### ISSUE TITLE
Fody build fails in some environments after updating Verify.XUnit from 21.3 to 22.1

### ISSUE THREAD

**Issue by tom-englert** [VerifyTests/Verify#1016]
e.g.
https://github.com/Fody/Fody/actions/runs/6418813822/job/17427360726?pr=1215

It's always the same error: 
```
Received: PeVerifierTests.TrimLineNumbers.Net4_7.received.txt
[IL]: Error: [C:\Code\net452\AssemblyToProcess.dll : UnsafeClass::MethodWithAmp] Unexpected type on the stack.
[IL]: Error: [C:\Code\net452\AssemblyToProcess.dll : UnsafeClass::get_NullProperty] Unexpected type on the stack.
[IL]: Error: [C:\Code\net452\AssemblyToProcess.dll : UnsafeClass::set_NullProperty] Unmanaged pointers are not a verifiable type.
3 Error(s) Verifying C:\Code\Fody\net452\AssemblyToProcess.dll
Verified: PeVerifierTests.TrimLineNumbers.verified.txt

[IL]: Error: [C:\Code\net452\AssemblyToProcess.dll : UnsafeClass::MethodWithAmp] Unexpected type on the stack.
[IL]: Error: [C:\Code\net452\AssemblyToProcess.dll : UnsafeClass::get_NullProperty] Unexpected type on the stack.
[IL]: Error: [C:\Code\net452\AssemblyToProcess.dll : UnsafeClass::set_NullProperty] Unmanaged pointers are not a verifiable type.
3 Error(s) Verifying C:\Code\Fody\net452\AssemblyToProcess.dll
```

- Difference is one extra blank line displayed in the ...verified.txt
- Seems to affect only windows environments, but works on Linux.

Not sure if this is a bug or a new behavior of Verify and we should remove the blank line in the ...verified.txt (but then why it works on Linux?)

**Comment by tom-englert** [comment]
Just checked this: `PeVerifierTests.TrimLineNumbers.verified.txt` starts with a blank line.

**Comment by tom-englert** [comment]
Sorry, I think it was the commit before, that caused the issue:
https://github.com/Fody/Fody/commit/9cb71795148ceb93a2db339792362bb83e72e928

**Comment by SimonCropp** [comment]
@tom-englert leave it with me. i will debug it

**Comment by tom-englert** [comment]
It's just the change in Fody, not related to Verify
