### ISSUE TITLE
Adding `net8.0` causes a couple verify tests to fail

### ISSUE THREAD

**Issue by bruno-garcia** [VerifyTests/Verify#1041]
#### Preamble

On this branch, I added `net8.0` on a series of tests: https://github.com/getsentry/sentry-dotnet/pull/2791
All but 3 are working fine.

The problem seems to be an empty space. That on each new run shows up:

![image](https://github.com/VerifyTests/Verify/assets/1633368/279ac6a3-f19c-4753-99d5-3e3cb0e96c36)

I can't get it accepted. I wonder if it's a leading space getting deleted in some tool.
If I add the space myself to the file. Tests then start passing. 
But I didn't get a `received` file to accept on disk.

![image](https://github.com/VerifyTests/Verify/assets/1633368/99b730b5-3e01-436a-874c-a5632cfa9df1)
But no files
![image](https://github.com/VerifyTests/Verify/assets/1633368/0344d0e2-f3b1-450e-bbcd-58906a10a184)

Fails in CI on Windows/macOS/Linux (e.g [Windows](https://github.com/getsentry/sentry-dotnet/actions/runs/6762560131/job/18378663530?pr=2791#step:13:1485))

My env:
```
bruno@DHPKTVF22X sentry-dotnet % dotnet --info
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-rc.2.23502.2/
```

Running Rider or `dotnet test`, same result. I also closed Rider since the diff tool was popping up even when I fired the tests in the CLI.

Where relevant, ensure you are using the current stable versions on your development stack. For example:

 * Visual Studio
 * [.NET SDK or .NET Core SDK](https://www.microsoft.com/net/download)
 * Any related NuGet packages

Any code or stack traces must be properly formatted with [GitHub markdown](https://guides.github.com/features/mastering-markdown/).

#### Describe the bug

I'm not too sure what's going on to be honest. I haven't contributed much to this repo since Verify was introduced so I need to prob educate myself more but it seems to have some issue since it's only on `net8.0`

#### Minimal Repro

Repro in this branch: https://github.com/getsentry/sentry-dotnet/pull/2791

`dotnet test SentryNoMobile.slnf` will show the failing tests.

#### Submit a PR that fixes the bug

Haven't figure out what's going on to be able to contribute today

**Comment by SimonCropp** [comment]
can u try this https://github.com/getsentry/sentry-dotnet/pull/2798

**Comment by bruno-garcia** [comment]
Thank you so much @SimonCropp as always!

**Comment by bruno-garcia** [comment]
Just verified (no pun intended) this problem was resolved! Thanks Simon.

I didn't want to raise an issue because seems specific to our set up, but if u know the answer, worth 25 points!

https://stackoverflow.com/questions/77442233/verify-snapshot-test-writes-all-frameworks-to-single-file
