### ISSUE TITLE
Way to scrub filenames in VerifyDirectory

### ISSUE THREAD

**Issue by javiercn** [VerifyTests/Verify#1072]
#### Is the feature request related to a problem

I'm using VerifyDirectory to validate the output of some process that generates a set of files and some of the files contain hashed versions in the name (like myfile.asdfadsf.css). 

I'm not interested in the particular contents of the file, and I want to avoid having to update the baseline every time the hash changes (which let's say can happen on every build).

If I use VerifyDirectory, I run into the issue that I have to update the baselines every time the hash changes.

#### Describe the solution

Would it be possible/reasonable to have a callback that lets the caller scrub the file name and not just the contents? So if I have myfile.asdfasdf.css, it could be scrubbed into something like `myfile.[hash].css`. The logic would be `Func<string,string>` (maybe some additional parameters for context if it's valuable).

#### Describe alternatives considered

I considered collecting the list of files writing them to a file and verifying that instead, but it's valuable to be able to check the structure and the contents in one go.

I considered renaming the files I generated, but that's also something I wanted to avoid doing as it replicates a lot of the work that VerifyDirectory already does.

**Comment by SimonCropp** [comment]
happy to accept a pull request for this
