### ISSUE TITLE
DateTimes not being scrubbed by default

### ISSUE THREAD

**Issue by MJB222398** [VerifyTests/Verify#1095]
#### Describe the bug

DateTimes are supposed to be scrubbed by verify by default. Whatever I try though they are not being scrubbed. Tried adding extra formats to cover them but even then it does not work.

#### Minimal Repro

If I have configured no global or local Verify settings and I run this:

`await Verifier.Verify(DateTime.Now.ToString("F"));`

I get the then unscrubbed date:

`15 December 2023 16:43:58`

**Comment by SimonCropp** [comment]
root objects are not scrubbed. since it makes no sense to have a verified file with the only content being `scrubbed`.

If you nest it, it will be scrubbed

```
await Verifier.Verify(
    new
    {
        Value = DateTime.Now.ToString("F")
    });
```

**Comment by MJB222398** [comment]
@SimonCropp Ok, my apologies looks like I went too far in my simplification of the perceived issue. My problem is not with a datetime as a root level object but with an HTML table where a cell (td) contains a date time. Basically I am wanting to verify a web page that contains a date time in the HTML but I do not know what the datetime will be and was expecting it to be scrubbed as per the documentation. So for example:

```
VerifyAngleSharpDiffing.Initialize();

var html = @"
    <!DOCTYPE html>
    <html>
    <body>
    <table>
      <tr>
        <th>Company</th>
        <th>Contact</th>
        <th>Country</th>
        <th>Date</th>
        <th>Guid</th>
      </tr>
      <tr>
        <td>Alfreds Futterkiste</td>
        <td>Maria Anders</td>
        <td>Germany</td>
        <td>15/12/2023 16:43:58</td>
        <td>b1c6cba5-de16-430b-9c01-6271443e7cd4</td>
      </tr>
      <tr>
        <td>Centro comercial Moctezuma</td>
        <td>Francisco Chang</td>
        <td>Mexico</td>
        <td>12/04/2023 11:41:58</td>
        <td>71727c10-9643-43e9-bdac-a4e55cf74450</td>
      </tr>
    </table>
    </body>
    </html>";

await Verifier.Verify(html, "html").PrettyPrintHtml();
```

This will NOT scrub the date times in those cells. Is that your expectation? Perhaps date times inside strings are not supposed to be scrubbed. The Guids in the next column are not scrubbed either. 

Interestingly though if I instead verify it as:

`await Verifier.VerifyXml(html);`

Then the Guids and date times are scrubbed.

If all is working as it should am I perhaps wanting to do something odd? Would supporting this be a bad idea? I guess for now at least I can implement some kind of custom scrubber.

**Comment by SimonCropp** [comment]
you can scrub inline guids https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#snippet-scrubinlineguids

i have not implemented scubbing of inline dates due to the perf impact. essentially do a tryparse on every combo of characters in a large string

**Comment by MJB222398** [comment]
@SimonCropp thanks. For me the performance is not going to be an issue as other components of my tests are orders of magnitude slower so this would go unnoticed. If this feature were disabled by default then is there really any harm in having it? Perhaps if developers had to define specific date time formats it could be faster with specific defined Regex patterns for those formats rather than just looking for absolutely everything as above. Anyway thanks for your help

**Comment by SimonCropp** [comment]
@MJB222398 fare enough. try this   https://github.com/VerifyTests/Verify/blob/main/docs/dates.md#inline-dates

**Comment by glen-84** [comment]
@SimonCropp I'm not seeing the global methods on `VerifierSettings`.

**Comment by SimonCropp** [comment]
have u updated to the latest nuget?

**Comment by glen-84** [comment]
> have u updated to the latest nuget?

Yes, I'm on `22.10.1`.

I do see the methods on `SettingsTask` and `VerifySettings`, but not the static methods in `VerifierSettings`.

**Comment by SimonCropp** [comment]
sigh. yeah i screwed up. new release incoming

**Comment by SimonCropp** [comment]
try 22.10.2. pending nuget updating

**Comment by glen-84** [comment]
Thanks for adding it.

When I tested the `SettingsTask` version earlier, I could swear that it replaced the date with `{Scrubbed}`, but unfortunately it's using the `DateTimeOffset_1` format, so I won't be able to use this feature. ([ref](https://github.com/orgs/VerifyTests/discussions/959))

Maybe a future change could be to allow the replacement string to be specified, for example:

```cs
VerifierSettings.ScrubInlineDateTimeOffsets("yyyy-MM-ddTHH\\:mm\\:ss.fffK", replaceWith: "{Scrubbed}");
```
