### ISSUE TITLE
Guids as string keys not being scrubbed.

### ISSUE THREAD

**Issue by SebastianStehle** [VerifyTests/Verify#1096]
Note: New issues raised, where it is clear the submitter has not read the issue template, are likely to be closed with "please read the issue template". Please don't take offense at this. It is simply a time management decision. If someone raises an issue, and can't be bothered to spend the time to read the issue template, then the project maintainers should not be expected to spend the time to read the submitted issue. Often too much time is spent going back and forth in issue comments asking for information that is outlined in the issue template.

#### Describe the bug

I have a custom dictionary class and a custom ID struct that is 90% of the time a struct. Everything works great and Guids are in general handled properly. 

But I have a guid in dictionaries where it does not work. I found a 2 year old bug about that:
https://github.com/VerifyTests/Verify/issues/74

I tried to dig into the code, but I am not sure how you have actually solved it. For my understanding it should be here: https://github.com/VerifyTests/Verify/blob/main/src/Verify/Serialization/VerifyJsonWriter.cs#L63. I can also not find a custom converter for dictionaries. Perhaps this is a regression...

Here is my screenshot from the merge tool.
![image](https://github.com/VerifyTests/Verify/assets/1236435/05d31247-f4b6-45b5-a2a7-7cc1d4a61925)

#### Minimal Repro

Happy to provide this if needed.

#### Submit a PR that fixes the bug

Submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.

**Comment by SebastianStehle** [comment]
I have found the code. It is this class:
 https://github.com/VerifyTests/Verify/blob/adca9992e4b260e40b361e1bb4ce2a8a8ebe5048/src/Verify/Serialization/CustomContractResolver.cs#L1

And the key is actually a string only. I solved it with custom contract resolver:

```
    private sealed class ContractResolver : IContractResolver
    {
        private readonly IContractResolver inner;

        public ContractResolver(IContractResolver inner)
        {
            this.inner = inner;
        }

        public JsonNameTable GetNameTable()
        {
            return inner.GetNameTable();
        }

        public JsonContract ResolveContract(Type type)
        {
            var contract = inner.ResolveContract(type);

            if (contract is JsonDictionaryContract dictionaryContract)
            {
                var originalKeyResolver = dictionaryContract.DictionaryKeyResolver!;

                dictionaryContract.DictionaryKeyResolver = (name, original) =>
                {
                    if (original is string id && Guid.TryParse(id, out var guid))
                    {
                        var index = Counter.Current.Next(guid);

                        return $"Guid_{index}";
                    }

                    return originalKeyResolver(name, original);
                };
            }

            return contract;
        }
    }
    ```
    
So it is probably more a feature request to also handle strings, like any other guid.

**Comment by SimonCropp** [comment]
try updating to the current nuget

**Comment by SebastianStehle** [comment]
I have commented the PR because I think the implementation is not as expected.
