### ISSUE TITLE
Changelog / release notes

### ISSUE THREAD

**Issue by glen-84** [VerifyTests/Verify#1099]
#### Is the feature request related to a problem

There doesn't appear to be a changelog or release notes for recent versions.

#### Describe the solution

Add a changelog, or add release notes to the releases page.

#### Describe alternatives considered

n/a

#### Additional context

n/a

**Comment by SimonCropp** [comment]
i used close milestones as release notes https://github.com/VerifyTests/Verify/milestones?state=closed

**Comment by ForNeVeR** [comment]
Currently, updates from Dependabot look like this:
![image](https://github.com/VerifyTests/Verify/assets/92793/67698632-5f03-4c8c-8158-a9b4823dad14)

While I sympathize with items loke "yolo" and "yolo2", the aforementioned "milestone" section also doesn't contain any explanations about the current release :)

Is everything alright here?

**Comment by SimonCropp** [comment]
yes i neglected to create a miletsone for the last release. here it is https://github.com/VerifyTests/Verify/issues?q=is%3Aclosed+milestone%3A25.3.0

as for dependabot listing commit messages on a PR. not much i can do about that. for most of my projects commit message dont mean much. for projects where i am the only contributor on, i dont feel the need to do clean commit message. ie i could push everything through a PR+squash commit process. But that would be significantly more work. I currently maintain 200+ nugets in my spare time, so i need to move quickly to keep up. I prefer to focus effort on quality unit tests and clean code, and not on a perfectly curated history of commit messages

**Comment by ForNeVeR** [comment]
I do not care about the commit messages _that_ much, mind you. But at least some way to know what's been changed in a new release would be nice to have.

I can see that you've created a milestone for the latest release, though, so perhaps it's enough information.

Also, now I see it's mentioned in the README, so for my taste it's alright. Thank you!

**Comment by cmeeren** [comment]
I propose having a curated changelog, if nothing else then at least to document breaking changes for new major versions. For package consumers, trying to look through issues and pull requests to try to ascertain which changes are breaking is generally a futile endeavor.
