### ISSUE TITLE
Issue with new `UseUtf8NoBom` setting

### ISSUE THREAD

**Issue by glen-84** [VerifyTests/Verify#1104]
#### Describe the bug

I'm trying to use the new functionality added [here](https://github.com/VerifyTests/Verify/pull/1074), but the initial [verified file](https://github.com/glen-84/verify-bom-issue/blob/main/UnitTest1.Test1.verified.txt) still seems to be created with a BOM.

The setting is added in [ModuleInitializer.cs](https://github.com/glen-84/verify-bom-issue/blob/main/ModuleInitializer.cs).

If you delete the 2 txt files, and run the test, you'll see that the verified file contains a BOM.

Am I missing something?

#### Minimal Repro

https://github.com/glen-84/verify-bom-issue

#### Submit a PR that fixes the bug

?

**Comment by SimonCropp** [comment]
i added a test that seems to pass https://github.com/glen-84/verify-bom-issue/pull/1

**Comment by SimonCropp** [comment]
what approach are you using to accept the changes?

**Comment by glen-84** [comment]
The issue is with the initial, empty, verified file. The test compares an _existing_ verified file with no BOM, which will pass since the received file is correctly no-BOM.

I'm using VS Code:

![image](https://github.com/VerifyTests/Verify/assets/261509/1380bf9a-06a2-4c8f-bd7e-f3a17f2315e6)

**Comment by glen-84** [comment]
Thanks Simon! 👍
