### ISSUE TITLE
Custom serializer support

### ISSUE THREAD

**Issue by adambajguz** [VerifyTests/Verify#1137]
Hi, 
currently Verify uses Argon as serialization framework. It would be nice to support other serializers like Newtonsoft.Json or System.Text.Json.

Are there any plans of adding custom serializer support?

**Comment by adambajguz** [comment]
Multiple reasons: `DateOnly`, `TimeOnly` support, speed, usage of YAML instad of JSON, Newtonsoft.Json and System.Text.Json are currently the most commonly used, ...

**Comment by SimonCropp** [comment]
* argon support DateOnly and TimeOnly 
 * argon is faster than Newtonsoft.Json 
 * System.Text.Json is not extensible enough to provide the full features that Verify supports. i have tried. happy to consider a PR if you want to have a go at implementing it

**Comment by SimonCropp** [comment]
for context i assume u know that argon is a fork of json dotnet

**Comment by SimonCropp** [comment]
the other challenge is the extensions to verify. the majority of them have json converters that target argon. to make them compat we would need a common abstraction for building converters

**Comment by adambajguz** [comment]
ok, closing
