### ISSUE TITLE
BUG: My custom serializer (Argon.JsonConverter) is not being applied to properties of an object

### ISSUE THREAD

**Issue by LorneCash** [VerifyTests/Verify#1162]
First off, let me say that I'm hoping there's something simple in the documentation that I've missed.  I've been through it several times and I can't seem to figure this out so please excuse my ignorance if this is my fault.  Also, I've intentionally not included all the code necessary to replicate this because I think it's easier to explain this way.  I can/will make a sample project if you need it but I'm guessing that won't be necessary to understand the problem if it is something I missed.  If it is actually a bug, I have no problem making a full sample for you, so just let me know if that's necessary.

I have a custom class called `TimeOnlyOffset`.  It should serialize to something like this: `"18:30:00 CST"`

**Here's the Custom Serializer:**
```c#
public class TimeOnlyOffsetArgonConverter : JsonConverter
{
	public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
	{
		if (value is not TimeOnlyOffset timeOnlyOffset) return;
		var timeFormat = timeOnlyOffset.Ticks switch
		{
			var ticks when ticks % TimeSpan.TicksPerMillisecond > 0 => "HH:mm:ss.fffffff",
			var ms when ms % TimeSpan.TicksPerSecond > 0 => "HH:mm:ss.fff",
			var s when s % TimeSpan.TicksPerMinute > 0 => "HH:mm:ss",
			_ => "HH:mm"
		};

		var time = timeOnlyOffset.TimeOnly.ToString(timeFormat);
		var zone = timeOnlyOffset.TimeZone.CodeUSA();

		writer.WriteValue($"{time} {zone}");
	}

	public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
	{
		throw new NotImplementedException();
	}

	public override bool CanConvert(Type objectType) => objectType == typeof(TimeOnlyOffset);
}
```

**And here are my UnitTests:**

This test serializes an instance of `TimeOnlyOffset` using `TimeOnlyOffsetArgonConverter` to get the correct result of `"18:30:00 CST"`

```c#
[TestMethod]
public async Task WriteTestOutput_TimeOnlyOffset()
{
	var verifySettings = new VerifySettings();
	verifySettings.AddExtraSettings(x =>
	{
		x.Converters.Add(new TimeOnlyOffsetArgonConverter());
	});

	var test = new TimeOnlyOffset(18, 30, TimeZoneUSA.Central);
	await Verify(test, verifySettings);
}
```

This test serializes an instance of `TimeOnlyOffset` using `TimeOnlyOffsetArgonConverter` but this time it's in a property of an example class called `MySettings1` and again it gets the correct result of `"18:30:00 CST"`

```c#
[TestMethod]
public async Task WriteTestOutput_Settings_Prop4()
{
	var verifySettings = new VerifySettings();
	verifySettings.AddExtraSettings(x =>
	{
		x.Converters.Add(new TimeOnlyOffsetArgonConverter());
	});

	var test = new MySettings1 { Prop4 = new TimeOnlyOffset(18, 30, TimeZoneUSA.Central) };
	await Verify(test.Prop4, verifySettings);
}
```

This is the problem case. Here you can see I've created a test class called `MySettings1` with a property of type `TimeOnlyOffset` named `Prop4`.

```c#
[TestMethod]
public async Task WriteTestOutput_Settings()
{
	var verifySettings = new VerifySettings();
	verifySettings.AddExtraSettings(x =>
	{
		x.Converters.Add(new TimeOnlyOffsetArgonConverter());
	});

	var test = new MySettings1 { Prop4 = new TimeOnlyOffset(18, 30, TimeZoneUSA.Central) };
	await Verify(test, verifySettings);
}
```

The problem here is it's not using `TimeOnlyOffsetArgonConverter` to do the serialization.  Verify in this case is behaving as if `TimeOnlyOffsetArgonConverter` is not there at all.  It's serializing every property in `MySettings1 ` as expected but  for `Prop4` (the instance of `TimeOnlyOffset`) it's serializing every property there as well and not using `TimeOnlyOffsetArgonConverter`.

**I'm expecting a result like this:**
```
{
  Prop1: false,
  Prop4: "18:30:00 CST"
}
```

**But I'm getting this:**
```
{
  Prop1: false,
  Prop4: {
    Hours: 18,
    Minutes: 30,
    Ticks: 666000000000,
    UtcTicks: 18000000000,
    TimeOfDay: 18:30:00,
    TimeZone: Central Standard Time,
    TimeOnly: Time_1,
    LocalTimeOnly: Time_1,
    UtcTimeOnly: Time_2
  }
}
```

**Comment by SimonCropp** [comment]
can u wrap the repro up into a single solution to save me some time

**Comment by LorneCash** [comment]
[ISSUE_1162.zip](https://github.com/VerifyTests/Verify/files/14610087/ISSUE_1162.zip)

Here's the solution.  You can see the two tests pass and are using `TimeOnlyOffsetArgonConverter` as expected but the one does not work and I'm not sure what I'm doing wrong.

**Comment by SimonCropp** [comment]
i think your canconvert should be 
```

	public override bool CanConvert(Type objectType) =>
		objectType == typeof(TimeOnlyOffset) ||
		objectType== typeof(TimeOnlyOffset?);
```

**Comment by SimonCropp** [comment]
or u can simplify your converter as follows:

```
public class TimeOnlyOffsetArgonConverter : WriteOnlyJsonConverter<TimeOnlyOffset>
{
	public override void Write(VerifyJsonWriter writer, TimeOnlyOffset timeOnlyOffset)
	{
		var timeFormat = timeOnlyOffset.Ticks switch
		{
			var ticks when ticks % TimeSpan.TicksPerMillisecond > 0 => "HH:mm:ss.fffffff",
			var ms when ms % TimeSpan.TicksPerSecond > 0 => "HH:mm:ss.fff",
			var s when s % TimeSpan.TicksPerMinute > 0 => "HH:mm:ss",
			_ => "HH:mm"
		};

		var time = timeOnlyOffset.TimeOnly.ToString(timeFormat);
		var zone = timeOnlyOffset.TimeZone.CodeUSA();

		writer.WriteValue($"{time} {zone}");
	}
}
```

**Comment by SimonCropp** [comment]
here are the docs https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#jsonnet-converter

**Comment by SimonCropp** [comment]
and you will get better perf by replacing all those `Add(new TimeOnlyOffsetArgonConverter` with a single on in a module initializer

```

public static class ModuleInitializer
{
	[ModuleInitializer]
	public static void Init()
	{
		VerifierSettings.AddExtraSettings(x =>
		{
			x.Converters.Add(new TimeOnlyOffsetArgonConverter());
		});
	}
}
```

**Comment by LorneCash** [comment]
@SimonCropp OMG thank you so much!! I kinda figured it was me doing something wrong... I really appreciate your help on this.  I've been trying to figure this out for hours.
