### ISSUE TITLE
Consider using NuGet's Central Package Management (CPM) to simplify versioning

### ISSUE THREAD

**Issue by MattKotsenas** [VerifyTests/Verify#1214]
Would you be open to using NuGet's [Central Package Management (CPM)](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management) in the repo?

It would centralize the version upgrades you already handle, and it additionally supports [transitive pinning](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management#transitive-pinning) which would come in handy for example in the SourceGenerator tests, where the Microsoft.CodeAnalysis.*.Testing packages pull in vulnerable versions of dependencies. We could use transitive pinning to upgrade those projects to safe versions without adding them as a direct dependency which both clutters the project and confuses code analysis tools that would otherwise see the references as unused and offer to remove them (thus introducing a potential vulnerability.

I'm happy to do the work myself but wanted to ask first.

**Comment by SimonCropp** [comment]
happy to have this happen. 

the reason i have held off so far is the lat time i tried it Rider didnt fully support it. do u know if it does now?


also is there a way to automate it. i would like to script it for all my projects

**Comment by MattKotsenas** [comment]
I'm not a Rider user so I can't easily check, but it [appears to be supported](https://blog.jetbrains.com/dotnet/2022/11/07/nuget-central-package-management-comes-to-jetbrains-rider/).

There aren't "official" tools from Microsoft for the conversion, but there are a couple of community tools to automate the conversion: https://github.com/microsoft/MSBuildSdks/blob/main/src/CentralPackageVersions/Migration.md.

To clarify responsibilities then, do you want me to convert for this repo, or do you want to handle it so you can do it across all your repos? No preference just didn't want to sign you up for work if you weren't interested.

**Comment by SimonCropp** [comment]
@MattKotsenas u may as well let me do it. given i want to do it for multiple repos, this one will be caught in that process

**Comment by SimonCropp** [comment]
@MattKotsenas https://github.com/Webreaper/CentralisedPackageConverter

**Comment by SimonCropp** [comment]
done
