### ISSUE TITLE
Sorting of immutable dictionary

### ISSUE THREAD

**Issue by nZeus** [VerifyTests/Verify#1230]
`Verify` has a nice feature of sorting dictionaries, https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#dictionary-sorting

But unfortunately it doesn't cover ImmutableDictionaries.

Could you please add support of immutable dictionaries as well

**Comment by SimonCropp** [comment]
it seems to work for me. can you share a failing unit test as a Pull Request

**Comment by nZeus** [comment]
Oh... My bad. Indeed, it works as expected.
We use a wrapper over the Verify method, where we do serialization ourselves, and the result is then passed to Verify.
This way we can keep an actual json in the verified files.

Anyways, Verify does sort immutable dictionaries, so I'm closing this feature request. Thank you for your help Simon!

**Comment by SimonCropp** [comment]
>We use a wrapper over the Verify method, where we do serialization ourselves, and the result is then passed to Verify. This way we can keep an actual json in the verified files.

if you want json, why not UseStrictJson  ? https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#usestrictjson

**Comment by nZeus** [comment]
I think I remember why we decided to have it this way.
We rely heavily on the System.Text.Json serialization, e.g. polymorphic serialization ([JsonDerivedType]). 
With Argon, we couldn't get expected output (e.g. no `"$type": "..."` element, and it doesn't respect `[JsonIgnore]` attributes)

**Comment by SimonCropp** [comment]
so r u using https://github.com/VerifyTests/Verify?tab=readme-ov-file#verifyjson or https://github.com/VerifyTests/Verify.SystemJson ?

**Comment by nZeus** [comment]
We use a custom wrapper, which is the same as:
```cs 
return Verify(
    target: System.Text.Json.JsonSerializer.Serialize(sut, options),
    extension: "json", 
    sourceFile: sourceFile, 
    settings: settings);
```
I don't see any difference with `VerifyJson()` and the `Verify.SystemJson` extension, since the serialization happens _before_ the target is passed to Verify, so we cannot use some of the nice features of Verify (e.g. Sorted Dictionaries)...

**Comment by SimonCropp** [comment]
`VerifyJson` wont give u sorting. since it assume that the order is potentially important for json.

but, because Verify knows the string is json and it can be tokenized, it does give u access to scrubbing features. eg 

 * guid https://github.com/VerifyTests/Verify/blob/main/docs/guids.md
 * date https://github.com/VerifyTests/Verify/blob/main/docs/dates.md
 * named members https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#ignore-member-by-name
 
 i am happy to consider a Pull Request that adds support for sorting when using `VerifyJson`

**Comment by nZeus** [comment]
You're right. `VerifyJson` is a better option then the one we do. And it's indeed nice to have access to scrubbing features. Thank you for the ideas!

As for the sorting of dictionaries - we temporary solved it by forcing the order in the JsonConverter's Write method.
That would be great if VerifyJson can get  support for sorting. We could then clean up our workaround.

**Comment by nZeus** [comment]
I tried to use VerifyJson, but it generated a strange output for this json:
```
{
  "Arr": [
    {
      "$type": "Start",
      "Input": "Test"
    }
  ],
  "Single": {
    "$type": "Start",
    "Input": "Test"
  }
}
```

The output is:
```
{
  "Arr": [
    {
      "Input": "Test"
    }
  ],
  "Single": {
    "$type": "Start",
    "Input": "Test"
  }
}
```

For some reason it lost the `"$type"` element, but only when the object is in an array.

The tested structure was this:
```
        public record Test
        {
            public StageState[] Arr { get; set; }
            public StageState Single { get; set; }
        }
```

Do you know if this is an expected behavior?
