### ISSUE TITLE
Wrong verified files path on Azure DevOps build agents

### ISSUE THREAD

**Issue by majkelllo** [VerifyTests/Verify#1233]
The tests works great locally, however, after running them on Private Azure DevOps build agents, the tests are failing.
The tests are failing because somehow the .received. files are generated in wrong directory. 
We are running tests using standard `dotnet test {PATH_TO_CSPROJ}`, without any custom config / arguments

The SourceCode path ( containing verified files ) is:
**C:\agent\_work\17\s**\MyService.UnitTests\Approvals

While somehow the framework puts .received. files in:
C:\s\MyService.UnitTests\Approvals

This is really strange, is there some magic environment variable that is used by the Framework to determine where to put the .received. files ? ( C:\s\ is not a directory used by Azure DevOps, it is created by VerifyTests framework somehow )

**Comment by SimonCropp** [comment]
are you using custom code to put your files in “/Approvals”?

**Comment by majkelllo** [comment]
Yes I am using following code:
```csharp
var settings = new VerifySettings();
settings.UseDirectory("Approved");
settings.UseFileName("ValidCsproj");
await Verify(solutionFileContent.Projects[0].Content, settings);
```

I have also tried with simple UseFileName:
```charp
await Verify(solutionFileContent.Projects[0].Content).UseFileName("VisualStudioCodeGeneratorTests.ValidCsproj");
```

Unfortunately the result is the same.

**Comment by SimonCropp** [comment]
i suspect it because UseDirectory leverages the current directory. and that is difference in devops


try this

```
    public static class ModuleInitializer
    {
        [ModuleInitializer]
        public static void Init() =>
            Verifier.UseProjectRelativeDirectory("Approvals");
    }
```

**Comment by majkelllo** [comment]
@SimonCropp I have just tried this method - it worked like a charm. Many thanks for quick help ! Issue resolved
