### ISSUE TITLE
Named Guid are not scrubbed with instance settings

### ISSUE THREAD

**Issue by davla** [VerifyTests/Verify#1246]
Adding a named Guid *via instance settings* does not replace the Guid, unless the automatic Guid scrubbing is turned off. This is not always desirable, though.

The global and fluent APIs do replace named Guids, with or without automatic Guid scrubbing.

The three setting APIs should have the same behavior.

Attached, a very minimal repro project: [minimal-repro.zip](https://github.com/user-attachments/files/16249731/minimal-repro.zip). The two tests should pass with the same verified file, but they don't.

#### Versions

I reproduced the issue in two scenarios.

The minimal repro:
- .NET 8
- xUnit 2.9.0
- Verify.Xunit 25.3.1

A private repository

- .NET 8
- MsTest 3.4.3
- Verify.MsTest 25.3.1

**Comment by SimonCropp** [comment]
u should remove the below from you project. it is a bug in VS that puts those in
```
    <ItemGroup>
      <None Update="UnitTest1.Test1.received.txt">
        <DependentUpon>NamedGuidSnapshotTests.cs</DependentUpon>
      </None>
      <None Update="UnitTest1.Test1.verified.txt">
        <DependentUpon>NamedGuidSnapshotTests.cs</DependentUpon>
      </None>
    </ItemGroup>
```
