### ISSUE TITLE
Duplicate 'Xunit.TestFramework' attribute

### ISSUE THREAD

**Issue by mlinderor** [VerifyTests/Verify#1251]
Note: New issues raised, where it is clear the submitter has not read the issue template, are likely to be closed with "please read the issue template". Please don't take offense at this. It is simply a time management decision. If someone raises an issue, and can't be bothered to spend the time to read the issue template, then the project maintainers should not be expected to spend the time to read the submitted issue. Often too much time is spent going back and forth in issue comments asking for information that is outlined in the issue template.

#### Preamble

When using recent versions of Verify and Verify.Xunit, both assemblies include the 
[assembly: VerifyXunit.UsesVerifyAttribute()]
output to the [].Attributes.cs
and gives this error when compiling the test project
**Duplicate 'Xunit.TestFramework' attribute**
<package id="Verify" version="25.3.2" targetFramework="net472" />
<package id="Verify.Xunit" version="22.11.3" targetFramework="net472" />

Current stable versions:
<package id="Verify" version="25.3.2" targetFramework="net472" />
<package id="Verify.Xunit" version="22.11.3" targetFramework="net472" />

Microsoft Visual Studio Professional 2022
Version 17.8.7
VisualStudio.17.Release/17.8.7+34601.278
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Professional

ASP.NET and Web Tools   17.8.358.6298
ASP.NET and Web Tools

C# Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

PowerShell Pro Tools for Visual Studio   1.0
A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio.

Razor (ASP.NET Core)   17.8.3.2405201+d135dd8d2ec1c2fbdee220e8656b308694e17a4b
Provides languages services for ASP.NET Core Razor.

Any code or stack traces must be properly formatted with [GitHub markdown](https://guides.github.com/features/mastering-markdown/).

#### Describe the bug

Because of output the assembly reference from both packages, the project gives an error:
Duplicate 'Xunit.TestFramework' attribute

https://github.com/search?q=repo%3AVerifyTests%2FVerify+WriteCodeFragment&type=code

If you updated [src/Verify.Xunit/buildTransitive/Verify.Xunit.props](https://github.com/VerifyTests/Verify/blob/39fb3f979241eacba8f02bca4ed6f86d3c24d154/src/Verify.Xunit/buildTransitive/Verify.Xunit.props#L24)
to only add the output if the assembly is not already referenced, or remove it altogether, it will resolve the issue.

Update the library to eliminate the bug.

#### Minimal Repro

Create test project on framework 4.7.2
Add reference to 
<package id="Verify" version="25.3.2" targetFramework="net472" />
<package id="Verify.Xunit" version="22.11.3" targetFramework="net472" />
 <package id="xunit" version="2.9.0" targetFramework="net472" />
 <package id="xunit.abstractions" version="2.0.3" targetFramework="net472" />
 <package id="xunit.analyzers" version="1.15.0" targetFramework="net472" developmentDependency="true" />
 <package id="xunit.assert" version="2.9.0" targetFramework="net472" />
 <package id="xunit.core" version="2.9.0" targetFramework="net472" />
 <package id="xunit.extensibility.core" version="2.9.0" targetFramework="net472" />
 <package id="xunit.extensibility.execution" version="2.9.0" targetFramework="net472" />
 <package id="xunit.runner.visualstudio" version="2.8.2" targetFramework="net472" developmentDependency="true" />
 ```

[VerifyXunit.UsesVerify]
[TestClass]
public partial class ApiGatewayKeyHelperTests : VerifyXunit.VerifyBase, IClassFixture<ApiGatewayKeyHelperTestsContext>, IDisposable
{
 ApiGatewayKeyHelperTestsContext _context;
 public ApiGatewayKeyHelperTests() : base() { _context = new ApiGatewayKeyHelperTestsContext(); }
 private ApiGatewayKeyHelperTests(ApiGatewayKeyHelperTestsContext context) //: base()
 {
     _context = context;
 }
 [Theory]
 [MemberData(nameof(GetData))]        
 public Task UseFileNameWithParam(string arg)
 {            
     //VerifyXunit.Verifier.Verify()
     return Verify(arg)
     .UseFileName($"{arg}.UseFileNameWithParam");
 }
 public static IEnumerable<object[]> GetData()
 {
     var temp = new List<object[]>();
     temp.Add(new object[]
     {
         "Blue"
     });
     return temp;
 }
}
 public partial class ApiGatewayKeyHelperTestsContext : IDisposable
 {
}
```
#### Submit a PR that fixes the bug
https://github.com/VerifyTests/Verify/pull/1250

https://github.com/search?q=repo%3AVerifyTests%2FVerify+WriteCodeFragment&type=code

**Comment by SimonCropp** [comment]
you should no longer need `[VerifyXunit.UsesVerify]` on any test class

**Comment by SimonCropp** [comment]
`VerifyBase` already has `[TestClass]`. so u dont need it on any inherited classes

**Comment by SimonCropp** [comment]
if you are still having issues please follow the issue template

>  Upload this repro as part of the issue, as a public GitHub repository or a downloadable zip.

**Comment by mlinderor** [comment]
> `VerifyBase` already has `[TestClass]`. so u dont need it on any inherited classes

Even when removed the error occurs. I appreciate you relooking into this issue.

**Comment by SimonCropp** [comment]
@mlinderor can you share a repro as a zip or a github repository

**Comment by mlinderor** [comment]
https://github.com/mlinderor/VerifyDemoXunitAttr
![image](https://github.com/user-attachments/assets/e885c60b-e364-4177-9345-d026437c9636)

**Comment by SimonCropp** [comment]
can u try 26.0.1

**Comment by mlinderor** [comment]
That eliminated the error and allows me to run my unit test. Thanks.
