### ISSUE TITLE
new warning when using Visual Studio 2022 17.9 

### ISSUE THREAD

**Issue by fforjan** [VerifyTests/Verify#1255]
Some of our build machines are still with a Visual Studio 2022 17.9 and not 17.10 and for internal reasons - large company, different teams, bla bla bla, the upgrade will come later this year.
but when using the latest package, we get
```
 CSC : warning CS9057: The analyzer assembly 'C:\Users\AzDevOps\.nuget\packages\verify.mstest\26.0.1\analyzers\dotnet\roslyn4.4\cs\Verify.MSTest.SourceGenerator.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.9.0.0'. 
```

Is it expected that Verify breaks compatibility with older visual studio version  ?
we're worried that the warning is hiding other things

**Comment by fforjan** [comment]
@SimonCropp  thanks for your reactivity !

**Comment by SimonCropp** [comment]
just pushed 26.1.1 to nuget. might take 15min for nuget to refresh its cache

**Comment by michael-freidgeim-webjet** [comment]
@SimonCropp  Is it possible to downgrade the compiler version to 4.8?
We are getting errors from [CodeQL analyser](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#building-c)

> CSC : warning CS9057: The analyzer assembly '/home/runner/.nuget/packages/verify.mstest/28.2.0/analyzers/dotnet/roslyn4.4/cs/Verify.MSTest.SourceGenerator.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'. 

https://stackoverflow.com/questions/79279857/verifytests-testcontext-is-a-type-which-is-not-valid-in-the-given-context

**Comment by SimonCropp** [comment]
@michael-freidgeim-webjet try version 2.6.0

**Comment by SimonCropp** [comment]
@michael-freidgeim-webjet version 4.9 of the compiler is compatible back to Visual Studio 2022 version 17.9.0 which was released  11 months ago. isnt it time for you to upgrade your VS version?
