### ISSUE TITLE
Feature to allow asserting specific fields on the received file.

### ISSUE THREAD

**Issue by TotalTest** [VerifyTests/Verify#1258]
I have a specific use case and couldn't see in the docs any examples of this being possible, when verifying a json object for example we can currently scrub lines, but there are properties I want to make specific assertions on. For example I may not want to scrub all datetimes, a specific datetime property I want to assert that it equals a value that I expect.

I have considering snapshooter just for this use case but would really like to go with Verify. With snapshooter there is a section in their docs titled **Assert Fields in Snapshots** which is essentially what I'm after :
https://github.com/SwissLife-OSS/snapshooter

**Example:**
Existing feature: for scrubbing specific members we can currently do:
`await Verify(result).ScrubMember<Poco>(a => a.Dt);`

Request: assert specific field against a known expected value, verify the rest of the object as normal:
`await Verify(res).AssertMember<Poco>(a => a.Dt == "02/01/2009 9:07 PM");`

Apologies if this already possible but I couldn't find a concrete example.

**Comment by SimonCropp** [comment]
why would you not use a standard assertion library for asserting those members?

**Comment by TotalTest** [comment]
> why would you not use a standard assertion library for asserting those members?

Since the objects I’ll be verifying will be quite large and complex files I was hoping verify would do most of the verification and I could just pick a few fields for specific assertions.

**Comment by SimonCropp** [comment]
Hows this https://github.com/VerifyTests/Verify.Assertions  ?

**Comment by TotalTest** [comment]
This looks great and thank you for such a quick turnaround. I'm not sure if I'm doing something wrong but I can't get it to work for me - below is a simple example (not my real life use case), but maybe you can try and replicate?

I'd expect the Dt property to pass due to the new assert call:

![image](https://github.com/user-attachments/assets/0f0a1add-2043-4749-91e3-70523ec6d505)

Here's the code for a quick copy and paste

```
 [Fact]
 public async Task Test6()
 {
     var dt = DateTime.Now.ToLongTimeString();
     var res = new SObject
     {
         Name = "n",
         Value = "v",
         A = "a",
         B = "b",
         C = "c",
         Dt = dt
     };

     await Verify(res)
         .Assert<SObject>(a => Assert.Equal(dt, a.Dt));
 }
```

```
public class SObject
{
    public string Name { get; set; }
    public string Value { get; set; }
    public string A { get; set; }
    public string B { get; set; }
    public string C { get; set; }
    public string Dt { get; set; }
}
```

Also would it possible to support .net7? (I know it's end of life but our org is still yet to give approval for using net8).

**Comment by SimonCropp** [comment]
your test is not consistent since you have a date as a string. you need to combine it with `ScrubInlineDateTimes` https://github.com/VerifyTests/Verify/blob/main/docs/dates.md#inline-dates

```
    [Fact]
    public async Task Test6()
    {
        var dt = DateTime.Now.ToLongTimeString();
        var res = new SObject
        {
            Name = "n",
            Value = "v",
            A = "a",
            B = "b",
            C = "c",
            Dt = dt
        };

        await Verify(res)
            .ScrubInlineDateTimes("T")
            .Assert<SObject>(a => Assert.Equal(dt, a.Dt));
    }
```   

> Also would it possible to support .net7?

I have for now. but you should consider this a short term solution. net 8 has been out for over 8 months, if your org cant update in that timeframe, then FOSS projects should not be expected to go to extra effort to enable that

**Comment by TotalTest** [comment]
Excellent that you very much Simon I have it working and will definitely be able to use this. I will close this and if I come across any issues I can raise in the Verify.Assertions repo. I appreciate the quick solution.
