### ISSUE TITLE
Add comparison link into test output for easy diff in Rider.

### ISSUE THREAD

**Issue by mfilippov** [VerifyTests/Verify#1260]
#### Is the feature request related to a problem
Add support open diff by link in Rider

#### Describe the solution

If you will write text in text output which matched this regex:
```
".*Compare\\(Rider\\):?\\s?=?\\s?“?\"(.+)\",\"(.+)\"”?"
```
like: `Compare(Rider): "file:///actualFilePath","file:///expectedFilePath"`

I think it is better that open diff for problem automatically.

**Comment by SimonCropp** [comment]
> I think it is better that open diff for problem automatically.

are you saying you would prefer that the rider diff did not open automatically

**Comment by mfilippov** [comment]
Yes. Open diff from output windows it is better experience from my opinion.

**Comment by SimonCropp** [comment]
are other diff tools supported? eg

```
Compare(BeyondCompare): "file:///actualFilePath","file:///expectedFilePath"
```

where is this feature documented?

**Comment by mfilippov** [comment]
@SimonCropp We added official docs about it.

**Comment by SimonCropp** [comment]
link?

**Comment by mfilippov** [comment]
https://www.jetbrains.com/help/rider/Analyze_test_results.html#compare-files-from-test-output
