### ISSUE TITLE
Allow member scrub/ignore with predicate

### ISSUE THREAD

**Issue by leorg99** [VerifyTests/Verify#1268]
#### Is the feature request related to a problem

Take for example this [class](https://github.com/HangfireIO/Hangfire/blob/main/src/Hangfire.Core/Storage/Monitoring/JobDetailsDto.cs).  I want to be able to scrub property/member names and string dictionary keys using a predicate where the member name is passed and I can return a bool indicating whether to scrub or ignore. This would allow me to do something like `name => name.EndsWith("At");`

#### Describe the solution

Add the following overload to `public void ScrubMember(string name)` and similar:
```
public void ScrubMember(Func<string, bool> predicate);

// Pass declaring type and name of member
public void ScrubMember(Func<Type, string, bool> predicate);
```

These may have to be `Expression<T>` parameters.

#### Additional context

Add any other context about the feature request here.

**Comment by SimonCropp** [comment]
happy to consider a pull request for this
