### ISSUE TITLE
Poor "The prefix has already been used" Exception message

### ISSUE THREAD

**Issue by matkoch** [VerifyTests/Verify#1276]
I assume this should be `Verify().UseMethodName()` etc.

https://github.com/VerifyTests/Verify/blob/055d9b2c426a3be75c42e1fe62cc1573b8b47033/src/Verify/Naming/PrefixUnique.cs#L13

**Comment by matkoch** [comment]
On a sidenote, calling `Verify` in a theory, I always have to call `UseParameters`. The method documentation though claims: `In most cases the parameter parameter values can be automatically resolved.`. Under what circumstances is that possible?

**Comment by matkoch** [comment]
@SimonCropp there's still an open question. When are parameters automatically resolved?

**Comment by SimonCropp** [comment]
@matkoch yep sorry for the delayed response, i had not meant to close this before answering your question, but forgot that the PR merge would auto close it

i have updated the xml docs

```
/// <summary>
/// Define the parameter values being used by a parameterised (aka data driven) test.
///
/// Scenarios:
/// 
/// <list type="bullet">
///   <item>Verify.Expecto: Does not currently support `UseParameters()`.</item>
///   <item>Verify.Fixie: Automatically detects the method parameters via a custom ITestProject https://github.com/VerifyTests/Verify/blob/main/docs/parameterised.md#fixie.</item>
///   <item>Verify.MSTest: Does not detect the parametrised arguments, as such `UseParameters()` is required..</item>
///   <item>Verify.NUnit: Automatically detects the method parameters. So `UseParameters()` is not required unless using custom parameters.</item>
///   <item>Verify.Xunit: Does not detect the parametrised arguments, as such `UseParameters()` is required.</item>
///   <item>Verify.XunitV3: Automatically detect the method parameters for built in types (string, int, bool etc), but for complex types `UseParameters()` is required.</item>
/// </list>
///
/// In the scenarios where parameters are not automatically detected, an exception will be thrown instructing the potential need for <see cref="UseParameters" />
/// Not compatible with <see cref="UseTextForParameters" />.
/// </summary>
```

I have also updated the docs https://github.com/VerifyTests/Verify/blob/main/docs/parameterised.md#useparameters

does that clarify things?
