### ISSUE TITLE
Override default Counters comparers

### ISSUE THREAD

**Issue by JaktensTid** [VerifyTests/Verify#1285]
#### Is the feature request related to a problem

Counters comparers (like `DateTimeOffsetComparer`) are hardcoded and there is no way to change default comparer.
In some cases I want to override it. For example `DateTimeOffset` has higher accuracy than `timestamp with timezone` in postgres. Hence counter works incorrectly for the same DateTimeOffset that was saved and loaded back from the database, because nanoseconds part is lost.

#### Describe the solution

Add VerifierSettings.CounterDateTimeOffsetComparer, VerifierSettings.CounterDateComparer, etc. These properties must accept IEqualityComparer interface.

#### Describe alternatives considered

-

#### Additional context

-

**Comment by SimonCropp** [comment]
@JaktensTid looks good. happy to accept a PR

**Comment by SimonCropp** [comment]
does this suffice?
https://github.com/VerifyTests/Verify/blob/main/docs/dates.md#custom-comparers

**Comment by SimonCropp** [comment]
@JaktensTid  ?

**Comment by JaktensTid** [comment]
Hi, let me check today

**Comment by JaktensTid** [comment]
> bump

Hi, I think thats fine. We can close this MR
