### ISSUE TITLE
Different behavior between Verify.SystemJson and Verify.NewtonsoftJson for empty property

### ISSUE THREAD

**Issue by gpetrou** [VerifyTests/Verify#1293]
#### Describe the bug

Use the following with Verify.SystemJson:

```
[Fact]
public Task TestEmpty() =>
    Verify(JsonNode.Parse("""
    {
        "empty":{}
    }
    """));
```

It results in:
```
{
  empty: {}
}
```

Use the following with Verify.NewtonsoftJson:

```
[Fact]
public Task TestEmpty() =>
    Verify(JObject.Parse("""
{
    "empty":{}
}
"""));
```
It results in:
```
{
  {}
}
```

The problem seems to be happening when https://github.com/VerifyTests/Verify/blob/53e462f990e5a2f26b1a34e8c0a714d89e845296/src/Verify/Serialization/VerifyJsonWriter.cs#L290 is called with an empty collection.

It would be nice if `Verify.NewtonsoftJson` could produce the same result as `Verify.SystemJson`. I checked the settings and I don't see an option to fix that. Perhaps I missed it?

**Comment by SimonCropp** [comment]
try this 


    [Fact]
    public Task TestEmpty() =>
        Verify(
            JObject.Parse(
                """
                {
                    "empty":{}
                }
                """))
            .DontIgnoreEmptyCollections();

**Comment by gpetrou** [comment]
Oh, I see. OK thanks. I was only looking at the JSON settings.
