### ISSUE TITLE
New test framework support

### ISSUE THREAD

**Issue by thomhurst** [VerifyTests/Verify#1295]
#### Is the feature request related to a problem

I've been building a new testing framework for .NET and noticed that you've got specialised packages for the existing major test frameworks. Would I or yourselves need to do anything to support my framework?

#### Describe the solution

New packages for TUnit

My framework can be found here: https://github.com/thomhurst/TUnit

**Comment by SimonCropp** [comment]
i can take a look

first question is how do i access the current test parameter values from the static context?  the other test frameworks use an async local to give access

**Comment by thomhurst** [comment]
> i can take a look
> 
> first question is how do i access the current test parameter values from the static context? the other test frameworks use an async local to give access

Thanks @SimonCropp . You can access this via:

`TestContext.Current!.TestDetails.TestClassArguments`

**Comment by SimonCropp** [comment]
@thomhurst as much a think strong naming adds no value, it will negatively impact the uptake of TUnit

**Comment by thomhurst** [comment]
> @thomhurst as much a think strong naming adds no value, it will negatively impact the uptake of TUnit

Sorry what do you mean?

**Comment by SimonCropp** [comment]
tunit is not strong named. most potential consumers will want it to be strong named

**Comment by thomhurst** [comment]
Ohhh you mean key signing the assembly/package? Thanks for the heads up. I'll raise an issue on my repo so I don't forget about it :)

**Comment by SimonCropp** [comment]
this is some nunit code

```
[TestFixtureSource(nameof(FixtureArgs))]
public class TestFixtureSourceAndTestCaseUsage(string arg1, int arg2)
{
    [TestCase("FromTestCase2")]
    public Task Test(string arg3) =>
        Verify(
            new
            {
                arg1,
                arg2,
                arg3
            });

    static object[] FixtureArgs =
    [
        new object[]
        {
            "Value2",
            2
        }
    ];
}
```

whats the equivalent in TUnit?

**Comment by SimonCropp** [comment]
this

```

    [Test]
    [Arguments((float)1.1)]
    public Task Float(float arg) =>
        Verify(arg);
```
results in 
```
33>Float_ParametersSample_49363d0d3fb0455cb46335bd8b7587a2.Generated.cs(18,39): Error CS0664 : Literal of type double cannot be implicitly converted to type 'float'; use an 'F' suffix to create a literal of this type
```

if i use 

```
    [Test]
    [Arguments(1.1F)]
    public Task Float(float arg) =>
        Verify(arg);
```
i get 
```
33>Float_ParametersSample_096a4f03ccd54ee285b352b9f622e9ee.Generated.cs(18,39): Error CS0664 : Literal of type double cannot be implicitly converted to type 'float'; use an 'F' suffix to create a literal of this type
```

**Comment by thomhurst** [comment]
> whats the equivalent in TUnit?

```chsarp
[MethodDataSource(nameof(FixtureArgs), UnfoldTuple = true)]
public class TestFixtureSourceAndTestCaseUsage(string arg1, int arg2)
{
    [Test]
    [Arguments("FromTestCase2")]
    public Task Test(string arg3) =>
        Verify(
            new
            {
                arg1,
                arg2,
                arg3
            });

    public static (string, int) FixtureArgs() => ("Value", 2);
}
```

**Comment by thomhurst** [comment]
> this
> 
> ```
> 
>     [Test]
>     [Arguments((float)1.1)]
>     public Task Float(float arg) =>
>         Verify(arg);
> ```
> 
> results in
> 
> ```
> 33>Float_ParametersSample_49363d0d3fb0455cb46335bd8b7587a2.Generated.cs(18,39): Error CS0664 : Literal of type double cannot be implicitly converted to type 'float'; use an 'F' suffix to create a literal of this type
> ```
> 
> if i use
> 
> ```
>     [Test]
>     [Arguments(1.1F)]
>     public Task Float(float arg) =>
>         Verify(arg);
> ```
> 
> i get
> 
> ```
> 33>Float_ParametersSample_096a4f03ccd54ee285b352b9f622e9ee.Generated.cs(18,39): Error CS0664 : Literal of type double cannot be implicitly converted to type 'float'; use an 'F' suffix to create a literal of this type
> ```

Ah nice spot - My bad! Source generator wasn't appending the relevant suffix.

Can you try with version `[0.1.738](https://www.nuget.org/packages/TUnit/0.1.738)`?

**Comment by thomhurst** [comment]
Thanks @SimonCropp ! ❤️

**Comment by SimonCropp** [comment]
@thomhurst no worries. and i good work on TUnit. it was the easiest test framework to integrate with so far
