### ISSUE TITLE
.NET 9 Tests RC 1 seems to handle empty collections differently in my project

### ISSUE THREAD

**Issue by devlead** [VerifyTests/Verify#1301]
#### Describe the bug

While adding `net9.0` tfm to a project a couple of my tests started to fail where snapshot

```json
﻿{
  Item1: Accepted,
  Item2: []
}
```
Example:
https://github.com/devlead/Blobify/blob/3298d272164892bedd43f45af7f581fe83f5fb0f/src/Blobify.Tests/Unit/Services/Storage/TokenServiceTests.PutAsync.verified.txt#L1-L4

Became:
```json
﻿{
  Item1: Accepted
}
```

Changing code from
```csharp
// Then
await Verify(result);
```
to
```csharp
// Then
await Verify(result)
    .DontIgnoreEmptyCollections();
```

Sorted the issue with the tests that started failing, 

#### Minimal Repro

Haven't created a minimal repro yet, but  at least locally on my machine if I remove this line, the test will start to consistently assert differently on `net9.0` than `net8.0`
```csharp
 .DontIgnoreEmptyCollections();
```
https://github.com/devlead/Blobify/blob/2a4175240d932c3a4368a9f76b9e5994a65bfe5c/src/Blobify.Tests/Unit/Services/Storage/TokenServiceTests.cs#L52

**Comment by SimonCropp** [comment]
so omitting the empty collection is the correct behavior.

 it was a bug that in earlier versions of .net it was included. that will be fixed in the next release of verify

i submitted a PR to Blobify to include empty collections by default https://github.com/devlead/Blobify/pull/4

**Comment by devlead** [comment]
Thanks for the PRs, for be it would've been fine if they were omitting by default, what threw me was that it behaved differently in same test project based on TFM.
