### ISSUE TITLE
Provide API to help getting the verification file in tests

### ISSUE THREAD

**Issue by vzam** [VerifyTests/Verify#1341]
#### Is the feature request related to a problem

I have an API which I am testing and I need to ensure that the data that I send is the same data that I receive. Sometimes it is not practical to have the data embedded in the C# code, instead I want to have it as a separate file. It would be nice if I could use the file which is used for verification before doing the `Verify`. Currently there is no easy way to get the path to the file which is used by the Verifier. 

#### Describe the solution

Provide an API to get the file path of the file used for verification, e.g. `string Verifier.GetVerificationFilePath()` or even to read the entire file `string Verifier.GetVerificationFileJson()`, `byte[] Verifier.GetVerificationFileBytes()` etc.

#### Describe alternatives considered

The file path can be hardcoded but it would have to be changed in the test whenever the verifier settings or file location change.

#### Additional context

\-

**Comment by SimonCropp** [comment]
can you give an example test that uses this theoretical api

**Comment by SimonCropp** [comment]
bunp
