### ISSUE TITLE
Support alternate DisableClipboard environment variable to easily support Linux

### ISSUE THREAD

**Issue by Zshazz** [VerifyTests/Verify#206]
#### Is the feature request related to a problem

When we run builds on Azure Pipelines, we get the following error:

```
Could not execute process. Command line: bash -c "cat /tmp/tmpdDjFqQ.tmp | xclip -i -selection clipboard". Output: Error: bash: xclip: command not found cat: write error: Broken pipe 
```

The solution described [at disabling the clipboard for a machine](https://github.com/VerifyTests/Verify/blob/master/docs/clipboard.md#for-a-machine) doesn't work when the build machine is running Linux, because the environment variables cannot contain a `.` character.

#### Describe the solution

I propose allowing the `Verify.DisableClipboard` environment variable to continue working as-is, but additionally, support `VERIFY_DISABLECLIPBOARD` to support the required naming restrictions (as well as the normal convention) on Linux machines. Note that if you use `Verify.DisableClipboard` on Azure Pipelines and it _automatically corrects_ to `VERIFY_DISABLECLIPBOARD`, so it gives a "pit of success" for that use-case with regards to the current documentation. None-the-less, it might be nice to document the alternative for Linux users.

#### Describe alternatives considered

In our tests, we are considering using the following in a static constructor on our test module to get this working for us immediately:
```
if (!string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("VERIFY_DISABLECLIPBOARD"))
{
    VerifierSettings.DisableClipboard();
}
```

Alternately, it looks like you can also do `env 'Verify.DisableClipboard=true' dotnet test $(Build.Repository.LocalPath)/src/App.sln --logger trx --results-directory $(Agent.TempDirectory)`, but it requires using a script instead of the built-in dotnet test action.

We are happy with these solutions, but wanted to make this request to make this officially supported or documented so that others have an easy solution as well.

Thank you,
Chris

**Comment by SimonCropp** [comment]
a couple of things

1. Clipboard should not run on CI, and should not need to be disabled.  
https://github.com/VerifyTests/DiffEngine#buildserverdetector 
this is handled by https://github.com/VerifyTests/DiffEngine/blob/master/src/DiffEngine/BuildServerDetector.cs 
as i understand it Azure Pipelines should be handled by https://github.com/VerifyTests/DiffEngine/blob/master/src/DiffEngine/BuildServerDetector.cs#L40
However there was a bug in verify that was not properly detecting this for one of the clipboard scenarios. this is fixed here

so you should be able to update to 6.14.0 of verify and not need any additional env variables on Azure Pipelines

2. i did not know about the env naming restrictions. i moved over to using `_` as a default with `.` fallback.  https://github.com/VerifyTests/Verify/issues/207

will close this for now. please let me know if u have any issues.

**Comment by SimonCropp** [comment]
@Zshazz BTW where did you hear about Verify? Also are you running on windows? if so you might want to try my diffengine tray tool as an alternative to the clipboard https://github.com/VerifyTests/DiffEngine/blob/master/docs/tray.md

**Comment by Zshazz** [comment]
I had found `ApprovalTests.Net` while looking for testing tools like that (manually approving what results you get from tests). I believe I had seen your contributions there and happened to see this alternative as a project you worked on. I went through and found as many options as I could and just tried a few out and found I preferred Verify.

With ApprovalTests, I felt I'd need to write a helper method that Json serializes most classes before calling it. I see value in its opinion that you should write readable `ToString` methods for it, but in most cases, those `ToString` methods aren't going to be any better than a bunch of key-value pairs. It also felt a little weird to write `ToString` methods on classes we're checking the output on only because of a tool our team happened to use for unit/integration tests. Plus I saw the `Verify.EntityFramework` package and I know we occasionally have a need for specifically checking out that our queries are actually getting built well, so it saves us time getting that working.

So Verify just seemed like a more straight-forward one to use.

I'll have to take a look at the tray tool. It looks pretty handy.

Thanks again,
Chris

**Comment by Zshazz** [comment]
> will close this for now. please let me know if u have any issues.

Hey @SimonCropp,

I went ahead and tried this out this morning and it still wasn't working, but with the informative reply you gave, I was able to figure out what's causing the build server detector from working here:

1. On Linux, Environment Variables are case-sensitive,
2. As noted in the BuildServerDetector, [`Agent.Id` is an Azure Pipelines agent variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables)
3. and Azure Pipelines Agents use `AGENT_ID`, because [the name is upper-cased, and the `.` is replaced with the `_`](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#access-variables-through-the-environment).

I confirmed this by running a build and saw that `Environment.GetEnvironmentVariable("Agent_Id") == null` and `Environment.GetEnvironmentVariable("AGENT_ID") == "9"` (on our agent, of course). From the best that I can tell, if [the Azure pipelines detection was uppercased](https://github.com/VerifyTests/DiffEngine/blob/master/src/DiffEngine/BuildServerDetector.cs#L40), then it should work.

When I added the following to my test:
```
static MyTests()
{
    if (Environment.GetEnvironmentVariable("AGENT_ID") != null)
    {
        BuildServerDetector.Detected = true;
        return;
    }
}
```

It does work for me.

Thank you,
Chris

**Comment by SimonCropp** [comment]
BTW if you are using Verify.EF, have u tried the recoding feature https://github.com/VerifyTests/Verify.EntityFramework#recording ?
