### ISSUE TITLE
Allow option for quoting strings

### ISSUE THREAD

**Issue by viceroypenguin** [VerifyTests/Verify#253]
In PR #244, quotes are removed from strings going forward. This means the output JSON are no longer valid JSON. Would it be possible to have an option to return to the old behavior where the strings were quoted?

**Comment by SimonCropp** [comment]
i would consider this. but first i would like to understand the "why". is there some tooling that u r using for diffs that handles json better? also note that before the mentioned change the output was not valid json. eg Single quotes were used (json specifies double quotes), names are not quoted, scrubbed guids+datetimes are not quoted.

**Comment by SimonCropp** [comment]
and the “not json” has always been documented https://github.com/VerifyTests/Verify/blob/master/docs/serializer-settings.md#not-valid-json

**Comment by viceroypenguin** [comment]
Fair. 

First, I think mostly it was the shock of having all of the output files require changing, simply because I upgraded. Didn't help that I did an upgrade of all of the libraries, so I was trying to verify nothing had changed by upgrading, and had to separate out the Verify upgrade from the others. Was there a release note on a) when the change and b) why the change?

Second, I do occasionally open the files for manual review. Even though they weren't technically JSON, they were close enough to be parsed by most generous parsers (including text editors). These now aren't able to be parsed by any parser or editor, so I have to turn off syntax highlighting and edit them as plain text files. 

Not a big deal if you want to close this request; just that the older version was more compatible with my expectations. https://xkcd.com/1172/

**Comment by viceroypenguin** [comment]
NB: the serializer settings documentation file you referenced has not been updated with the recent changes in the output file (not using quotes on strings, etc.).

**Comment by SimonCropp** [comment]
> the serializer settings documentation file you referenced has not been updated with the recent changes in the output file (not using quotes on strings

updated. thanks

> First, I think mostly it was the shock of having all of the output files require changing, simply because I upgraded

Agreed. i think i need to bump a major when i change the output in any way. al though i hope not to have to do that much

> Was there a release note on a) when the change and b) why the change?

The change was for readability. sorry i didnt get around to release notes for that change

> Second, I do occasionally open the files for manual review. Even though they weren't technically JSON, they were close enough to be parsed by most generous parsers (including text editors). These now aren't able to be parsed by any parser or editor, so I have to turn off syntax highlighting and edit them as plain text files.

Ok i will re add a "pure json" option

**Comment by viceroypenguin** [comment]
@SimonCropp Thanks!

**Comment by viceroypenguin** [comment]
Thank you again! Looking forward to the update.

**Comment by SimonCropp** [comment]
it is deployed now if u want to play with it. here are some docs https://github.com/VerifyTests/Verify/blob/master/docs/serializer-settings.md#usestrictjson

**Comment by SimonCropp** [comment]
@viceroypenguin also if u dont like the clipboard approach, you can disable it for your machine using an env setting https://github.com/VerifyTests/Verify/blob/master/docs/clipboard.md#for-a-machine . And as an alternative to approval via the clipboard, you could also use DiffEngineTray https://github.com/VerifyTests/DiffEngine/blob/master/docs/tray.md

**Comment by viceroypenguin** [comment]
Works as expected, see any of the json files [here](https://github.com/viceroypenguin/Going.Plaid.NET/commit/8b7534046a2dda7f511f1fa7c96ed673a550a4ae).
