### ISSUE TITLE
Store *.verified.* files in another directory

### ISSUE THREAD

**Issue by patriksvensson** [VerifyTests/Verify#261]
#### Is the feature request related to a problem

I would like to have my `.verified.*` files in another directory than my tests to avoid clutter.
This would make it much nicer to work with when using an editor that doesn't support file grouping, such as VSCode.

#### Describe the solution

Preferably I would define a relative path in a configuration file next to my csproj file.

Perhaps having different file handling strategies as well. So instead of naming my files `FooTests.Bar.verified.txt` and `BarTests.Baz.verified.txt`, I could in said configuration file above mention that I want to use a directory-based approach instead.

* /Verified
  * /FooTests
    * Bar.verified.txt
  * /BarTests
    * Baz.verified.txt

**Comment by SimonCropp** [comment]
already supported. https://github.com/spectresystems/spectre.console/pull/141  i just did a basic example. u can expand on it for your own convention

**Comment by SimonCropp** [comment]
the docs are in a weird place. https://github.com/VerifyTests/Verify/blob/master/docs/build-server.md#custom-test-directory i will fix that later

**Comment by SimonCropp** [comment]
@patriksvensson glad that PR worked for you. Also I updated the docs https://github.com/VerifyTests/Verify/blob/master/docs/naming.md#derivetestdirectory
