### ISSUE TITLE
Long filenames and MAX_PATH

### ISSUE THREAD

**Issue by patriksvensson** [VerifyTests/Verify#282]
#### Is the feature request related to a problem

Due to how I arrange my tests, filenames become very long, which breaks Visual Studio (fails silently when trying to view the file) and other tools like nCrunch. The problem is really related to `MAX_PATH` and not Verify per se. 

#### Describe the solution

Would like a way to manually name expectation files with an attribute or similar.

```csharp
[Fact]
[VerifyName("UnknownCommand.txt")]
public Task Should_Return_Correct_Text_When_Command_Is_Unknown()
{
    // Omitted
}
```

#### Describe alternatives considered

A hook into Verify where I can transform the name as I want to, just like I can with the root directory using `DeriveTestDirectory`.
Perhaps a `DeriveVerifyName` or similar? 

#### Additional context

Example of filename that breaks VS and nCrunch: 
`CommandAppTests.Parsing.UnknownCommand.Should_Return_Correct_Text_With_Suggestion_When_Root_Command_Followed_By_Argument_Is_Unknown_And_Distance_Is_Small.verified.txt`

**Comment by SimonCropp** [comment]
would this work for you https://github.com/VerifyTests/Verify/blob/master/docs/naming.md#derivetestdirectory  ?

**Comment by patriksvensson** [comment]
@SimonCropp No, I'm already using that (unless I'm misunderstanding something). The problem is the generated name which gets too long.

**Comment by SimonCropp** [comment]
i think i get it. let me do a PR as a possible solution, and i will get u to review it

**Comment by patriksvensson** [comment]
@SimonCropp Awesome. No rush or anything. I've disabled nCrunch for now. Tell me if there's anything I can do.

**Comment by SimonCropp** [comment]
hows this https://github.com/VerifyTests/Verify/blob/UseName/docs/naming.md#usename  ?

**Comment by patriksvensson** [comment]
@SimonCropp This would certainly unblock me!

**Comment by patriksvensson** [comment]
@SimonCropp I must ask, would it be possible to be able to specify the subdirectory in the same manner? That would make things very flexible.

**Comment by SimonCropp** [comment]
>would it be possible to be able to specify the subdirectory in the same manner

it would. but that is the point of https://github.com/VerifyTests/Verify/blob/master/docs/naming.md#derivetestdirectory. i had assume, possibly incorrectly, that people would only want to configure that in the static context. is that not correct?

**Comment by patriksvensson** [comment]
@SimonCropp I would say that you would want to configure the root directory in the static context, but be able to control more granularly where the expectation ends up.

```csharp
await Verifier.Verify("value")
    .UseDirectory("My/Directory"); // Relative path
    .UseName("TheCustomNameFluent");
```

Preferably, I would be able to specify some kind of strategy on the static context how to "calculate" the directory and filename (relative to the root directory).
For example:

```csharp
// Signature is something like Func<MethodInfo, (string? Directory, string Filename)>
VerifierSettings.DeriveTestInfo(
    (methodInfo) =>
    {
        strinf dir = .. // Get the relative directory path from the method info. Optional
        string file = .. // Get the filename from the method info
        return (dir, file)
    });
```

This would of course be some kind of "I know what I'm doing"-mode, but would open up to configure Verify exactly as you want it.

Hope I make sense

**Comment by SimonCropp** [comment]
i deployed a beta with these changes

 * https://github.com/VerifyTests/Verify/blob/master/docs/naming.md#derivepathinfo
 * https://github.com/VerifyTests/Verify/blob/master/docs/naming.md#directory
 * https://github.com/VerifyTests/Verify/blob/master/docs/naming.md#testclassname
 * https://github.com/VerifyTests/Verify/blob/master/docs/naming.md#testmethodname

can u have a look and let me know what u think?

**Comment by patriksvensson** [comment]
@SimonCropp This looks exactly what I need 🙏. I will take a look as soon as I get to a computer.

**Comment by patriksvensson** [comment]
@SimonCropp Seems to work OK! Have a pretty complex path deriver now that seems to work as it should! Thanks a lot for this!

(Examples below are just using example paths and names to demonstrate)

![image](https://user-images.githubusercontent.com/357872/103537516-d7f1b380-4e94-11eb-97db-7cd32059c27e.png)

![image](https://user-images.githubusercontent.com/357872/103537696-2b640180-4e95-11eb-9896-43060c86c2f0.png)

And the code:

```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Threading;
using VerifyTests;

namespace Spectre.Console.Tests
{
    public static class VerifyConfiguration
    {
        private static readonly HashSet<string> _encountered = new HashSet<string>(StringComparer.Ordinal);
        private static readonly SemaphoreSlim _lock = new SemaphoreSlim(1, 1);

        [ModuleInitializer]
        public static void Init()
        {
            VerifierSettings.DerivePathInfo((_, project, type, method) =>
            {
                var root = Path.Combine(project, "Expectations");

                var attribute = method.GetCustomAttribute<ExpectationNameAttribute>();
                if (attribute == null)
                {
                    return GetFallbackPathInfo(root, type, method);
                }

                return GetPathInfo(root, type, method);
            });
        }

        private static PathInfo GetFallbackPathInfo(string root, Type type, MethodInfo method)
        {
            return new PathInfo(
                directory: root,
                typeName: GetTypeName(type),
                methodName: method.Name);
        }

        private static PathInfo GetPathInfo(string root, Type type, MethodInfo method)
        {
            // Get the method name
            var nameAttribute = method.GetCustomAttribute<ExpectationNameAttribute>();
            var methodName = string.IsNullOrWhiteSpace(nameAttribute.Name) ? method.Name : nameAttribute.Name;

            var pathStack = new List<string>();
            var current = type;
            while (current != null)
            {
                var pathAttribute = current.GetCustomAttribute<ExpectationPathAttribute>();
                if (pathAttribute != null)
                {
                    if (string.IsNullOrWhiteSpace(pathAttribute.Name))
                    {
                        pathStack.Insert(0, current.Name);
                    }
                    else
                    {
                        pathStack.Insert(0, pathAttribute.Name);
                    }
                }

                current = current.DeclaringType;
            }

            if (pathStack.Count == 0)
            {
                // No expectation paths?
                // Use the full type name.
                pathStack.AddRange(GetTypeName(type).Split('.'));
            }

            root = Path.Combine(root, string.Join("/", pathStack));

            var full = $"{root}/{methodName}/Test";
            EnsureUnique(full);

            return new PathInfo(
                directory: root,
                typeName: methodName,
                methodName: "Test");
        }

        private static string GetTypeName(Type type)
        {
            var typeName = type.FullName;
            var index = type.FullName.LastIndexOf('.');
            if (index != -1)
            {
                typeName = type.FullName.Substring(index + 1);
            }

            return typeName.Replace('+', '.');
        }

        private static void EnsureUnique(string full)
        {
            try
            {
                _lock.Wait();

                if (_encountered.Contains(full))
                {
                    throw new InvalidOperationException($"Found duplicate expectations: {full}");
                }

                _encountered.Add(full);
            }
            finally
            {
                _lock.Release();
            }
        }
    }
}
```
