### ISSUE TITLE
Make it possible to disable copying of diff command in certain situations

### ISSUE THREAD

**Issue by patriksvensson** [VerifyTests/Verify#296]
#### Is the feature request related to a problem

Yes. I use a tool called nCrunch that continuously runs my tests in the background. This means that sometimes when a test is failing and I try to paste something I copied, it will instead paste the  diff command, such as `cmd /c move /Y "C:\Code\Sample\Sample.Test.received.txt" "C:\Code\Sample\Sample.Test.verified.txt"`.

#### Describe the solution

nCrunch sets a environment variable `NCrunch` to `1` when it is running a test. Would be nice if I in my VerifyConfiguration, where I configure Verify, could disable copying.

https://www.ncrunch.net/documentation/troubleshooting_ncrunch-specific-overrides

#### Describe alternatives considered

No other alternatives suggested.

**Comment by SimonCropp** [comment]
can u try 10.0.0-beta.5

**Comment by SimonCropp** [comment]
just an fyi.

u can disable the clipboard globally https://github.com/VerifyTests/Verify/blob/master/docs/clipboard.md#for-a-machine 

and if u use diffenginetray it will override the clipboard behavior https://github.com/VerifyTests/DiffEngine/blob/master/docs/tray.md

**Comment by patriksvensson** [comment]
@SimonCropp Ah, sorry. Not sure how I missed that. Thanks!
Is this new in 10.0.0-beta-5?

**Comment by SimonCropp** [comment]
the autodetection of ncrunch i just fixed and released https://github.com/VerifyTests/Verify/commit/dedbc6321fe3f06ba3309d8865f7d3c65a541588

 disable the clipboard globally has been there since v2 (i think)

diffenginetray as been around since august 2020

**Comment by patriksvensson** [comment]
@SimonCropp Ah, DiffEngineTray I'm using all the time (it's part of my startup). Was meaning disabling the clipboard.

Thanks!

**Comment by SimonCropp** [comment]
if DiffEngineTray  is running the clipboard should never be touched. if it is we have another bug

**Comment by patriksvensson** [comment]
@SimonCropp No, when I encountered the bug, the diff engine tray was not running, and I haven't noticed this before, so I think there is no bug.
