### ISSUE TITLE
Extension-aware scrubbers in VerifySettings instance are ignored

### ISSUE THREAD

**Issue by diegofrata** [VerifyTests/Verify#315]
#### Describe the bug

Extension-aware scrubbers added to an instance of VerifySettings are ignored during the Verify call. It should work since the method overload exists. From inspecting the code, it seem the scrubbers are registered but simply not used.

#### Minimal Repro

The received document should contain "b", not "a".

```c#
[Test]
public async Task Test()
{
    await File.WriteAllTextAsync("test.html", "a");
    var settings = new VerifySettings();
    settings.AddScrubber("html", builder => builder.Replace("a", "b"));
    await Verifier.VerifyFile("test.html", settings);
}
```

**Comment by SimonCropp** [comment]
@diegofrata thanks for the repro. i just pushed a fix to nuget.
