### ISSUE TITLE
Typeo in method description

### ISSUE THREAD

**Issue by Bencargs** [VerifyTests/Verify#327]
There's a typeo on this line - https://github.com/VerifyTests/Verify/blob/837ebedcb32b1b21118d22ecb40b056650775b0f/src/Verify/SettingsTask.cs#L227

I think it should read: "Automatically accept the results of the current tes`t`.

**Comment by SimonCropp** [comment]
@Bencargs thanks. this is fixed now.

as an aside what are you using verify for? and are you using diffenginetray https://github.com/VerifyTests/DiffEngine/blob/master/docs/tray.md
