### ISSUE TITLE
Suggestions for F# users

### ISSUE THREAD

**Issue by kurtschelfthout** [VerifyTests/Verify#336]
#### Is the feature request related to a problem

Verify doesn't work out of the box for F# users.

Also I'll make a few suggestions that are largely specific to F# (arguably some of those are not quirks of this library but rather of F#, but I mention them because they cause some friction.)

#### Describe the solution

This file contains a number of workarounds: https://github.com/fscheck/FsCheck/blob/shrinking/tests/FsCheck.Test/VerifyGen.fs

The main issue I encountered at first was that it refused to work at all because I needed to add `AssemblyMetadataAttribute` to my assembly manually. From browsing the code, I believe this is because there is a build step here which is conditional on VB and C# projects, and so F# falls through the cracks.

The second issue is that `Verifier.Verify<'T>.GetAwaiter` returns an awaitable, not a `Task`, while xunit expects a `Task` back to run the tests. This is surprisingly annoying to convert in F#: https://github.com/fscheck/FsCheck/blob/shrinking/tests/FsCheck.Test/VerifyGen.fs#L26

My third and very minor suggestion is to add an option to include properties that have `null` values in the output - they are as far as I can see currently removed unconditionally. This is slightly surprising in F# because `None` and `()` are real values, but are represented as `null` under the hood. So if you have a record type like `{ Foo: option<int> }` and its value is `None`, Foo simply does not appear in the output, and this was surprising to me.

#### Describe alternatives considered

N/A

#### Additional context

None

**Comment by SimonCropp** [comment]
would you have time to submit a pr with a new fs project that contains a test and your work arounds. then i will work on removing those workarounds

**Comment by kurtschelfthout** [comment]
Should not be a problem, I'll send you what I have

**Comment by kurtschelfthout** [comment]
Didn't quite know where you wanted it so just attached it as zip: [VerifyFSharp.zip](https://github.com/VerifyTests/Verify/files/6329561/VerifyFSharp.zip)

**Comment by SimonCropp** [comment]
> without AssemblyMetadataAttribute Verify refuses to work.

fixed in https://github.com/VerifyTests/Verify/pull/337/files

> it automatically replaces anything that looks like the value with {ProjectDirectory}, which we also never want.

fixed in https://github.com/VerifyTests/Verify/pull/338

**Comment by SimonCropp** [comment]
ok those two changes are deployed. i think between them and [some fsharp docs](https://github.com/VerifyTests/Verify/blob/master/docs/fsharp.md) all your concerns are addressed?

**Comment by kurtschelfthout** [comment]
Agreed, I have yet to give it a try in FsCheck but all looks good!

**Comment by SimonCropp** [comment]
also note that i moved NullValueHandling  to the module startup and changed it to use the static VerifierSettings

https://github.com/VerifyTests/Verify/blob/master/docs/fsharp.md#full-tests

**Comment by SimonCropp** [comment]
ok. since everything is covered, i will close this one
