### ISSUE TITLE
sync on snapshot/approvals/verification testing

### ISSUE THREAD

**Issue by SimonCropp** [VerifyTests/Verify#35]
@theramis @isidore @michaelstaib @nscheibe @claremacrae

hey peoples. Given our project overlaps i though it might be helpful for us to be aware of each other and have a possible sync so we can share ideas, lessons learnt, code etc.

 * [ApprovalTests](https://github.com/approvals/ApprovalTests.Net)
 * [Snapshooter](https://github.com/SwissLife-OSS/Snapshooter)
 * [Snapper](https://github.com/theramis/Snapper)
 * [Verify](https://github.com/SimonCropp/Verify)

Some discussion points i can think of

 * the trade offs between stack trace walking and using `[CallerFilePath]`
 * how [diff tools work](https://github.com/SimonCropp/Verify/blob/master/docs/diff-tool.md), which i think  Snapper and Snapshooter dont have?
 * verification of files/binary data. eg [image](https://github.com/SimonCropp/Verify/blob/master/docs/binary.md) or [office document](https://github.com/SimonCropp/Verify.Aspose) verification 
 * the possibility of sharing code. i have already created a stand alone nuget for [EmptyFiles](https://github.com/SimonCropp/EmptyFiles) (which makes comparison of files easier). i was also considering splitting out the whole diff tool detection+management into a nuget.

So would people like to get on a call? or perhaps discuss things here? or some other medium?

Is there anyone else I should have brought in? or tools i should have listed?

**Comment by claremacrae** [comment]
Sounds good. Count me in!

I’m not aware of any other tools

**Comment by gkinsman** [comment]
Assent is the one I usually spring for: https://github.com/droyad/Assent. Also FluentAssertions has approval test support.

**Comment by michaelstaib** [comment]
Sure I lets talk ;)

**Comment by michaelstaib** [comment]
@SimonCropp do you want to setup a meeting?

**Comment by SimonCropp** [comment]
sure. what timezones are people in?

**Comment by SimonCropp** [comment]
@gkinsman thanks. hey @droyad does this interest you

**Comment by droyad** [comment]
Yeh sure. I'm in AEST and generally available 2100 -> 12:00 GMT. Not too fussed if I miss it though.

**Comment by claremacrae** [comment]
I’m in UK time.

**Comment by theramis** [comment]
Yea sure, happy to have a chat. I'm in NZ so timezone is currently GMT+13. 
Generally free 0500 -> 1000 GMT most days. Weekends I can make time whenever 😄

**Comment by claremacrae** [comment]
> I’m in UK time.

Generally free 0900 -> 2200 GMT most days.
Willing to be available 0700 -> 2300 if necessary!

**Comment by michaelstaib** [comment]
We are Zurich time :)

**Comment by SimonCropp** [comment]
sorry for the horrible delay on this. how about monday (29th) 7am AEST? and then another 8pm AEST?

**Comment by claremacrae** [comment]
Thanks Simon.

Whilst checking time zones, here are links to help others, for your own time zones...

> how about monday (29th) 7am AEST?

http://www.timebie.com/std/aest.php?q=7

So for me in the UK that is Sunday @ 10:00 PM (22:00)

>  and then another 8pm AEST?

http://www.timebie.com/std/aest.php?q=20

So for me that is Monday @ 11:00 AM (11:00)

Those are both fine for me and in my diary...

It does mean it would be helpful for others to reply in the next few hours, as the first slot is around 10 hours away...

**Comment by theramis** [comment]
Sorry for the late reply. 

I can make both times really. Would prefer 7 am AEST though. 
Just need a heads up a day or two before 😄
