### ISSUE TITLE
Pass a scenario instead of all parameters when using parameterised tests

### ISSUE THREAD

**Issue by KenBonny** [VerifyTests/Verify#353]
Hello, I recently discovered this library and I'm really liking it. I'm moving from a _rivaling_ package to this one as it is a lot more user friendly and predictable. There is one thing I have a "problem" with. Maybe there is a solution to this and I haven't found it yet. My apologies if that is the case.

#### Is the feature request related to a problem

I have a number of files that contain the correct serialisation already and for most it's just getting the naming scheme right. There is a problem when I get to **[Theory]** tests in xUnit (and I think it will be the same for NUnit as well). There is support for parameterised tests, but I have to supply all parameters to get a good file name.

Because some scenarios require quite a bit of parameters to get right, every first parameter is a scenario name so I can easily identify which case this is testing. For example: `GenerateCorrectInvoice(string scenario = "with-multiple-customers", DateTime invoiceForDate = "1/1/2021", /* more params here */)`. This is some pseudo code so you get the idea what I'm doing. The resulting filename would be something like `InvoiceTests.GenerateCorrectInvoice_scenario=with-multiple-customers_invoiceForDate=1_1_2021_....txt`.

This leads to really long and sometimes confusing names. It would be a lot simpler if I could specify the scenario, which I know will be unique for the class and test method.

#### Describe the solution

Is it possible to have a method like `UseScenario(string scenario)` where I can supply the scenario as a unique constraint. An overload of `UseFileName`/`UseTypeName`/`UseMethodName` where I get access to the `Type` and `MethodInfo` would also be good as I can then format the name of the file to look for myself.

It would also need to prevent the `Verify` method to throw an `System.Exception: Method `InvoiceTests.GenerateCorrectInvoice` requires parameters, but none have been defined. Add UseParameters.` when the `Use...Name` overloads are specified.

#### Describe alternatives considered

I have looked into moving to the new file format, but I'm afraid that the Windows max file name length problem might pop up at a certain moment.

#### Additional context

/

**Comment by SimonCropp** [comment]
can you share a test with this proposed api and the file names that result?

also why would you need overloads with method info for the Use* methods? you are already in the context of the method so can use a constant or a nameof

**Comment by KenBonny** [comment]
I have the following test in the class `WhenIGenerateAnInvoice`:

```
[Theory]
[InlineData("single-workday")]
[InlineData("single-workday-minimum")]
[InlineData("half-workday")]
[InlineData("half-workday-minimum")]
[InlineData("one-and-half-workday")]
[InlineData("just-under-one-and-half-workday")]
[InlineData("just-under-two-workdays")]
[InlineData("complex-one-and-half-workday")]
[InlineData("single-workday-kenze")]
public async Task ForDayRate(string scenario)
{
    await _httpTest.LoadTimecampData(scenario);
    var invoices = await Generate(new DateTime(2019, 2, 1));
    invoices.Length.ShouldBe(1);
    invoices[0].ShouldBe(scenario);
}
```

The `LoadTimecampData` fetches a files named `scenario.json` which will be the http payload of a call to the Timecamp api (external service I use for tracking time). The `Generate` function will generate a number of invoices based on the Timecamp data, in these scenarios it will always be a single invoice (to check that I calculate simple scenarios correctly).

The `ShouldBe(scenario)` method is an extension method so it looks like the other Shouldly assertions.

```
public static Task ShouldBe(this Invoice? invoice, string scenario, [CallerMemberName] string? caller = null)
{
    invoice.ShouldNotBeNull();
    return Verifier.Verify(invoice).UseMethodName($"{caller}.{scenario}");
}
```

This is an attempt to get around the error that I need to specify `UseParameters`. This is a very simple scenario from a personal project, but I have tests where I have six or seven different parameters (but that is for work time code, not my personal project).

There is a file `WhenIGenerateAnInvoice.ForDayRate.single-workday.verified.txt` which contains the correct verified serialisation. The reason I want to use either the scenario or an overload of `Use*Name` function, is because I cannot access the name of the test method directly here. I now realise I could pass the filename to the extension method. The thing is, when you get to about 20 different test scenarios, I'd love to be able to rely on your build in name resolution and add a specific suffix that indicates where to find the correct file to verify against.

**Comment by SimonCropp** [comment]
can u try https://github.com/VerifyTests/Verify/blob/master/docs/parameterised.md#overriding-text-used-for-parameters

**Comment by KenBonny** [comment]
This is perfect. Thank you for adding this so quickly. You don't know how much work this has saved me. ❤️ 

Is there anything I can do in return?

**Comment by SimonCropp** [comment]
glad it met the requirements. no need for anything in return. out of curiosity, what is the tech stack of the current project?

**Comment by KenBonny** [comment]
The current project is a mix of old stuff that was written in dotnet 4.5 (now running on 4.8) where I first used a competitive nuget (approval something 😉 ) to get some golden masters. Me and the two other devs are rewriting, expanding and strangling the older parts with dotnet 5 projects/services. It's using a mishmash of asp.net mvc, nancy endpoints, console programs/windows services, nservicebus, msmq (now rabbitmq) to process a number of business cases in a simple webshop. Incredibly overengineered (sagas calling sagas calling endpoints that just need to be classes), foreach loops with repository.getbyid calls and a lot of `directory` + `filename` + `extension` nonsense instead of a decent `Path.Combine`.

Sorry to rant.

Your library has a lot better support for dates and ids (makes stuff so much easier), but I had to port a number of the existing approval/verify result files. I can change `Test.Method.scenario.txt` to `Test.Method_scenario.txt` quite easily, but not so much to `Test.Method_arg1=foo_arg2=bar...txt`. That's why I needed that, it saves me quite a bit of work.

I'm also using it on a personal project where I have an invoice console app that uses this to check that my invoices are generated correctly. Next step is to check the generated pdf with your library. Haven't gotten around to doing that yet. I just ported about 40 tests from the old approval thing to your wonderful VerifyTests.

**Comment by SimonCropp** [comment]
Ok here is some random info

 * I am also [on the approval tests team](https://github.com/approvals/ApprovalTests.Net/graphs/contributors)
 * I [worked for Particular on NSB](https://github.com/Particular/NServiceBus/graphs/contributors) for a few years and am still an [NSB Champ](https://particular.net/champions)
 * I maintain a few [NServiceBus Extensions](https://github.com/NServiceBusExtensions/)
 * Did u know there is a [Verify package for NServiceBus](https://github.com/NServiceBusExtensions/Verify.NServiceBus)
 * I fondly remember Nancy. We have since moved onto a SPA approach so dont have much use for server side parts. but if u decide to move off nancy, u should check out [Carter](https://github.com/CarterCommunity/Carter). it makes ASP.NET Core behave more like nancy.


on a side not i think you are missing an await in `invoices[0].ShouldBe(scenario);`?

**Comment by SimonCropp** [comment]
oh, and are you using https://github.com/VerifyTests/DiffEngine/blob/master/docs/tray.md  ?

**Comment by KenBonny** [comment]
Cool that you are an NSB Champ. I did not know there was a mock context, I always use a mock of the context interface. I'll need to look into that. At the moment I'm more interested in using approve/verify to check the differences in output of the handlers (updates to objects in the db, calls to other services, etc).

When I replace the Nancy stuff, I'm probably going for a few endpoints in the general site only accessible from admin areas/pages. Right now, that Nancy stuff is used to launch an order processing saga or upload a file so an import is started. I would probably look more into something like [ApiEndpoints](https://github.com/ardalis/ApiEndpoints). One file, one endpoint with some code behind it. Probably with injected services or maybe a repository so I can do simple reads right in the endpoint. KISS!

I am not using Tray. I'm using the default diffing attribute, VS Code shows the output nicely.

**Comment by SimonCropp** [comment]
the tray does not change what diff tool is used. but it makes it easier for you to accept or discard a change. it also helps u track pending approvals between different solutions

**Comment by KenBonny** [comment]
Hmmm, I'll give it a try. Thanks for the tip!
