### ISSUE TITLE
Renaming a test doesnt delete verified file

### ISSUE THREAD

**Issue by eugeneniemand** [VerifyTests/Verify#357]
#### Describe the bug
When renaming a test the old verified file does not get deleted. I'm using NUnit 3

#### Minimal Repro
Create a test, run it, save the verified file.
Rename test, run it, save the new verified file.
The first verified file still exists. I would expect it to be deleted

**Comment by SimonCropp** [comment]
unfortunately i know of no way to detect a rename. happy to hear suggestions

**Comment by rebelzach** [comment]
If we had an opt-in option like `.CleanUpUnmatchedVerificationFiles()` any files that don't match a list of patterns generated from a list of tests in the project (provided by the specific test library) could be deleted or moved to another directory. This would assume a few things, but these might be acceptable trade-offs to have unused files removed:
- They aren't rewriting the method name with `.UseMethodName()` though it could throw an exception in this case.
- The full list of tests is discoverable, this might slow down single test runs but possibly could be cached or run only when a few tests are run.

I can see how implementing this might be more complicated than its worth, but may also help to make adopting Verify more accessible.

**Comment by SimonCropp** [comment]
@rebelzach  Happy to consider a PullRequest

**Comment by DanAvni** [comment]
This might be easier to implement: after checking that the received and verified files are the same, Verify could modify the last modified date of the verified file to now. That way if I look on the folder of snapshots in some time and see files that have not updated I know they are probably obsolete (they could belong to a test that is not executed by default so I would not rush to auto-delete anything)
