### ISSUE TITLE
Default-integers ignored

### ISSUE THREAD

**Issue by figursagsmats** [VerifyTests/Verify#365]
First of all, thanks for an amazing project! Just getting started out, but really useful thus far! 
Now to the issue:  

**Integers with the default value of 0 gets ignored by default.** 

To demonstrate my confusion:
```
public class Foo
{
    public int FirstInteger { get; set; }
    public int SecondInteger { get ; set;}
}
```
Set the first integer to zero and the second to 1, and run Verify:
```
public async Task SomeMethodUnderTest()
{
    var foo = new Foo
    {
        FirstInteger = 0,
        SecondInteger = 1,
    };

    await Verify(foo);
}
```
This produces this output:
```
{
  SecondInteger: 1
}
```

**Comment by figursagsmats** [comment]
Silly me! I now realized that this is intended behavior since Json.Net is doing the serialization with 
`DefaultValueHandling = DefaultValueHandling.Ignore`
Which is stated in de docs!
Sorry for raising such a noobish issue

**Comment by SimonCropp** [comment]
no worries at all. and you can change that setting globally if u want

**Comment by figursagsmats** [comment]
Thanks! Realized that just now :)

**Comment by SimonCropp** [comment]
https://github.com/VerifyTests/Verify/blob/master/docs/serializer-settings.md#globally
