### ISSUE TITLE
Icon invisible when using Dark Theme in GitHub

### ISSUE THREAD

**Issue by chvollm** [VerifyTests/Verify#369]
#### Describe the bug

When I use Dark Theme in GitHub, the Icon "Helmet" is invisible because it seems to be black on transparent background. 

#### Minimal Repro

Switch to Dark Theme and open the project start page. 

#### Submit a PR that fixes the bug
Not sure how you want to fix this.

**Comment by SimonCropp** [comment]
IMO this should be fixed by the github team.
