### ISSUE TITLE
Incorrect order of P4Merge args

### ISSUE THREAD

**Issue by RussKie** [VerifyTests/Verify#372]
#### Preamble

Verify.Xunit v11.18.1

#### Describe the bug

P4Merge has the following args: `$BASE" "$LOCAL" "$REMOTE" "$MERGED"`, which appears to be reversed by the verifier. 

The verifier launched P4MErge with the following command:
`"C:\Program Files\Perforce\p4merge.exe" "...received.txt" "....verified.txt" "....verified.txt" "....received.txt"`, which leads to the following:
![image](https://user-images.githubusercontent.com/4403806/120622272-00acc200-c4a2-11eb-91ff-102b341784ff.png)

The command instead must be `"C:\Program Files\Perforce\p4merge.exe" "...received.txt" "....received.txt" "....verified.txt" "....verified.txt"`:
![image](https://user-images.githubusercontent.com/4403806/120622295-05717600-c4a2-11eb-9ae2-e6b988124d31.png)

#### Minimal Repro

```cs
        [Fact]
        public Task Test()
        {
            return Verifier.Verify("boo");
        }
```

#### Submit a PR that fixes the bug

If you point me to the source code I may be able to fix it.

**Comment by SimonCropp** [comment]
does this look better https://github.com/VerifyTests/DiffEngine/commit/9cf1d1b5c084b754b4d0bb3351184b859ff8d5ab  ?

**Comment by SimonCropp** [comment]
thanks for you help. this is now deployed (pending a nuget cache update)

**Comment by RussKie** [comment]
Thank you for the awesomely quick turnaround!

**Comment by SimonCropp** [comment]
no worries. as a aside, is the codebase you using this an OSS project?

**Comment by RussKie** [comment]
Yes, https://github.com/dotnet/winforms :)

**Comment by SimonCropp** [comment]
cool. what branch?

**Comment by RussKie** [comment]
https://github.com/dotnet/winforms/pull/5035
