### ISSUE TITLE
Classes implementing IEnumerable<T> does not have properties included in verification

### ISSUE THREAD

**Issue by patriksvensson** [VerifyTests/Verify#380]
As always, thanks for a wonderful library ❤️ 

#### Describe the bug

If a class that's being verified implements `IEnumerable<T>`, properties on the class are not reflected in the verification result.
Not sure if this is a bug, or by design, but would be great if there was a way to opt-out of this behavior.

I'm of course happy to provide a pull request for this if I know where to fix it (if you think it's something that should be fixed).                                                                                                            

#### Minimal Repro

I have the following classes:

```csharp
public sealed class Bar
{
    public int Num { get; set; }
}

public sealed class Foo : IEnumerable<Bar>
{
    private readonly List<Bar> _bars;

    public int Count { get; }
    public int Sum => _bars.Sum(x => x.Num);
    public IReadOnlyList<Bar> Bars => _bars;

    public Foo(IEnumerable<Bar> bars)
    {
        _bars = new List<Bar>(bars ?? Enumerable.Empty<Bar>());
    }

    public IEnumerator<Bar> GetEnumerator()
    {
        return _bars.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }
}
```

And I have the following test:

```csharp
[UsesVerify]
public sealed class SwiftMessageReaderTests
{
    [Fact]
    public Task Should_Return_Correct_Foo()
    {
        // Given, When
        var foo = new Foo(new[]
        {
            new Bar { Num = 1 },
            new Bar { Num = 2 },
            new Bar { Num = 4 },
        });

        // Then
        return Verifier.Verify(foo);
    }
}
```

I get the following verification:

```
[
  {
    "Num": 1
  },
  {
    "Num": 2
  },
  {
    "Num": 4
  }
]
```

As you see, the properties `Bars`, `Count` and `Sum` are missing.

**Comment by SimonCropp** [comment]
so should `public IReadOnlyList<Bar> Bars { get; }` be set?

And no that behavior is not intentional, but it seems to be the default behavior of newtonsoft?

**Comment by patriksvensson** [comment]
I missed setting the `Bars` property in the example. Updated the code.

Hmm, that makes sense. I think I saw something about setting up serialization in the documentation. Will take a look and report back if I can solve it that way.

**Comment by patriksvensson** [comment]
Found issue here: https://github.com/JamesNK/Newtonsoft.Json/issues/2121

**Comment by patriksvensson** [comment]
@SimonCropp Doesn't seem to be a way of overriding the `JsonSerializerSettings` in Verify. Am I correct in saying that?

**Comment by SimonCropp** [comment]
see modify defaults here https://github.com/VerifyTests/Verify/blob/master/docs/serializer-settings.md#default-settings

**Comment by patriksvensson** [comment]
Doh. Not sure how I missed that. Thanks!

**Comment by patriksvensson** [comment]
For anyone else encountering this, it can be solved by using a custom contract resolver.

```csharp
VerifierSettings.ModifySerialization(config =>
{
    config.AddExtraSettings(settings =>
    {
        settings.ContractResolver = new CustomContractResolver();
    });
});
```

Here is the resolver which will make sure that any `IEnumerable<MyType>` gets serialized as an object.

```csharp
public class CustomContractResolver : DefaultContractResolver
{
    public new static readonly ConverterContractResolver Instance = new ConverterContractResolver();

    protected override JsonContract CreateContract(Type objectType)
    {
        JsonContract contract = base.CreateContract(objectType);

        if (objectType == typeof(MyType))
        {
            return CreateObjectContract(objectType);
        }

        return contract;
    }
}
```

Disclaimer: Any calls such as `config.DontIgnoreEmptyCollections();` and `config.DontIgnoreFalse();` won't work anymore and will need to be implemented in the custom contract resolver.
