### ISSUE TITLE
Support UseTextForParameters even when test method does not have arguments.

### ISSUE THREAD

**Issue by matt-psaltis** [VerifyTests/Verify#383]
We have some more complex test scenarios where the test data is passed in via alternative means. I would love to be able to use 
UseTextForParameters in these circumstances but the fall through case is just an empty string. Could this also check the current parametersText string and return that instead if its been configured?

https://github.com/VerifyTests/Verify/blob/3085f7e69596ce503740685b2b9ad7e95101c090/src/Verify/Naming/FileNameBuilder.cs#L131

```
[Fact]
public async Task Test1() {

  ...
  await Verifier.Verify(obj)
                .UseTextForParameters("Sample");

}
```

The file naming would then include Sample even though the method has no arguments

**Comment by SimonCropp** [comment]
> We have some more complex test scenarios where the test data is passed in via alternative means

not sure i understand. even if test data is passed in via different means, there will still only be one `test.verified.txt`, so why do u need the sample suffixe?

on another note would this work for you

```
await Verify(obj)
    .UseMethodName("Test_Sample");
```

**Comment by matt-psaltis** [comment]
It uses custom xunit test discovery so the tests are run multiple times. I'll try usemethodname, use text for parameters just better fit from a naming perspective. Cheers.

**Comment by SimonCropp** [comment]
ahh. i had not considered that scenario. will fix and deploy in a few hours

**Comment by SimonCropp** [comment]
this is now deployed. sorry for the delay

**Comment by matt-psaltis** [comment]
Thank you very much @SimonCropp. Really appreciate it. No need to apologise, you're graciously donating your time to help! Thanks again!
