### ISSUE TITLE
Generated file names getting too long in Windows, causing problem loading test project in VS

### ISSUE THREAD

**Issue by MEmanuelsson** [VerifyTests/Verify#384]
I've come across an issue using xunit and Verify where the generated files' filenames are longer than what the operating system (Windows in this case) likes. I'm using a Theory and ClassData-attribute where I'm passing in a list of objects (based on an interface) and the filenames being generated are apparently based on the namespace of the interface in this list, resulting in very long filename, at least in our case. 

This results in the test-project not being loaded in our solution with the following error message: 

"Path: <path to txt-file> exceeds the OS max path limit. The fully qualified file name must be less than 260 characters."

This sounds very much like this issue in another project https://github.com/SimonCropp/XunitContext/issues/41. I guess a similar solution to that issue could work here also? Or is there some way that I've missed to change this in some kind of configuration?

**Comment by SimonCropp** [comment]
can u share a test that is causing this issue?

**Comment by MEmanuelsson** [comment]
I've attached a solution with a very small console application and xunit test project (hope this way of sharing example code works, if not let me know how you want it otherwise)
[VerifyFileName.zip](https://github.com/VerifyTests/Verify/files/6725913/VerifyFileName.zip)

This test results in .txt files that looks like this. 
![image](https://user-images.githubusercontent.com/9945377/123630715-1ea5e200-d816-11eb-9b68-1631fe3f9fe9.png)

I see that you're removing namespaces for the actual unit test but my problem comes from a list of objects with a somewhat long namespace. 

I understand that there is no way of safeguarding stupid naming by people (including me of course :-)) of things but perhaps there is a way to solve this one problem?

**Comment by MEmanuelsson** [comment]
Solved this (for now at least) by instead of passing a list of objects I passed like a DTO-class that contains a property which contains this list of objects. That way I get rid of the problem with a filename being created with namespaces etc. Perhaps that's the way to go?

**Comment by SimonCropp** [comment]
is this a better solution?

```
        [Theory]
        [ClassData(typeof(TestData))]
        public async Task Test_Which_Should_Produce_Extra_Long_Verify_FileNames(string query, List<Model> model)
        {
            VerifySettings settings = new();
            settings.UseTextForParameters(query);
            await Verifier.Verify(model, settings);
        }
```

**Comment by SimonCropp** [comment]
if u still want some of the content from the model in the file name u could use `VerifierSettings.NameForParameter` https://github.com/VerifyTests/Verify/blob/master/docs/parameterised.md#complex-memberdata

**Comment by MEmanuelsson** [comment]
That's perfect, I was not aware of those options so thanks for pointing them out to me!

**Comment by SimonCropp** [comment]
glad u got it sorted. btw u can also create your own naming convention  https://github.com/VerifyTests/Verify/blob/master/docs/naming.md#derivepathinfo
