### ISSUE TITLE
Exception when Verify.ProjectDirectory not defined

### ISSUE THREAD

**Issue by dparvin** [VerifyTests/Verify#388]
When I upgraded to Verify version 11.20.1, I started receiving the following error:
> System.Exception : Could not find a `AssemblyMetadataAttribute` named `Verify.ProjectDirectory`.

and it seems to come from: https://github.com/VerifyTests/Verify/blob/5f4837b62a3675439aad09d2161293d74f46283b/src/Verify/DerivePaths/AttributeReader.cs#L70

When I add:
`<Assembly: AssemblyMetadata("Verify.ProjectDirectory", "C:\Code\TheSolution\Project\")>`
to my AssemblyInfo.vb file, the error goes away.

### Call Stack

     AttributeReader.GetValue(Assembly assembly, String key) line 70
    <>c.<GetAssemblyInfo>b__11_0(Assembly _) line 77
    ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
    InnerVerifier.ctor(String sourceFile, Type type, VerifySettings settings, MethodInfo method) line 17
    Verifier.GetVerifier(VerifySettings settings, String sourceFile) line 14
    <<Verify>b__0>d.MoveNext() line 28
    --- End of stack trace from previous location where exception was thrown ---
    ExceptionDispatchInfo.Throw()
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    TaskAwaiter.ValidateEnd(Task task)
    VB$StateMachine_15_VerifyStatements.MoveNext() line 140
    --- End of stack trace from previous location where exception was thrown ---
    ExceptionDispatchInfo.Throw()

### Environment
I am using Visual Studio Enterprise 2019 version 16.10.3.  I am compiling my code in .NET Framework 4.8.

**Comment by SimonCropp** [comment]
can u share a full solution that repro's this? perhaps as a zip?

**Comment by dparvin** [comment]
I am working on that at the moment.  I will give a link to a github project.

**Comment by dparvin** [comment]
here is my project which reproduces the issue.

https://github.com/dparvin/VerifyErrorReproProject

**Comment by SimonCropp** [comment]
does the same problem exist when using the new sdk style of projects?

**Comment by dparvin** [comment]
After making another repository for a new set of projects, I found that in the sdk version of the projects seem to work correctly.

https://github.com/dparvin/VerifyErrorReproProjectCS

**Comment by SimonCropp** [comment]
so seems like this is a bug in VS/MSbuild with the old project system not supporting transitive dependencies. It is probably better to raise a GH issue with the microsoft project

**Comment by dparvin** [comment]
I have no idea why when I add a reference to the latest Verify to a new project, it will make the project work fine, but when I upgrade from an older version like version 1.15.1 to version 1.20.1, the tests get this error.  I do not know enough about how Verify works to be able to tell what is the cause.

**Comment by SimonCropp** [comment]
it is not a matter of "upgrading verify" or "adding it". it is (i suspect) the fact the project type is classic or sdk style. AFAIK the classic project style is abandonware.

**Comment by dparvin** [comment]
No idea.  I am supporting projects that are kind of old and they are using the older project type.  As I said, with the older project type, if I add the latest version of verify to it, it works fine, but when I upgrade it doesn't.  The project type does not change in the process.  I did try it with the sdk type and it works fine to upgrade it.  I know more about how to do my processes, but I have barely started working with Verify.  I don't know about the older project style being abandonware as any older software still uses it.  I have not used the sdk style for more than one project so far.

**Comment by SimonCropp** [comment]
So on some more research, it seems `buildtransitive` only doesnt work for references added via packages.config. so if you move over to PackageReference you should not need to move over to the full new sdk style. here is a PR that shows how to do this https://github.com/dparvin/VerifyErrorReproProject/pull/1

**Comment by SimonCropp** [comment]
and the "use PackageReference instead of `packages.config`" only needs to be in the test projects

**Comment by SimonCropp** [comment]
can u try 11.20.2. it should work for the packages.config as well

**Comment by dparvin** [comment]
Thank you.
