### ISSUE TITLE
Verify replaces paths in test content with symbols

### ISSUE THREAD

**Issue by daningalla** [VerifyTests/Verify#401]
#### Overview

When outputting diff on a unit test, Verifier replaces file paths in the content being scrutinized with tokens, e.g. `{ProjectDirectory}`. 

#### Description

I'm writing a logger implementation. In order to test the expected output of the logger when it writes an exception, I generate an exception and then log the error. The intent is to capture a baseline of what the logger should output, and compare of subsequent runs.

The exception to print is generated from code, but Verify removes file paths in the test string and replaces them with the following token: `{ProjectDirectory}` presumably because the paths are the same in the test project.

#### Expected behavior

Verifier does not transform the content being tested in any way.

#### Environment

- MacOS Big Sur 11.5.2
- JetBrains Rider 2021.1.5
- .NET 5.0.203
- Verifier.XUnit 11.27.0
- Verify support Rider Plugin 2021.2.0

#### Repro
 
Repro [gist](https://gist.github.com/daningalla/ed90e410017dfe776f5a482bec02cb1b)

**Comment by SimonCropp** [comment]
Yep that behavior is [documented here](https://github.com/VerifyTests/Verify/blob/main/docs/scrubbers.md#directory-scrubbers)

> Verifier does not transform the content being tested in any way.

if that was the behavior, then the snapshots would fail on different peoples machines (or the CI server) where the code could be checked out to a different directory.

**Comment by SimonCropp** [comment]
note it can be disabled


 * The current solution directory will be replaced with `{SolutionDirectory}`. To disable use `VerifierSettings.DontScrubSolutionDirectory()` in a module initializer.
 * The current project directory will be replaced with `{ProjectDirectory}`. To disable use `VerifierSettings.DontScrubProjectDirectory()` in a module initializer.

**Comment by daningalla** [comment]
Gotcha - thanks.

**Comment by SimonCropp** [comment]
so out of curiosity, are you going to leave that behavior as default, or disable it?

**Comment by daningalla** [comment]
I will leave it - this was merely a case of me not digging enough into the docs here to know the behavior was by design.

**Comment by SimonCropp** [comment]
👍
