### ISSUE TITLE
Verify Expecto Error

### ISSUE THREAD

**Issue by JordanMarr** [VerifyTests/Verify#405]
#### Describe the bug

I created a simple Verify Expecto sample test in a `net5.0` project which yields the following error:

```
  Message: 
    The type initializer for '<Module>' threw an exception.

  Stack Trace: 
    tests@26-33.Invoke(Unit unitVar)
    TaskBuilder.run[a](FSharpFunc`2 firstStep)

```

#### Minimal Repro

```F#
module VerifyTests

open VerifyExpecto

[<Tests>]
let tests = 
    testList "Verify Expecto Tests" [

        testTask "Simple Test" {
            let test = "test"
            do! Verifier.Verify("Simple Test", test)
        }

    ]
```

I also tried it without wrapping it in a `testList` to more closely match your test, but it still threw the same exception.

**Comment by SimonCropp** [comment]
I am having issue repo'ing this. can you share a full solution/project that reproduces this error.

**Comment by JordanMarr** [comment]
It just occurred to me what the issue is:
I am launching my Expecto tests via the VS2019 Test Explorer which is possible if you add the following packages:
- Microsoft.NET.Test.Sdk
- YoloDev.Expecto.TestSdk

Obviously a lot of people that use Expecto run solely from the console, but not all.

**Comment by JordanMarr** [comment]
Incoming repro project....

**Comment by JordanMarr** [comment]
Actually, as I sit here and fiddle with this .gitignore file, I realize that it will be easier and better for you to just add those two packages to your test project anyway, as you can then support both scenarios.

**Comment by SimonCropp** [comment]
can u try 12.0.0-beta.7

**Comment by JordanMarr** [comment]
I tried with different levels of nesting and it works great in all of them. 😀

**Comment by SimonCropp** [comment]
awesome. thanks for your help

**Comment by SimonCropp** [comment]
i deployed a stable nuget
