### ISSUE TITLE
Custom Verify Expecto Computation Expressions

### ISSUE THREAD

**Issue by JordanMarr** [VerifyTests/Verify#406]
#### Is the feature request related to a problem

I was playing around with this idea and trying to decide if I should proceed:

Having to type the name twice for the F# Verify Expecto could be removed.
Also, the need to manually call Verifier.Verify could be removed to make it even more streamlined.
This could be done by creating custom computation expressions.

#### Describe the solution

A set of custom computation expressions for Verify Expecto.

```F#
[<Tests>]
let tests = 
    testList "Sample Tests" [

        verify "Simple Test" {
            return getPerson()
        }

        verifyTask "Simple Test Task" {
            return! getPersonAsync()
        }

    ]

```

`verify` (non-async) is the most simple one (and the only one I have created yet), but there would also need to be a `verifyTask` and `verifyAsync` (which will be a bit more tricky).

#### Describe alternatives considered

It could also be done as a regular function instead of custom computation expressions, but CEs would look more uniform.

#### Additional context

If settings are also needed, the existing API could be used manually.
(Or, they could possibly even be integrated into the custom CEs)

**Comment by SimonCropp** [comment]
wouldnt this be better as a feature request to expecto? ie expecto could store the test name/list etc in an asynclocal, and expose it to extensions?

**Comment by JordanMarr** [comment]
I don’t think that would add enough value to be added to the core library as i don’t know any other extension libraries that need the `name`, and if they did, it’s fairly easy enough for them to extend it themselves, or for the user to do it themselves. 
And i suppose i just made the case against this feature. 😆

**Comment by SimonCropp** [comment]
how about you raise it on expecto. if they say no we can reconsider this
