### ISSUE TITLE
Make uniqueness guarantee for snapshots optional

### ISSUE THREAD

**Issue by andrewlock** [VerifyTests/Verify#415]
#### Is the feature request related to a problem

In [the Datadog APM tracer](https://github.com/DataDog/dd-trace-dotnet), we are using Verify with snapshots to verify a request is traced correctly. We run in two distinct modes, CallSite and CallTarget, and as such have separate tests for these. However, both tests should give the same output. 

[Verify enforces that each test uses a unique snapshot](https://github.com/VerifyTests/Verify/blob/main/src/Verify/Verifier/InnerVerifier.cs). That means we currently have duplicate snapshots for our tests, that could easily be consolidated, as half of them are identical.

#### Describe the solution

Providing a toggle to allow disabling of the uniqueness requirement for given test paths. I think this could be added as part of the `UniqueFor` API without too much friction?

#### Describe alternatives considered

Continuing to have many duplicate files (our existing solution), hard links between files (more hassle than it's worth)

#### Additional context

Thanks for the library! 🙇

**Comment by SimonCropp** [comment]
@andrewlock yep happy to add this. not sure if it should be at the `UniqueFor` level. since the use case could be when people are not even using the `UniqueFor` api. how about top level setting (static and instance?s

**Comment by andrewlock** [comment]
That's great, thanks @SimonCropp! Yes, that makes more sense I think.

I'm happy to work up a PR, or would you prefer to do it? Thanks again!

**Comment by SimonCropp** [comment]
sure. have a go at a pr. note i have moved to vs2022. if that is a complication i can handle the change
