### ISSUE TITLE
Edge case with SortPropertiesAlphabetically

### ISSUE THREAD

**Issue by asherber** [VerifyTests/Verify#416]
Using Verify.XUnit v13.1.0, .NET Core 3.1.

I was very happy to see the addition of `SortPropertiesAlphabetically()`, because I was also seeing that natural property order differed between runtimes and OSes.

One complex object model that I need to verify includes a property which is an `XmlElement`. Verify puts that property in the right order within the parent object, but the Json serializer is unable to look inside and sort the properties of the inner XML, which means that some of my tests which passed locally are still failing on our CI server.

I came up with what I thought was a clever workaround. Instead of verifying my object directly, I first converted it to a `JObject`, getting all the nested properties out in the open, and then verified that. 

```c#
var s = new JsonSerializer() { NullValueHandling = NullValueHandling.Ignore };
var obj = JObject.FromObject(input, s);

VerifierSettings.SortPropertiesAlphabetically();
return Verifier.Verify(obj);
```

This worked very well, except for the case where the `XmlElement` contained some XML with, for example, an attribute and a text node. On my local Windows machine, these would get serialized, sorted, and saved to the verified file like this:

```
{
  #text: foobar,
  @type: schemeName
}
```

But on my CI server, running on a Linux image, those two items would sort in the other order, causing the test to fail. This is consistent for all serialized nodes where there's something with a hash and something with an at; the hash sorts first on my machine, but the at sorts first on the CI server. This looks like it has something to do with the sort order in the current culture, except that I know Verify is using `StringComparer.Ordinal`, which should give the same results regardless of culture.

Here's a minimal repro that demonstrates the issue:

```c#
[UsesVerify]
public class UnitTest1
{
    [Fact]
    public Task Test1()
    {
        // This elides the step of creating an XmlElement and turning it into a JObject
        var obj = new JObject(
            new JProperty("@xmlns", "foo"),
            new JProperty("#text", "bar")
        );

        VerifierSettings.SortPropertiesAlphabetically();
        return Verifier.Verify(obj);
    }
}

/**
 * On my Windows machine, produces
 * {
 *   #text: bar,
 *   @xmlms: foo
 * }
 *
 * On CI server, produces
 * {
 *   @xmlms: foo,
 *   #text: bar
 * }
 */
```

**Comment by SimonCropp** [comment]
can u try 13.2.1

**Comment by asherber** [comment]
Works like a charm -- thank you! I didn't think to test a dictionary when I came across this issue.
