### ISSUE TITLE
Consider making the CounterContext public

### ISSUE THREAD

**Issue by benmccallum** [VerifyTests/Verify#431]
#### Is the feature request related to a problem

Currently if you want to scrub a particular value that doesn't necessarily fall in the `...Id` property or Guid basket, you're left with a regex replace and have to implement your own counting solution, which is fine, but given it's a problem already solved by Verify it'd be nice if we could tap into it.

#### Describe the solution

1. Make it public.

OR 

2. Perhaps go one step further and bring my whole extension method below into the core library, which is just a way to do the replacement with incrementing with a BYO regex. Then context counter can remain private.

#### Describe alternatives considered

1. Copy and paste Verify's solution into ours.
2. Maintaining a count in a regex replace ourselves. e.g. with a local replacement func like [here](https://gist.github.com/benmccallum/e971c9571ae2f37e5f375ba492eef2f5).

#### Additional context

Add any other context about the feature request here.

**Comment by SimonCropp** [comment]
it is global, but it is implemented as an async local that plugs in to the `OnVerify(Action before, Action after)` api.

Happy to make it public. 

> Actually damn, I've just realised this context is global to all running tests (or probably to the class?), so if you're testing against a real db and then run tests in different orders the results aren't the same

can u share this as a failing unit test so i can have a look

**Comment by benmccallum** [comment]
will see if I can today, might be difficult given it's the order of the tests in test class that's the problem though. e.g.

classA
  test1
    Id_x
  test2
    Id_y

If I run all tests for classA, x will be 1 and y will be 2.
If I run fact2 only, y will now be 1 (and not match 2 as above).

At least that's what I think I was seeing yesterday, I'll double check and try make a test but the inception is real. Perhaps calling verify twice in one unit test might be the way to demonstrate it if it's supposed to be scoped at OnVerify

**Comment by benmccallum** [comment]
Sorry Simon, I haven't forgot about this. Will revisit when I'm back from holidays.

**Comment by SimonCropp** [comment]
how does this look https://github.com/VerifyTests/Verify/pull/466

**Comment by benmccallum** [comment]
That's awesome @SimonCropp! Sorry for not getting back to this. I'll refactor my previous code onto this guy and assuming all is well if they are run in different orders then this is def closed.
