### ISSUE TITLE
Consider allowing us to modify the suffix convention for the Numeric Id scrubbing

### ISSUE THREAD

**Issue by benmccallum** [VerifyTests/Verify#432]
https://github.com/VerifyTests/Verify/blob/87f359db743d50b53682c1b945c78c6d0e52c8a3/src/Verify/Serialization/CustomContractResolver.cs#L165

We still have some legacy stuff which is using `XyzID` and that causes problems. If we could configure the convention, perhaps a `Func<string, bool>` (where string input is the property name) property on the settings we could override, that'd be great.

**Comment by SimonCropp** [comment]
hows this https://github.com/VerifyTests/Verify/pull/433/files?

**Comment by benmccallum** [comment]
That's awesome, thanks Simon. Should've realised it'd be on a MemberInfo :P 

If I can reproduce the issue with the id incrementing this will work very well.

**Comment by SimonCropp** [comment]
this is deployed (pending nuget updating its cache)
