### ISSUE TITLE
DateTime serialization settings are ignored

### ISSUE THREAD

**Issue by ben-hamida** [VerifyTests/Verify#434]
It seems that the settings related to DateTime serialization are being ignored. For example the following

 ```csharp
[Test]
public Task Test()
{
    return Verifier.Verify(new DateTime(2021, 11, 04, 0, 0, 0))
        .ModifySerialization(_ => _.DontScrubDateTimes())
        .AddExtraSettings(_ => _.DateFormatHandling = DateFormatHandling.MicrosoftDateFormat);
}
```

outputs `2021-11-04T00:00:00+1`, while the expected output is `\/Date(1635980400000+0100)\/`.

The other settings that I have confirmed are ignored are DateFormatString and DateTimeZoneHandling.

**Comment by SimonCropp** [comment]
that is because of the TreatAsString feature https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#treatasstring

So those types dont actually go trough the json serialization pipeline

**Comment by ben-hamida** [comment]
Is it possible to disable this feature for DateTime?

I found this workaound
```CSharp
var serializationSettings = new JsonSerializerSettings
{
    DateFormatHandling = DateFormatHandling.MicrosoftDateFormat
};
        
VerifierSettings.TreatAsString<DateTime>((dateTime, _) => JsonConvert.SerializeObject(dateTime, serializationSettings));
```

Maybe the TreatAsString feature should be opt-in for DateTime considering that there are settings that are expected to work that don't because of this feature?

In any case, I think there might still be a bug. The documentation says that this feature is enabled when an instance of a type for which this feature is enabled is passed _directly_ in to Verify. I take it this means when I call `Verifier.Verify<DateTime>`? But I still get the same behavior if i encapsulate the date time in a class:

```CSharp
[Test]
public Task Test()
{
    return Verifier.Verify(new Class())
        .ModifySerialization(_ => _.DontScrubDateTimes())
        .AddExtraSettings(_ => _.DateFormatHandling = DateFormatHandling.MicrosoftDateFormat);
}

private class Class
{
    public DateTime DateTime { get; set; } = new DateTime(2021, 11, 04, 10, 20, 20);
}
```

The above outputs
```Json
{
  DateTime: 2021-11-04T10:20:20
}
```

The difference was that this time disabling date time scrubbing was actually necessary.

**Comment by SimonCropp** [comment]
yeah that could be considered a bug. but why do you want to change the date format?

**Comment by ben-hamida** [comment]
I want to change the DateTimeZoneHandling property to Unspecified or Utc. What was serailized as '2021-11-04T00:00:00+1' on my computer got serialized as '2021-11-04T00:00:00+2' on the build server because of different time zones. So that obviously fails the test. I need to make the serialization independent of time zone.
