### ISSUE TITLE
Setting to suppress writing verify results to console

### ISSUE THREAD

**Issue by JordanMarr** [VerifyTests/Verify#444]
#### Is the feature request related to a problem
Yes:
When I run my project build scripts, the results of my Verify tests are printed to the build window which adds way too much noise to my build output that makes it difficult to focus on that actual build task output that I care about. 

#### Describe the solution

It would be great if the `VerifySettings` had an option to suppress info results from being written to the output window.
Maybe something like `SuppressInfoLog` or `SuppressLog`.

**Comment by SimonCropp** [comment]
are referring to the output for when a test fails? or some other log entry?

**Comment by JordanMarr** [comment]
Does it only output the when failed?
The problem is that it is injecting the entire output of of a verify test into my build script output, but the output is so large that it is truncating the first part of my build output.  

So really, I don't want to see the entire output in my log - even if it fails. 
Being able to either _not_ output the result at all, or alternatively, be able to limit it to say the first _x_ number of lines.

**Comment by SimonCropp** [comment]
> Does it only output the when failed?

yep

> Being able to either not output the result at all, or alternatively, be able to limit it to say the first x number of lines

Obviously possible. but... "Being able to either not output the result at all" seems like when it fails it would be difficult to work out what is wrong? "be able to limit it to say the first x number of lines" there is no guarantee that those lines contain the diff.

Instead would it be a better option to only output the changed lines? https://github.com/VerifyTests/Verify.DiffPlex  ?

**Comment by JordanMarr** [comment]
I just confirmed that it is only outputting on fail.
So my issue is that when it fails, it pipes so many lines in that when I try to scroll back to the top of my build log in the command window, the first part of my output has been truncated due to the size of my verified file taking so much space.

I do think that the ability to only output the changed lines would greatly improve the usefulness of writing the results out in the first place. 

If one of my Verify tests fails, I don't think that I would want to troubleshoot the differences in my command window anyway.

**Comment by SimonCropp** [comment]
Ahh sorry i was assuming you meant CI servers. yeah i make more sense if you are running local.

**Comment by SimonCropp** [comment]
this is now deployed https://github.com/VerifyTests/Verify/blob/main/docs/verify-options.md#omitcontentfromexception

**Comment by JordanMarr** [comment]
Thanks, that worked as intended and cleans up my build very nicely!
