### ISSUE TITLE
14.11.0 breaks projects which are not on c#10

### ISSUE THREAD

**Issue by tom-englert** [VerifyTests/Verify#448]
Not sure if this is an issue with Verify or with VisualStudio.

e.g. https://github.com/Fody/Fody/pull/1058 / https://github.com/Fody/Fody/commit/c189e1512500911e18198883479c951c6b6842e9 
does no longer build, because VS is generating files containing global usings, which it then complains it can't compile:
`8>C:\dev\GitHub\Fody\Tests\obj\Debug\netcoreapp3.1\Tests.GlobalUsings.g.cs(2,1,2,34): error CS8400: Feature 'global using directive' is not available in C# 8.0. Please use language version 10.0 or greater.`

The content of the file is:
```
// <auto-generated/>
global using global::VerifyTests;
global using global::VerifyXunit;
global using global::Xunit;
global using static global::VerifyXunit.Verifier;
```

I can't compile this PR version of Fody on my local machine with VS2022 (17.1.0)

Maybe the condition in `<ItemGroup Condition="'$(ImplicitUsings)' == 'enable'">` is important? 
What does Microsoft say about global usings in packages?

Can you reproduce this?

**Comment by SimonCropp** [comment]
sigh. i had assumed .net would be sensible enough to ignore those csproj settings in earlier versions of c#. i will fix
