### ISSUE TITLE
The forward slash is being scrubbed as "{UserProfile}" when building inside Docker in Jenkins

### ISSUE THREAD

**Issue by konstantin-smolyakov-idt** [VerifyTests/Verify#450]
#### Describe the bug

I've noticed cryptic bugs when running snapshot tests outside of my local machine:

1. When building inside the docker container with the sources mounted to `/app` folder, all `app` strings inside my snapshots were replaced with the `{SolutionDirectory}` tag. E.g. `application/json` -> `{SolutionDirectory}lication/json`. I see that I can possibly disable that scrubbing globally, so it's not that critical.
2. When building inside the docker container as Jenkins agent, the same happened to forward slashes. Each slash was replaced with `{UserProfile}` tag, so `application/json` would become `application{UserProfile}json`. I see user profile directory scrubbers are global, and I don't see a way to disable them.

I expect at least a way to disable scrubbing. Not really why they are enabled by default either. 

#### Minimal Repro

I might add this later if needed.

**Comment by SimonCropp** [comment]
given you can repro this, would you mind having a go as submitting a PR that fixes it

**Comment by konstantin-smolyakov-idt** [comment]
@SimonCropp What's the big idea behind global scrubbers? Any particular reason those I mentioned must be global? Any globals are evil 😄  I would think that all scrubbers should be opt-in.
