### ISSUE TITLE
Rider "Verify Support" plugin buttons does nothing

### ISSUE THREAD

**Issue by zlepper** [VerifyTests/Verify#452]
I'm not quite sure how to get the required information for the Rider plugin. 
And apologies if this issue is in the wrong Repo, couldn't find a repo for the plugin specifically.

#### Describe the bug
I'm using Verify to test a source generator. The test itself runs fine and has the expected output. However, trying to use the "Accept received" and "Compare Accepted/Receives" buttons does nothing. As in nothing happens when I click those buttons. I have ensured that tests are allowed to start sub-processes. When the test fails a diff tool does start, so Rider can clearly be found by Verify. 

Logs from Rider, where I only started the IDE, found a failing test and clicked those buttons. 
[rider verify logs.zip](https://github.com/VerifyTests/Verify/files/7768264/rider.verify.logs.zip)

And video in case my rambling didn't make any sense:

https://user-images.githubusercontent.com/1499810/147223348-8945bd14-0f98-42ea-989e-4f57801441d4.mp4

#### Minimal Repro

Here is a somewhat minimal solution that has a source generator and everything. The buttons still don't work. 
[VerifyBug.zip](https://github.com/VerifyTests/Verify/files/7768321/VerifyBug.zip)

#### Submit a PR that fixes the bug

I can't even find the code for the Rider plugin :(

**Comment by SimonCropp** [comment]
sorry for the redirect... can you re-raise this here https://github.com/matkoch/resharper-verify

**Comment by zlepper** [comment]
Raised as https://github.com/matkoch/resharper-verify/issues/5 instead.
