### ISSUE TITLE
Disable image comparison 

### ISSUE THREAD

**Issue by crruBoyum** [VerifyTests/Verify#454]
Hello!
I'm using Verify to do some snapshot testing in Blazor, and I would like to disable the comparison of png files for the Verifier.Verify(IElementHandle)

#### Is the feature request related to a problem
This issue is not related to a problem. When the tests are ran locally, there are no differences between the images, but when ran in an azure pipeline, some of the images throw "VerifyException : Results do not match". But since the image comparison isn't critical for my use case, I'd like to disable it.

#### Describe the solution
I would like the method to generate the png files (as it does), but not run a Compare between received and verified png files. So, when I run the tests in a pipeline, it will only throw the VerifyException in case the html files do not match. 

I looked into the VerifySettings to achieve this, but have been unsuccessful so far. Please let me know if I missed something.
Thanks!

Cristian.

**Comment by SimonCropp** [comment]
so what nugets are you using to do the snapshot testing?

**Comment by SimonCropp** [comment]
because by default Verify.Blazor does not produce an image https://github.com/VerifyTests/Verify.Blazor#result

**Comment by crruBoyum** [comment]
Thank you for your prompt answer.
I'm using the following nugets: 
- Verify (13.3.0)
- Verify.Bunit (7.1.3)
- Verify.Playwright (1.3.0)
- Verify.Xunit (13.3.0)

Side-note: I've managed to by-pass the issue somewhat by using ImageMagick (got that from the video in the Blazor Train episode).

**Comment by SimonCropp** [comment]
can you share your tests code

**Comment by crruBoyum** [comment]
```
public class BasicVerifyTests : IClassFixture<PlaywrightFixture>
{
    private readonly PlaywrightHelper _helper;
    private readonly IPage _page;
    private readonly ListPageHelper _listPageHelper;
    private readonly TestEndpointController _endpointController = new();
    private static string? _testFilesFolderFullPath;

    public BasicVerifyTests(PlaywrightFixture fixture)
    {
        TestDataAssistant.SetInputFilesConfigurations();
        _testFilesFolderFullPath = TestDataAssistant.InputFolderFullPath;
        _helper = new PlaywrightHelper(fixture, _endpointController.FrontendEndpoint, _testFilesFolderFullPath);
        _page = fixture.Page;
        PlaywrightHelper.Initialize();
        _listPageHelper = new ListPageHelper(_helper);
    }

    [Theory]
    [InlineData(UiPaths.DataConnectionList)]
    [InlineData(UiPaths.EmailTemplateList)]
    [InlineData(UiPaths.DataSourceList)]
    [InlineData(UiPaths.EmailProviderList)]
    [InlineData(UiPaths.ReportDefinitionList)]
    [InlineData(UiPaths.WorkFlowList)]
    public async Task GoToListPagesTests(string value)
    {
        await _listPageHelper.OpenListPageAsync(value);
        //var element = await _page.QuerySelectorAsync(".content");
        await Verifier.Verify(_page).UseParameters(value);

    }
}
```

**Comment by SimonCropp** [comment]
so that is a Playwright test, not a Verify.Bunit or a Verify.Blazor test. if you only care about the html i recommend you use Verify.Bunit or Verify.Blazor. That way the tests will run much faster, and you dont need the browser to render the html

**Comment by crruBoyum** [comment]
I'd like to have the images of how the rendered html looks, but not to necessarily compare them. It might be useful to be able to toggle the "compare images" on/off in different scenarios. Thank you for your help, though.  I'm still new to this :)

**Comment by SimonCropp** [comment]
you can achieve what you want by writing a custom comparer for those image types https://github.com/VerifyTests/Verify/blob/main/docs/comparer.md#comparer

**Comment by crruBoyum** [comment]
thanks for your help
