### ISSUE TITLE
Get path to original source for continuous test runners

### ISSUE THREAD

**Issue by JoshSchreuder** [VerifyTests/Verify#460]
#### Is the feature request related to a problem

When running tests under continuous test runners like NCrunch, the test project is copied to a temporary directory.
This leads to cases where if the approval fails, it's trying to save the updated approval to the temporary directory instead of the original source path.

eg. `C:\Users\Josh\AppData\Local\NCrunch\20688\5\MyTestProj\MyTest.received.txt` instead of `C:\Work\MyTestProj\MyTest.received.txt`.

#### Describe the solution

Have a mechanism to access the original source path if possible? Though I understand that reading stack traces is one of the things you didn't want to bring across to Verify.

From what I can tell ApprovalTests was [getting original source directory information from stack traces](https://github.com/approvals/ApprovalTests.Net/blob/14d5afd62a769bd9c60586b3d8fee7458b2dc347/src/ApprovalTests/Namers/UnitTestFrameworkNamer.cs#L28) to work around this issue?

#### Describe alternatives considered

I have tried using `DerivePathInfo` to try and set the original source path rather than the temporary NCrunch build path to no avail.

#### Additional context

Thanks in advance

**Comment by SimonCropp** [comment]
given i dont have a copy of ncrunch. do you want to have a go at submitting a PR that fixes this?

**Comment by JoshSchreuder** [comment]
Sure, I can give it a go. Do you have a preferred approach in mind for detecting the original source path?

**Comment by SimonCropp** [comment]
> Do you have a preferred approach in mind for detecting the original source path

well the approach used in ApprovalTests and Verify should be functionally equivalent. both use metadata embedded in the assembly. so i dont understand why one works and the other doesnt

**Comment by JoshSchreuder** [comment]
Ok, I'll start there and see what I can figure out then :)

**Comment by JoshSchreuder** [comment]
For anyone facing this problem, it can be worked around using `DerivePathInfo` and NCrunch.Framework (which you can install via Nuget)

```csharp
VerifierSettings.DerivePathInfo(
    (sourceFile, projectDirectory, type, method) => new(
        directory: Path.Combine(Path.GetDirectoryName(NCrunchEnvironment.GetOriginalProjectPath()), "Approvals"),
        typeName: type.Name,
        methodName: method.Name));
```

https://www.ncrunch.net/documentation/reference_runtime-framework_environment-class#documentationContent

**Comment by JoshSchreuder** [comment]
This seems to be working fine now without the above (just tried in 18.3 after seeing the NCrunch specific bug fix), so thank you for the fix whatever it was @SimonCropp 😄
