### ISSUE TITLE
are there global settings?

### ISSUE THREAD

**Issue by MihailsKuzmins** [VerifyTests/Verify#482]
Tried asking on stackoverflow, but to no avail (https://stackoverflow.com/questions/71210285/does-verifytests-verify-have-global-settings)

In the [docs](https://github.com/VerifyTests/Verify/blob/main/docs/naming.md#directory) it is mentioned how to setup a custom output directory for `Verify` and it works fine, but it is pain to do it for every test.
```cs
await Verify("value")
   .UseDirectory("CustomDirectory");
```
ApprovalTests have a global `UseApprovalSubdirectory` which solves this issue. So I wonder is there anything similar in here?  
The reason is that VS2022 does not allow renaming nested files, so I need to go to the file explorer and rename files there (pain...)

**Comment by SimonCropp** [comment]
you should be able to use [DerivePathInfo](https://github.com/VerifyTests/Verify/blob/main/docs/naming.md#derivepathinfo) to achieve this. So in your case

```
VerifierSettings.DerivePathInfo(
    (sourceFile, projectDirectory, type, method) =>
    {
        return new(
            directory: Path.Combine(projectDirectory, "CustomDirectory"),
            typeName: type.Name,
            methodName: method.Name);
    });
```

**Comment by MihailsKuzmins** [comment]
@SimonCropp, is there also `VerifierSettings.something` for `classLevelSettings.UseExtension("json");`? I cannot seem to find it :(

**Comment by SimonCropp** [comment]
is this what you are after https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#usestrictjson  ?

**Comment by MihailsKuzmins** [comment]
hmm, looks like, but it does not seem to work because the output file still has the `.txt` extension.

`DerivedPathInfo` works as expected and I get the output file where I need, but the extension is not changed to `.json`. (maybe I will try to checkout the source code and find out what goes wrong on my side)

![image](https://user-images.githubusercontent.com/47413092/155704343-b4a9fdb8-56f6-4f2e-a7b7-a10be3233cfd.png)
![image](https://user-images.githubusercontent.com/47413092/155704849-01fc8601-3a1e-4319-87ce-56121e48c5ed.png)

**Comment by SimonCropp** [comment]
are you calling `UseStrictJson ` in a ModuleInitializer?

**Comment by MihailsKuzmins** [comment]
I have tried using both the `[ModuleInitializer]` attribute and calling `VerifierSettings.UseStrictJson();` in the test method itself, but the result was the same - `.txt` extension was applied (both samples are down below).

So I have checked out the source code and the problem is here (in `TryGetTargetBuilder` or `InnerVerifier`):
Since I pass a JSON string the flow enters this if block and attempts to get an extension from the instance of `VerifySettings`. Since it is `null` the default `.txt` is returned. It is also obvious that the static `VerifierSettings.StrictJson` is ignored in this case because the first if block is never entered and the next if block is never reached (because of `return true`).

The problem is clear, but applying `VerifierSettings.StrictJson` within `if (!hasAppends && target is string stringTarget)` is a design issue which you should consider. I hope that the description is clear to you as well and we could try to decide what to do in this case

So again the workflow:
1) `target` is the JSON string value
2) `hasAppends` becomes `false`
3) `target is null` is evaluated to `false`. the if block is skipped
4) `!hasAppends && target is string stringTarget` evaluates to true and the if block is entered
5) `extension` is assigned to `.txt`, `VerifierSettings.StrictJson` is ignored
6) return true
![image](https://user-images.githubusercontent.com/47413092/155839942-5d45936b-713e-4c6a-a0df-b15af4c25cbe.png)


```cs
[ModuleInitializer]
public static void Aaa()
{
	VerifierSettings.DerivePathInfo((_, projectDirectory, type, method) =>
	{
		var basePath = GetExecutionPath(projectDirectory, type);
		basePath = Path.Combine(basePath, "Approvals");

		return new PathInfo(basePath, type.Name, method.Name);
	});

	VerifierSettings.UseStrictJson();
}
```

```cs
[Collection(CollectionDefinitions.Test), UsesVerify]
public class MyTests
{
	[Fact]
	public async Task Test()
	{
		VerifierSettings.UseStrictJson();

		var result = await GetJsonStringAsync();
		await VerifyAsync(result);
	}
}
```

**Comment by SimonCropp** [comment]
can u submit a failing unit test as a pull equest

**Comment by MihailsKuzmins** [comment]
this test was already present among other tests, but I have created it as well. Please take a look at #500

**Comment by StefH** [comment]
@SimonCropp 
It seems that the `VerifierSettings.DerivePathInfo` is not present in version 19.6.0?

**Comment by SimonCropp** [comment]
@StefH https://github.com/VerifyTests/Verify/blob/main/docs/naming.md#derivepathinfo

**Comment by SimonCropp** [comment]
@StefH https://github.com/VerifyTests/Verify/blob/main/docs/upgrade17-18.md#verifiersettingsderivepathinfo-moved
