### ISSUE TITLE
Add Playwright Snapshot Support

### ISSUE THREAD

**Issue by khalidabuhakmeh** [VerifyTests/Verify#494]
#### Is the feature request related to a problem

Verify snapshots support for Playwright traces, typically in a `.zip` format.

#### Describe the solution

Open the trace and snapshot `trace.trace` and `trace.network`.

[trace.zip](https://github.com/VerifyTests/Verify/files/8200185/trace.zip)
[trace.zip](https://github.com/VerifyTests/Verify/files/8200186/trace.zip)
[trace.zip](https://github.com/VerifyTests/Verify/files/8200187/trace.zip)
[trace.zip](https://github.com/VerifyTests/Verify/files/8200188/trace.zip)
[trace.zip](https://github.com/VerifyTests/Verify/files/8200190/trace.zip)

**Comment by SimonCropp** [comment]
looked into this and could not see any way to add value
