### ISSUE TITLE
First value of an enum is ignored during serialization

### ISSUE THREAD

**Issue by malilus** [VerifyTests/Verify#498]
Hi, I have encountered the following bug:

when calling verify on an object that has an enum property, this property is ignored during serialization,
if its value equals the first value of the enum type. 
I have attached a sample project that shows this. The 
The snapshot "VerifySerializationBug.Verify_FirstEnumValue_WillNotSerializeEnumProperty.received.txt" does not contain any data, while the other snapshots contain the serialized enum property.

* Tested on Visual Studio 2022 + Resharper with Resharper Verify Plugin
* Tested for xUnit and NUnit
* Tested for .NET 5 and .NET Framework 4.8

[VerifySerializationBug.zip](https://github.com/VerifyTests/Verify/files/8237513/VerifySerializationBug.zip)

**Comment by SimonCropp** [comment]
by default DefaultValueHandling.Ignore is used

https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#default-settings

**Comment by SimonCropp** [comment]
try putting this in a moduleinitializer 

```

        VerifierSettings.ModifySerialization(settings =>
            settings.AddExtraSettings(serializerSettings =>
                serializerSettings.DefaultValueHandling = DefaultValueHandling.Include));
```

**Comment by malilus** [comment]
That works. Thank you!

**Comment by SimonCropp** [comment]
@malilus good to hear

**Comment by kkumor** [comment]
For future visitors, there were some breaking changes after last response: https://github.com/VerifyTests/Verify/pull/533
Instead of you might want to use following snippet:
`VerifierSettings.AddExtraSettings(_ => _.DefaultValueHandling = Argon.DefaultValueHandling.Include);`
