### ISSUE TITLE
Run Verify on build server without source files present

### ISSUE THREAD

**Issue by Sopor10** [VerifyTests/Verify#511]
#### Is the feature request related to a problem

We have a 2 step process of building an running the tests in our CI/CD pipeline.
The output from the build  step is saved as an artifact and the tests are run on a different machine.
Therefore Verify (correctly) fails to find the `*.verified.txt` files.

#### Describe the solution

Is there a possibility to automatically add the `*.verified.txt` files to the build output?

**Comment by SimonCropp** [comment]
does adding this to your test project work?

```
  <ItemGroup>
    <None Update="**\*.verified.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

**Comment by Sopor10** [comment]
Thanks a lot, combining this with the code snipped from the Build Server doc worked perfectly.
