### ISSUE TITLE
Making Verify play nice with AutoFixture

### ISSUE THREAD

**Issue by egil** [VerifyTests/Verify#527]
Hi @SimonCropp,

Can you confirm what version you have pushed of Verify that should make UseParameters more AutoFixture friendly. Dont think I see it on NuGet.org.

_Cannot seem to post new discussions or reply to existing, so lets try an issue._

**Comment by SimonCropp** [comment]
@egil yeah discussion seems broken. i will try deleting it and recreating

**Comment by SimonCropp** [comment]
and i will push to nuget now

**Comment by egil** [comment]
> @egil yeah discussion seems broken. i will try deleting it and recreating

Report it to GitHub first before you delete it. That should not happen.

**Comment by SimonCropp** [comment]
fixed it

**Comment by egil** [comment]
Lets continue in the discussion forum again.
