### ISSUE TITLE
Globally enabled AutoVerify

### ISSUE THREAD

**Issue by paynecrl97** [VerifyTests/Verify#528]
Apologies if this is already supported, but I couldn't find a way to do it.

#### Is the feature request related to a problem

We sometimes make a change (such as renaming or adding a property to an object that is being verified) that causes widescale  changes to verified files. For example, imagine that we have a `User` object that is used in a lot of our output- adding a property to this object will invalidate a lot of our verified files and we need to go and correct that.

We'd like to be able to globally enable `AutoVerify` to make it easier to re-verify a large number of files.

#### Describe the solution

Add a method `AutoVerify(bool includeBuildServer = true)` to `VerifierSettings` that can be used to globally control this feature.

#### Describe alternatives considered

A lot of our tests are littered with the following lines:

```
// Uncomment to re-create the expected verifier files:
//verifySettings.AutoVerify();
```

Another alternative would be to have a static config class (outside of Verify) with a property to control this and litter tests with:
```
if (StaticConstClass.AutoVerify)
{
    verifySettings.AutoVerify();
}
```

#### Additional context

There's a concern about globally verifying received changes in the sense that you may accidentally or inadvertently auto verify a bad change, but I think this would be a risk that the consumer should be responsible for. Additionally- verified changes can be manually checked either when committing changes or via a PR etc...

**Comment by SimonCropp** [comment]
are you on windows or mac?

**Comment by paynecrl97** [comment]
Some of us are on windows, some of us are on Mac. I’m personally on windows.

**Comment by SimonCropp** [comment]
this is in 17.1.0 which will be on nuget in a few min

btw I find DiffEngineTray to be a better way to buld accept https://github.com/VerifyTests/DiffEngine/blob/main/docs/tray.md

**Comment by paynecrl97** [comment]
Thank you. 

I actually do use diff engine tray, but it doesn’t cover cases where a test might have multiple verify files. In this event the test will fail at the first file and then I have to run it again. 

Thanks again for adding the feature.

**Comment by SimonCropp** [comment]
>  doesn’t cover cases where a test might have multiple verify files. In this event the test will fail at the first file and then I have to run it again.

this should not be required. can you share the code that does this
