### ISSUE TITLE
UTF-8 BOM gets duplicated

### ISSUE THREAD

**Issue by 304NotModified** [VerifyTests/Verify#541]
#### Describe the bug

For some reason the UTF 8 gets duplicated by Verify test.

Tested it with:
-  VerifyTests.Xunit 16.9.0 and .NET 6
-  VerifyTests.Xunit 16.8.0 and .NET 6 after downgrade

#### Minimal Repro

```c#
var result = ... // a string with a UTF 8 BOM: EF BB BF
await Verifier.Verify(result).UseExtension("html");
```
The verified file now contains 2 times the BOM! 😮 
![image](https://user-images.githubusercontent.com/5808377/172396137-00a05448-1475-456e-ad73-5d8be3ebfe1a.png)

#### Submit a PR that fixes the bug

I'm not there yet. I need some advice where to fix this.

**Comment by SimonCropp** [comment]
i am confused. my understanding was that strings should only have a bom when encoded. so strings in memory should never have a bom?

**Comment by SimonCropp** [comment]
as for where the bug is my guess would be https://github.com/VerifyTests/Verify/blob/main/src/Verify/IoHelpers.cs#L3 and https://github.com/VerifyTests/Verify/blob/main/src/Verify/IoHelpers.cs#L48

but from what i can tell we are using the File method correctly?

**Comment by 304NotModified** [comment]
> i am confused. my understanding was that strings should only have a bom when encoded. so strings in memory should never have a bom?

With UTF8 a BOM is optional. Some tools do add the BOM to the string. For our case, we are creating a HTML file rendered by a Razor template. 
But there are also other cases that the BOM is in the string, e.d. download of (some) HTML files in by the WebClient: https://stackoverflow.com/questions/1317700/strip-the-byte-order-mark-from-string-in-c-sharp

**Comment by 304NotModified** [comment]
related, the guidelines are a bit confusing. The usage of the BOM varies between required, optional and don't 😅 


from : https://www.unicode.org/faq/utf_bom.html#bom7
> Q: How I should deal with BOMs?
> 
> Here are some guidelines to follow:
> 
> - A particular protocol (e.g. Microsoft conventions for .txt files) may require use of the BOM on certain Unicode data streams, such as files. When you need to conform to such a protocol, **use a BOM.**
> 
> - Some protocols allow **optional** BOMs in the case of untagged text. ...
> - Some byte oriented protocols expect ASCII characters at the beginning of a file. If UTF-8 is used with these protocols, use of the BOM as encoding form signature should be **avoided**.
> 
> - Where the precise type of the data stream is known (e.g. Unicode big-endian or Unicode little-endian), the BOM should **not be used**. In particular, whenever a data stream is declared to be UTF-16BE, UTF-16LE, UTF-32BE or UTF-32LE a BOM must not be used. (See also [Q: What is the difference between UCS-2 and UTF-16?](http://unicode.org/faq/utf_bom.html#utf16-11).) [[AF]](https://www.unicode.org/faq/attribution.html#AF)

**Comment by SimonCropp** [comment]
unfortunately many of the diff tools do a poor job of guessing encoding. without a utf8bom they show mangled text. so we need to keep it. 

I think the best option is skip the existing BOM when writing.

do u want to have a go at a PR? it not i will get to this tomorrow

**Comment by 304NotModified** [comment]
> unfortunately many of the diff tools do a poor job of guessing encoding. without a utf8bom they show mangled text. so we need to keep it.
>
> I think the best option is skip the existing BOM when writing.

I think also thats the best option. 

> do u want to have a go at a PR? it not i will get to this tomorrow

Im limited on time these weeks, so if you know where to add this,  I would really appreciate your change :)

**Comment by SimonCropp** [comment]
yep. should be done by tomorrow

**Comment by SimonCropp** [comment]
can u try 17.1.3

**Comment by SimonCropp** [comment]
hmm that didnt work

**Comment by SimonCropp** [comment]
try 17.1.4
