### ISSUE TITLE
GitHub releases are out to date - on-tag-do-release task gives an error

### ISSUE THREAD

**Issue by 304NotModified** [VerifyTests/Verify#544]
The latest release is 17.1.4

In github the latest release is 17.1.1

The error:

> [FTL] Bad Issue https://github.com/VerifyTests/Verify/pull/543 expected to find a single label with either Breaking Change, Bug, Documentation, Feature, Good First Issue, Help Wanted, Improvement, Question or Build.
GitReleaseManager.Core.Exceptions.InvalidIssuesException: Bad Issue https://github.com/VerifyTests/Verify/pull/543 expected to find a single label with either Breaking Change, Bug, Documentation, Feature, Good First Issue, Help Wanted, Improvement, Question or Build.

See  https://github.com/VerifyTests/Verify/runs/6785858074?check_suite_focus=true#step:2:53

**Comment by SimonCropp** [comment]
i am not going to get to this. i will try to do better in the future
