### ISSUE TITLE
Abstract storage location for diff files

### ISSUE THREAD

**Issue by benmccallum** [VerifyTests/Verify#547]
#### Is the feature request related to a problem

I'm verifying an ingestion process but want to simultaneously be testing it's perf (given realistic load) and therefore the database changes I'm verifying are large. I think the written files will be several megabytes in size. 

Worst case I'm probably OK with this being written to the git repo, but usually we try and avoid writing large files to the repo. 

It won't change often I'd imagine, so at least it won't really balloon out of control.

#### Describe the solution

All this got me wondering though, whether a diff that writes to a different location (e.g. cloud storage) might be worth considering as a feature add to Verify.

Current feeling is it might be overkill, but thought I'd raise it anyway.

#### Describe alternatives considered

Just ignore the fact the files are large and move on with life :P

#### Additional context

Add any other context about the feature request here.

**Comment by SimonCropp** [comment]
> a diff that writes to a different location (e.g. cloud storage) might be worth considering as a feature add to Verify.

I dont know how that would work. there are a variety of ways that accept changes. the most common being from within the diff tool or using the diff tray. how would those approachs "accept changes into cloud storage"? 

My other concern would be how cloud storage would work when people are managing multiple branches

**Comment by benmccallum** [comment]
All good points. Happy to close. At the end of day prob not worth over-engineering something just to save some MBs in a git repo.
