### ISSUE TITLE
Group different datetimeoffsets

### ISSUE THREAD

**Issue by SebastianStehle** [VerifyTests/Verify#559]
#### Is the feature request related to a problem

I have code in my API that looks basically like this

```
var entity = new Entity { Created = DateTime.UtcNow };
await DoX();
await DoY();
entity.LastUpdated = DateTime.UtcNow;
```

it is a little bit more complicated, but in general the problem is that `Created` is sometimes not the same as `LastUpdated`.

Therefore I sometimes get the following output

```
{
  created: DateTimeOffset_1,
  lastUpdate: DateTimeOffset_2,
}
```

And sometimes

```
{
  created: DateTimeOffset_1,
  lastUpdate: DateTimeOffset_1,
}
```

#### Describe the solution

"Group" DateTimeOffset values that are close to each other, defined by a delta value.

#### Describe alternatives considered

The only alternative I see is to disable DateTimeOffset members.

**Comment by SimonCropp** [comment]
unfortunately grouping by a delta would not fix the problem, only make it less likely to occur. Given multiple dates in a sliding window, eventually (based on perf) some will fall in the window and some will fall out. it would result in a difficult to debug issue.

you have two options

## 1 reuse the datetime

```
var now = DateTime.UtcNow;
var entity = new Entity { Created = now  };
await DoX();
await DoY();
entity.LastUpdated = now ;
```

## 2 scrub one of the values

https://github.com/VerifyTests/Verify/blob/main/docs/scrubbers.md

given you are happy for them to be represented with the same value, you may as well scrub one of them

**Comment by SimonCropp** [comment]
3 inject a DateTime.UtcNow service

u could also inject a service that provides a DateTime.UtcNow. then u can be in control of the values and ensure they are always different or the same based on your requirements
