### ISSUE TITLE
ScrubInlineGuids not scrubbing guid at end of line

### ISSUE THREAD

**Issue by drewburlingame** [VerifyTests/Verify#570]
#### Describe the bug

A clear and concise description of what the bug is. Include any relevant version information.

> String ending with guid `http://localhost/position/d16f33cd-5eb2-49f6-99a9-f14d05455e96` is not being scrubbed, even with `ScrubInlineGuids`

> String should be scrubbed with the guid value `http://localhost/position/Guid_1`

Using Verify 17.6.0

I'm unable to install the .net 7 preview to create a test and fix it.  I've debugged within my app and here's the screenshot of GuidScrubber.ReplaceGuids where it appears the method exits just as it's loaded the guid.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/103345/183312538-10b03f7f-1203-4788-97d2-425f9d2b22f1.png">

**Comment by SimonCropp** [comment]
can u try 7.6.1

**Comment by drewburlingame** [comment]
That's perfect.  Thanks for the quick turn around Simon.  Just in time for my presentation to introduce alternatives for improving our tests.
