### ISSUE TITLE
Custom scrubbers no longer work. 

### ISSUE THREAD

**Issue by OFark** [VerifyTests/Verify#603]
#### Describe the bug

Since 17.5.0 (17.5.0 worked fine) I cannot get any line level scrubbing to work. I am using Verify.MSTask

- ScrubLines
- ScrubLineswithReplace
- ScrubLinesContaining

None of these does anything when previously they did. 

Scrubbing Guids and Dates is working.

Here is some example code:
```cs
var settings = new VerifySettings();

settings.DontScrubGuids();
settings.ScrubNodesWith("JWT", "<User JWT>");
settings.ScrubNodesWith("RefreshToken", "<User RefreshToken>");
settings.ScrubNodesWith("PasswordSalt", "<User PasswordSalt>");
settings.ScrubNodesWith("PasswordHash", "<User PasswordHash>");

await Verify(loginAttempt.Value, settings);
```

```cs
internal static void ScrubNodesWith(this VerifySettings settings, string NodeName, string newValue) => 
        settings.ScrubLinesWithReplace(line => line.Trim().StartsWith(NodeName) ? $"{line[..(line.IndexOf(':'))]}: {newValue}" : line);
```

This was working just fine in 17.5.0 with my output files being scrubbed and lines being replaced. However, since then they are not. I can see my tokens in the created JSON.
I have tried not using my extension, I have tried `.ScrubLines(l => l.Trim().StartsWith("PasswordHash"))` and `.ScrubLinesContaining("PasswordHash")` and neither makes a difference.

**Comment by SimonCropp** [comment]
can u submit a failing unit test as a pull request

**Comment by OFark** [comment]
PR created #604

**Comment by SimonCropp** [comment]
based on your PR, can u try `settings.ScrubMember("SHA1");`

**Comment by SimonCropp** [comment]
oh u will need version 18.0.0-beta.3

**Comment by SimonCropp** [comment]
let me know if it doenst work for u and i will re-open

**Comment by OFark** [comment]
Ok, so ScrubMembers does work, in that it scrubs the entire line. Two problems though

1. The methods that don't work are still available and still don't work.
2. The ScrubMember removes the line, I still need to verify that the service I'm verifying returned some data, otherwise someone could remove parts of the model and Verify would still pass it.

**Comment by SimonCropp** [comment]
@OFark 

> The methods that don't work are still available and still don't work.

those old methods work on the text scenario. not on members duing serialization

> The ScrubMember removes the line, I still need to verify that the service I'm verifying returned some data, otherwise someone could remove parts of the model and Verify would still pass it.

can u try 18.0.0-beta.5

**Comment by OFark** [comment]
I am using 18.0.0-beta.5 is there a scrubmembers and replace method I've missed?

**Comment by SimonCropp** [comment]
so this doesnt work for you https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#scrub-member-by-name  ?

**Comment by OFark** [comment]
Yes, it scrubs the entire line. The problem is that I don't want to scrub the entire line, I want to keep the line but sanitise the value. Just like you do with dates and guids. That way if the model changes and someone removes a scrubbed property, Verify still checks that the property still exists,

**Comment by OFark** [comment]
Ahh so I scrolled down to see you have an example result, I am not getting that example, it's scrubbing the whole line blank.

**Comment by SimonCropp** [comment]
can u share your exact code

**Comment by OFark** [comment]
Ahh Ok, yes it works now. I see you pushed an update today, and I was still on beta3. 
Thanks.
