### ISSUE TITLE
`UseStrictJson` is not respected for empty strings

### ISSUE THREAD

**Issue by edumserrano** [VerifyTests/Verify#623]
## Description

I noticed this issue when running a test with `Verify.Quibble`. It threw an `System.Text.Json.JsonReaderException`  when the JSON model contained an empty `string` and `received` is different from `verified`.

## How to reproduce

1) Create a new xUnit test project.
2) Create a test class equal to [Verify.Quibble/src/Tests/Tests](https://github.com/VerifyTests/Verify.Quibble/blob/main/src/Tests/Tests.cs)
2) Run the test the first time to get the `verified` file created
3) Run it again and the test passes
4) On the `Sample` test, change `Property1` on the `Target` model from `ValueC` to an empty `string`
5) Run the test again.

I would expect that in the test result Verify now detects a change between the `received` and `verified` since we changed the `ValueC` to empty `string` for the `Property1`.

What happens is that we get the following exception:

```
Message: 
System.ArgumentException : Failed to parse the value passed for leftJsonString as a JSON value. See inner exception for details. (Parameter 'leftJsonString')
---- System.Text.Json.JsonReaderException : ',' is an invalid start of a value. LineNumber: 1 | BytePositionInLine: 15.

Stack Trace: 
JsonStrings.parse(String s, String paramName)
JsonStrings.diff(String leftJsonString, String rightJsonString)
JsonStrings.TextDiff(String leftJsonString, String rightJsonString)
<>c.<Initialize>b__0_0(String received, String verified, IReadOnlyDictionary`2 _) line 22
Comparer.CompareStrings(String extension, String received, String verified, VerifySettings settings) line 38
Comparer.Text(FilePair filePair, String receivedText, VerifySettings settings) line 13
VerifyEngine.GetResult(VerifySettings settings, FilePair file, Target target, Boolean previousTextFailed) line 39
VerifyEngine.HandleResults(List`1 targetList) line 60
InnerVerifier.VerifyInner(Object target, Func`1 cleanup, IEnumerable`1 targets) line 25
InnerVerifier.Verify[T](T target) line 80
<<Verify>b__0>d.MoveNext() line 31
--- End of stack trace from previous location ---
Tests.Sample() line 20
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
Utf8JsonReader.ConsumeValue(Byte marker)
Utf8JsonReader.ReadSingleSegment()
Utf8JsonReader.Read()
JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
JsonDocument.Parse(String json, JsonDocumentOptions options)
JsonStrings.parse(String s, String paramName)
```

## Analysis

It seems the issue for the above exception when using `Verify.Quibble` is that the `json` that written to in the `verified` file is not correct for an empty `string` despite using `VerifierSettings.UseStrictJson();`.

In the reproduction example above, the `verified` file that gets created when we set `Property1` to an empty string looks like this:

```json
{
  "Property1": ,
  "Property2": "ValueD"
}
```

As you can see, even though we want to use strict json, the value for the key `Property1` doesn't have `""`. The above `json` is what we get if we don't have any `verified` file and we run the test but start with an empty `string`.

## System

This happens when using the following NuGet package versions:

```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.0" />
<PackageReference Include="Verify.Quibble" Version="1.2.0" />
<PackageReference Include="Verify.Xunit" Version="17.10.2" />
<PackageReference Include="xunit" Version="2.4.2" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
<PackageReference Include="coverlet.collector" Version="3.1.2">
```

in the following system:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\
```

## Pull request

`Handle empty strings properly when using strict json mode` #622 is an attempt to fix this bug.

**Comment by SimonCropp** [comment]
can u try 18.0.0-beta.12

**Comment by edumserrano** [comment]
I believe you can close this issue. 

1) Updated to use `Verify.Xunit` `18.0.0-beta.14` and with `VerifierSettings.UseStrictJson();` the file generated does now have `""` for the JSON value of an empty string.
2) Tested with `Verify.Xunit` `18.0.0-beta.14` and `Verify.Quibble` `2.0.0-beta.3` and everything worked as expected.

> Note
> Unrelated to this issue I did notice though that the new package the new version `18.0.0-beta.14` of the package changes the order in which the JSON properties are written to the file. On version `17.10.2` the JSON properties are written in asceding alphabetical order. On version `18.0.0-beta.14` the properties order is kept based on the input given to `VerifyJson`. 
> For instance, the following `string`:
> ```
> {"hasMoreLinks":false, "count":2}
>```
> in version `17.0.2` gets written to the file with the `count` property first and the `hasMoreLinks` second but in version `18.0.0-beta.14` it gets written as is with `hasMoreLinks`  first and `count` second.
> 
> When using Quibble to compare this difference in order isn't even flagged but if not using Quibble the files are all flagged as changed even though it's just the order of the properties that changed.
>
> Though this was work flagging just in case.

**Comment by SimonCropp** [comment]
@edumserrano good to hear. hopefully the extra tests i added will reduce the change of this happening again
