### ISSUE TITLE
Add Bearer Token Scruber

### ISSUE THREAD

**Issue by AnthonyDTrad** [VerifyTests/Verify#626]
#### Is the feature request related to a problem

Most of us use Verify for our testing projects. In my integration testing against an API, it is really common to have some sort of Authorization (Bearer Tokens, User and pass etc...). I currently have to manually remove those from the HttpResponseMessage before sending that to verifier.

#### Describe the solution

A more clear and concise way of doing things is to implement a scrubber than removes the Bearer Token. That way it will be consistent and everything will be removed from a single place. This feature can go beyond JWT Tokens and implement Client Credentials and other security types.

#### Describe alternatives considered

I am currently removing them from the object before sending to verifier which is messy.

#### Additional context

This was easily solvable if there's a Regex Scrubber. But we don't have that and the StringBuilder only matches to static strings. I don't want to convert the entire file to a string for performance issues. So the ideal alternative would be regex capabilities in scrubbing.

**Comment by Muchaszewski** [comment]
Hey did you try the `ScrubLines` method? 

```
// Notice space after Bearer
_verifySettings.ScrubLines(s => s.StartsWith("Bearer "));
```

for me, this works pretty straightforward and works for many tests that we have.

There is also a more fancy method that you can use that we have for some tests, that keeps the bearer but replaces it with something that is easily verifiable and comparable

```
        List<string> tokens = new();
        _verifySettings.ScrubLinesWithReplace(s =>
        {
            if(s.StartsWith("Bearer ")
            {
                var indexOf = tokens.IndexOf(id);
                if (indexOf != -1)
                {
                    return "Bearer token-" + indexOf;
                }
                tokens.Add(id);
                return "Bearer token-" + (tokens.Count - 1);
            }

            return s;
        });
```

**Comment by SimonCropp** [comment]
would this meet your requirement https://github.com/VerifyTests/Verify.Http#ignoring-headers  ?
