### ISSUE TITLE
Cannot get it to run with NUnit

### ISSUE THREAD

**Issue by andreasmuellergin** [VerifyTests/Verify#631]
Using Visual Studio 2022 a .net core 6.0 project with NUnit 3.13.3, Verify 17.10.2 and VerifyNunit 17.10.2 i cannot get the verification mechanism to kick in. 

The test just passes all the time, no files are being generated, no diff tool is popping up. 

I created a public test project which i ask you to have a look at. 

https://github.com/andreasmuellergin/VerifyTest

**Comment by andreasmuellergin** [comment]
Nevermind i noticed my mistake.
I was unaware of the fact that Verify actually returns a Task which is to be awaited or exposed to the Test runner. 

Keep up with the great work, thank you.

**Comment by SimonCropp** [comment]
glad you got it working
