### ISSUE TITLE
Nuget reference to xunit prevents from using it with xunit.assert.source

### ISSUE THREAD

**Issue by Chaosflo** [VerifyTests/Verify#649]
Note: New issues raised, where it is clear the submitter has not read the issue template, are likely to be closed with "please read the issue template". Please don't take offense at this. It is simply a time management decision. If someone raises an issue, and can't be bothered to spend the time to read the issue template, then the project maintainers should not be expected to spend the time to read the submitted issue. Often too much time is spent going back and forth in issue comments asking for information that is outlined in the issue template.

#### Preamble

General questions may be better placed [StackOveflow](https://stackoverflow.com/).

Where relevant, ensure you are using the current stable versions on your development stack. For example:

 * Visual Studio
 * [.NET SDK or .NET Core SDK](https://www.microsoft.com/net/download)
 * Any related NuGet packages

Any code or stack traces must be properly formatted with [GitHub markdown](https://guides.github.com/features/mastering-markdown/).

#### Describe the bug

Hello there! 
When I combine Verify.Xunit with xunit.assert.source package, the Assert class results in a conflict.

If you don't know, this packages allows you to define custom assert which is needed by our project.

This problem is in many repositories and there is an easy fix normally by simply reducing the nuget references.

Is it possible that the xunit.assert reference could be removed?
If not, would it be possible to use the xunit.assert.source package instead?

#### Minimal Repro

Simply install xunit.assert.source and Verify.Xunit package in one project

#### Submit a PR that fixes the bug

Submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.

**Comment by SimonCropp** [comment]
can u push up a repro of this to a github repository

**Comment by Chaosflo** [comment]
Its not that difficult, simply make a solution with XUnit Test and add the xunit.assert.source package

**Comment by SimonCropp** [comment]
can u try 18.0.0-beta.18

**Comment by Chaosflo** [comment]
Aww nice one!!!!

Really cool many thanks

**Comment by tom-englert** [comment]
That works great, even with older Verify versions, you just have to suppress CS0436:
```
[*.cs]
# CS0436: Type conflicts with imported type
dotnet_diagnostic.CS0436.severity = none
```
So no need to break other projects
