### ISSUE TITLE
Proposal add a library to compare folder/file structures

### ISSUE THREAD

**Issue by taori** [VerifyTests/Verify#670]
#### Is the feature request related to a problem

I have a project where i verify a scaffolding process. Up until now i did this with a lot of mocking, but recently ran into Verify and figured this may be an interesting topic in general.

#### Describe the solution

- Clone target folder hierarchy and compare it with incomming folder hierarchy.
- Configuration options on whether to include file contents into testing or just folder/file structure

#### Describe alternatives considered

None yet - So far testing dotnet templating seems to be a highly manual process. Doing this with Verify might turn the process into something much less annoying.

#### Additional context

This should be implemented as a generic Directory structure comparison independant of dotnet templating. that way you could easily unit test installers for msi too i think.

**Comment by SimonCropp** [comment]
i assume you found https://github.com/VerifyTests/Verify/blob/main/docs/verify-directory.md

**Comment by taori** [comment]
i did indeed. thanks however for your reply and this great method to implement tests

**Comment by SimonCropp** [comment]
no worries. note that VerifyDirectory is a recent addition. so if u have an feedback, please let me know
