### ISSUE TITLE
Serialize DateTime with consistent timezone

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [VerifyTests/Verify#675]
I have an issue similar to https://github.com/VerifyTests/Verify/issues/434. Our local development and build server have different timezones which cause build failures when verifying DateTime values. 

The test is related to a DateTime issue, so we need the DateTimes.

```csharp
public static class Initializer
{
    [ModuleInitializer]
    public static void Run()
    {
        VerifierSettings.DontScrubDateTimes();
    }
}

record Test(DateTime DateTime);

[UsesVerify]
public class UnitTest1
{
    [Fact]
    public async Task Test1()
    {
        await Verify(new DateTime(2022, 10, 17, 9, 6, 16, DateTimeKind.Local));
    }
    
    [Fact]
    public async Task Test2()
    {
        var test = new Test(new DateTime(2022, 10, 17, 9, 6, 16, DateTimeKind.Local));
        await Verify(test);
    }
```

Which gives:
Test1:
```
2022-10-17T09:06:16+2
```
Test2:
```
{
  DateTime: 2022-10-17T09:06:16+02:00
}
```

My first attempt was:
```csharp
VerifierSettings.AddExtraSettings(js => js.DateTimeZoneHandling = DateTimeZoneHandling.Utc);
```
which gives the exception:

```
System.Exception
Custom RoundtripKind is not supported. Instead use VerifierSettings.TreatAsString<DateTime>(func) to define custom handling.
```

So the next attempt was (exclamation marks for identifying!):
```csharp
VerifierSettings.TreatAsString<DateTime>((dt,_) =>
  dt.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss!!", CultureInfo.InvariantCulture));
```
but that only seems to work when the DateTime is passed in directly (i.e. Test1) and not when the DateTime is part of an object.

Test1:
```
2022-10-17T07:06:16!!
```
Test2:
```
{
  DateTime: 2022-10-17T09:06:16+02:00
}
```

Is there any way to configure the serialization of a DateTime that is part of an object? It would be great if the tests did not depend on the timezone of where they run!

**Comment by SimonCropp** [comment]
can u try version 18.0.0-beta.32
