### ISSUE TITLE
Library for developing roslyn analyzer unit tests

### ISSUE THREAD

**Issue by taori** [VerifyTests/Verify#676]
#### Is the feature request related to a problem

Developing roslyn analyzers requires unit tests 100%. While tooling to write tests has improved a lot, comparing actual vs expected output is not as easy. I just wrote an analyzer which accidentally marked the whole class as warning span, instead of the class identifier. With visual highlighting of the marked diagnostics that would not have been the case.

#### Describe the solution

Ideally test input is copied and diagnostics are marked with a special syntax to verify whether the output  is correct or not.

#### Describe alternatives considered

Testing without it just using Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.XUnit or similar

**Comment by SimonCropp** [comment]
so you are proposing an extension to Verify that helps snapshot the various roslyn analyzer types? ie in the same way this does for source generators  types https://github.com/VerifyTests/Verify.SourceGenerators ?

**Comment by taori** [comment]
Yes, in a very similar fashion, except for marking diagnostics inline with the original code. An older version of the test sdk used to compare the char sequences because it was too tedious when anything changed. If this feature for example produced output like this:
```
// arguments
//diagnostics
// ACA001
{details of diagnostic, message parameters, list of locations}
public class <ACA001:01>TestClass</ACA001:01>
{
}
```

That would make it easy to identify diagnostics with multiple locations, their precise locations and comparing whether or not message arguments and so on are correct.

**Comment by taori** [comment]
First i wanted to make sure that this fits into the general theme of the extensions in this organisation. Another concern of mine is how would you like for this to be done? I did not inspect every repo yet, but it feels like it is 1 repo per extension, but this extension would at least spawn 4 packages for XUnit, MSTest, NUnit + Shared code. What is the process of having it merged with VerifyTests organisation? Or is this organisation exclusively for packages you created by your own demand?

**Comment by SimonCropp** [comment]
> general theme of the extensions in this organisation

i just put extensions i create in this org. you can maintain you own extension outside the org

> this extension would at least spawn 4 packages for XUnit, MSTest, NUnit + Shared code

I dont understand why this would be required. no other extension has required this. but if it did you can manage the code any way you want

> What is the process of having it merged with VerifyTests organisation
> is this organisation exclusively for packages you created

it doesnt need to be under the VerifyTests organisation

**Comment by taori** [comment]
Okay. Thanks for the clarification
