### ISSUE TITLE
# for index makes accepting changes more difficult

### ISSUE THREAD

**Issue by JoshSchreuder** [VerifyTests/Verify#684]
#### Describe the bug

#637 changed to use "#" to delineate index. I think overall this is a good change, however it makes accepting changes via file rename much more difficult, as VS won't accept files with "#" in the name without chucking an error message up.

![image](https://user-images.githubusercontent.com/681706/197645539-a2b10980-85c2-47a1-a0c5-77f825f91a38.png)

Perhaps I am in the minority here, but would it be possible to reconsider the approach here and use a different character?

**Comment by SimonCropp** [comment]
Why would VS be blocking that?

> would it be possible to reconsider the approach here and use a different character

what character do u you propose?

(i wish you had raised this during the 2 month beta period of this release)

**Comment by JoshSchreuder** [comment]
Honestly not sure why VS is doing that, probably some wacky legacy reason. 
I'm fine if the answer is no of course as it's your project.

Perhaps `[00]`? It is harder to read probably, though it kind of fits with array index notation.

**Comment by SimonCropp** [comment]
the VS behavior gets weirder 

https://developercommunity.visualstudio.com/t/Cant-use--to-create-or-rename-a-file/10180338

**Comment by SimonCropp** [comment]
@JoshSchreuder have you tried using [a different compare tool](https://github.com/VerifyTests/DiffEngine#supported-tools)? VS is chosen last since (even aside from this issue) it has the worst experience

Or using [DiffEngineTray](https://github.com/VerifyTests/DiffEngine/blob/main/docs/tray.md)

**Comment by JoshSchreuder** [comment]
@SimonCropp have been using Beyond Compare but we're doing image comparison which I don't think it copes too well with. As I said, feel free to close this if it's not really a priority for you.

I'll try DiffEngineTray

**Comment by SimonCropp** [comment]
> Perhaps [00]? It is harder to read probably, though it kind of fits with array index notation.
> As I said, feel free to close this if it's not really a priority for you.

I want to see this fixed. but `[00]` would be another breaking change and a reasonable amount of friction for consumers

> Beyond Compare but we're doing image comparison which I don't think it copes too well with

BC works fine with image comparison. i have been using it for years

**Comment by SimonCropp** [comment]
or more specifically: in what way is VS better than BC for comparing images?

**Comment by JoshSchreuder** [comment]
Yeah I should clarify, I usually rename received -> verified then compare outside of VS (in the git tool Fork which has swipe comparison)

This renaming part could be done via script or DiffEngineTray or whatever as you note, so it's not a huge blocker.

**Comment by SimonCropp** [comment]
if u always use your git tooling. perhaps autoverify would work for you?
https://github.com/VerifyTests/Verify/blob/main/docs/verify-options.md#autoverify

**Comment by JoshSchreuder** [comment]
Thanks for the advice, I'm going to try that out and see how we go.

**Comment by SimonCropp** [comment]
given this is a bug in VS, and has been logged, will close this one

**Comment by JoshSchreuder** [comment]
Autoverify works quite well for our workflow, thanks for the tip

**Comment by SimonCropp** [comment]
is that the preference for you whole team? and if so how many people is that?

**Comment by JoshSchreuder** [comment]
Team is about 4-5 people so pretty small. We can review on the pull request side also with image comparison quite easily so auto approve works quite well here I think.
