### ISSUE TITLE
Verify.Xunit should reference full  Xunit package 

### ISSUE THREAD

**Issue by tom-englert** [VerifyTests/Verify#686]
With this we can optionally omit the reference to Xunit in the test projects, avoiding the ubiquitous dependabot errors when it tries to bump Verify.

Reducing the Xunit referenced to a minimum doesn't really make sense here - when you use Verify.Xunit, you surely want to use Xunit

**Comment by SimonCropp** [comment]
given Verify.Xunit will not necessarily re-deploy when Xunit updates, and we want to be referencing the newest Xunit, shouldnt any consuming package reference Xunit to ensure they have the latests?

**Comment by SimonCropp** [comment]
also note https://github.com/VerifyTests/Verify/issues/649

**Comment by tom-englert** [comment]
It still can

**Comment by tom-englert** [comment]
#649 should have been able to resolve by adding the correct direct references in the client project.
Now many existing projects are broken.

**Comment by SimonCropp** [comment]
@Chaosflo  thoughts?

**Comment by tom-englert** [comment]
I could fix this by referencing Xunit as version "*" to always have the latest version.
