### ISSUE TITLE
Verifying byte arrays has different behavior in v18 than in v17

### ISSUE THREAD

**Issue by xt0rted** [VerifyTests/Verify#689]
#### Describe the bug

I'm updating from v17.10.2 to v18.1.1 (also tried v18.0.0) and one of my tests started to fail. The verification files prior to v18 were `.bin` but now they're `.txt` with different contents in them. This looks to probably be due to the changes in #656. That PR also isn't listed in the release notes.

I was calling `Verify(bytes)` but now I have to call `Verify(bytes, extension: "bin")` to get the same results. I'm not sure if this is a bug or the intended behavior after those changes.

#### Minimal Repro

This is the PR where the issue came up https://github.com/xt0rted/dotnet-startup-projects/pull/10

**Comment by xt0rted** [comment]
@SimonCropp I just updated to 18.2.0 and switched this:

```csharp
await Verify(File.ReadAllBytesAsync(suoPath), extension: "bin").UseParameters(version, folder);
```

to this:

```csharp
await Verify(File.ReadAllBytesAsync(suoPath)).UseParameters(version, folder);
```

Now I'm getting the following error:

```text
C:\dev\xt0rted\dotnet-startup-projects\test\SetCommandTests.cs(90,15): error CS0121: The call is ambiguous between the following methods or properties: 'Verifier.Verify<T>(Task<T>, VerifySettings?, string)' and 'Verifier.Verify(Task<byte[]>, VerifySettings?, object?, string)' [C:\dev\xt0rted\dotnet-startup-projects\test\Tests.csproj]
```

If I switch back to my original code where I await the method then it builds ok.

```csharp
await Verify(await File.ReadAllBytesAsync(suoPath)).UseParameters(version, folder);
```

**Comment by SimonCropp** [comment]
@xt0rted can u try 18.3.0

**Comment by xt0rted** [comment]
@SimonCropp 18.3.0 works great, thanks! Both with and without the `await` work as they used to in my test https://github.com/xt0rted/dotnet-startup-projects/pull/15.
