### ISSUE TITLE
Serialization settings not passed on to JToken converters

### ISSUE THREAD

**Issue by hennys** [VerifyTests/Verify#691]
Using Verify: v3.0.0 on .NET 6.0 in VS 2022 (17.3.6)

While using Verify to verify JSON output from OpenAPI specification generation, I realized that `$ref` properties in the document were replaced with `null` by Verify. 

Simplified, this JSON:
```JSON
{
   "schema": {
       "$ref": "#/components/schemas/MyComponent"
   }
}
```

Became serialized by Verify as:
```JSON
{
   "schema": null
}
```

I tracked this down to [how the JToken is converted to a dictionary](https://github.com/VerifyTests/Verify/blob/425952a1fd692f2d021afeb85d500cf777a25fd4/src/Verify/Serialization/Converters/JObjectConverter.cs#L7) and how the serializer treats 'metadata properties'. I could reproduce the behavior in Argon and also show how you could control this behavior by passing in a serializer with `MetadataPropertyHandling` set to `Ignore`.

```c#
var json = JToken.Parse("{'$ref': '#/no/ref'}");

var withDefaultSerializer = json.ToObject<OrderedDictionary>();
Assert.Null(withDefaultSerializer);

var serializer = JsonSerializer.Create(new JsonSerializerSettings { MetadataPropertyHandling = MetadataPropertyHandling.Ignore });
var withCustomSerializer = json.ToObject<OrderedDictionary>(serializer);

Assert.NotNull(withCustomSerializer);
```

I tried to apply this to the serializer settings using `.AddExtraSettings(s => s.MetadataPropertyHandling = Argon.MetadataPropertyHandling.Ignore)`, but since those settings are not passed into the `ToObject` method in the [JObjectConverter](https://github.com/VerifyTests/Verify/blob/425952a1fd692f2d021afeb85d500cf777a25fd4/src/Verify/Serialization/Converters/JObjectConverter.cs#L7) they do not apply. I believe the same is true for [JArrayConverter](https://github.com/VerifyTests/Verify/blob/main/src/Verify/Serialization/Converters/JArrayConverter.cs#L6).

I had some issues getting the solution running properly in it's default configuration, so apologies for lack of PR. I can make a further attempt if you would prefer this.

Using xUnit:

```c#
[Fact]
public async Task VerifyJsonShouldRespectSerializerSettings()
{
    var json = "{'$ref': '#/no/ref'}";

    await Verify(json)
        .AddExtraSettings(s => s.MetadataPropertyHandling = Argon.MetadataPropertyHandling.Ignore);
}
```

**Comment by SimonCropp** [comment]
can u try 18.2.1

**Comment by hennys** [comment]
Works perfectly. Many thanks! Much appreciated.
