### ISSUE TITLE
Add a tag and release for 19.0.0

### ISSUE THREAD

**Issue by pellared** [VerifyTests/Verify#711]
I see no release not tag for https://www.nuget.org/packages/Verify.Xunit/19.0.0

I resist do not bump the package unless the repository has a tag (release). Maybe it is a malicious package  😉 
Also it would be good to know what changed.

**Comment by SebastianStehle** [comment]
There is also a big breaking change: The casing of properties has changed. In my `.verified.txt` files everything is camelCase, but the new files are PascalCase

**Comment by SimonCropp** [comment]
done https://github.com/VerifyTests/Verify/releases/tag/19.0.0

@SebastianStehle 

> everything is camelCase, but the new files are PascalCase

can you share a repro?

**Comment by pellared** [comment]
@SimonCropp Thanks. Closing.

@SebastianStehle I think it would be better if you create a new issue and share the repro steps 😉
