### ISSUE TITLE
The casing issue

### ISSUE THREAD

**Issue by SebastianStehle** [VerifyTests/Verify#712]
Just wanted to inform you about the "bug" with the casing.

I am testing API calls with an generated client for OpenAPI with JSON.NET. The properties have attributes, generated by the source generator, e.g.

```
class FooBar
    {
        [JsonProperty("text")]
        public string Text { get; set; }
    }
 ```
    
 So in 17.5 the *.txt file was looking like this 
 
 
 ```
 {
  text: 123
}
```

But I guess you moved to System.Text.Json later on and therefore the JsonPropertyAttribute is ignored now and this leads to generated files like this:

```
{
  Text: 123
}
```

**Comment by SimonCropp** [comment]
this is expected. Verify did not move to System.Text.Json. it moved to [Argon](https://github.com/SimonCropp/Argon). so JsonProperty from newtonsoft are no longer recognised.  

does the change in casing cause issues for you?

**Comment by SebastianStehle** [comment]
All my tests have failed suddenly, but this is not a big deal. Just wanted to inform you.

**Comment by SebastianStehle** [comment]
What is the motivation for Argon?

**Comment by SimonCropp** [comment]
i needed many features that do not exist in newtonsoft.
