### ISSUE TITLE
Received file should use specified names of ValueTuples rather than Item1, Item2, etc

### ISSUE THREAD

**Issue by LorneCash** [VerifyTests/Verify#725]
#### Is the feature request related to a problem

When doing Verify on a ValueTuple with named fields the received file uses Item1, Item2, etc as property names rather than the names specified. Here's an example:

if my method signature looks like this:
```c#
public (List<Story> Stories, string QueryUrl) GetNews(...)
```

and I verify it like this:
```c#
await Verify(GetNews(...));
```

the received file looks like this:
```
{
  Item1: [
    {
        ...
    },
    {
        ...
    }
  ],
  Item2: https://...
}
```

#### Describe the solution

I would very much like to see the received file looks like this:
```
{
  Stories: [
    {
        ...
    },
    {
        ...
    }
  ],
  QueryUrl: https://...
}
```

#### Describe alternatives considered

The workaround of course would be to just do this:
```c#
var news = GetNews(...);
await Verify(new { news.Stories, news.QueryUrl });
```

#### Additional context

I tried a quick search to see if I could figure out how to grab the names given to the Tuple's fields but didn't find anything.  I'm assuming it's possible, probably worth a question on SO.

**Comment by SimonCropp** [comment]
https://github.com/VerifyTests/Verify/blob/main/docs/named-tuples.md
