### ISSUE TITLE
Verify.Nunit 17.10.2 -> 18.0.0.0 with ImageSharp 3.9.0 Produces different Verified/Received file names

### ISSUE THREAD

**Issue by chasewallis** [VerifyTests/Verify#727]
## Bug Description
I'm having difficulty updating Verify past version 17.10.2. As soon as I upgrade to anything 18 and over, when I run the tests with ImageSharp 3.9.0, the *.verified.{json | png} are all blank. It took a while for me to notice, but all the *.verified and *.received file names are different than what they were in 17.10.2

## Minimal Repro
I was able to replicate with a very simple test:
```csharp
[TestFixture]
public class ImageTests
{
    static ImageTests()
    {
        VerifyImageSharp.Initialize();
    }
    [Test]
    public async Task GetImagesForItem_bytearray()
    {
        var bytes = File.ReadAllBytes("A.png");

        var image = Image.Load<Rgba32>(bytes);
        await Verify(image);
    }
}
```
where `A.png` is just a simple png generated from dummyimage.com. Run this with Verify.Nunit 17.10.2 and ImageSharp 3.9.0 and accept the changes. There should be 1 `*.verified.txt` file and 1 `*.verified.png` file.

Upgrade to Verify.Nunit 18.0.0 (19.1.0 behaves the same way) and run the same tests. All will fail because Verify is looking for the *verfied files as different filenames. Not only that, but now there are 2 json files that are between tested which are identical.

Below is a screenshot after running the tests. The file names in red were generated during the test and they don't match the filenames in white that are saved in source control
![image](https://user-images.githubusercontent.com/49491497/203415916-c6459ba8-8747-4dab-b203-464bba595acc.png)

### Development stack
I'm using Rider 2022.2.4 and .net 6.0.302, although  I don't think they are relevant to the problem. Also using the SixLabors.ImageSharp nuget package Version 2.1.3.

**Comment by SimonCropp** [comment]
isnt that covered by https://github.com/VerifyTests/Verify/blob/main/docs/upgrade17-18.md#use--to-delineate-nameindex  ?

**Comment by SimonCropp** [comment]
> doesn't explain why there are more .txt files than there should be

can u submit a failing unit test in a pull request

> Can I recommend linking to that upgrade document on that release page for version 18?

done
