### ISSUE TITLE
Argon vs NewtonsoftJson

### ISSUE THREAD

**Issue by ldeluigi** [VerifyTests/Verify#739]
It's difficult to mantain both Newtonsoft.Json json converters and Argon JsonConverters.

Please, consider providing an API adapter bewteen the two, so that I can pass a Newtonsoft JsonConverter where a Argon JsonConverter is expect (for example in settings.Converters.Add).

#### Is the feature request related to a problem

I can't use Newtonsoft converters with Verify.

#### Describe the solution

Use the patter [Adapter](https://en.wikipedia.org/wiki/Adapter_pattern).

#### Describe alternatives considered

You can integrate NewtonsoftJson adapters directly into Argon.

**Comment by SimonCropp** [comment]
I dont understand why you need to maintain so many converters?

At my current employer we have 38 test projects, and dont have any custom converters

Perhaps you could share a few class definitions that make it clear that the need for converters is more common that my current understanding?

**Comment by ldeluigi** [comment]
This is an extension of the standard library we are using in our project: https://github.com/EasyDesk/easydesk-tools

The class which gets often serialized badly is Option<T>:
https://github.com/EasyDesk/easydesk-tools/blob/master/src/EasyDesk.Tools/Options/Option.cs

Because it gets serialized as an IEnumerable, like `[{..}]` (some) or `[]` (none). Instead, we always want to get it serialized as `{...}` (some) or `null` (none).

**Comment by SimonCropp** [comment]
fair enough. happy to accept a PR to Argon that adds support for an  Adapter

**Comment by ldeluigi** [comment]
The problem is that the Argon project doesn't and shouldn't have a dependency to Newtonsoft.Json. Should I instead make a PR to https://github.com/VerifyTests/Verify.NewtonsoftJson?

**Comment by SimonCropp** [comment]
ok

**Comment by ldeluigi** [comment]
Done: https://github.com/VerifyTests/Verify.NewtonsoftJson/pull/1

**Comment by SimonCropp** [comment]
given https://github.com/VerifyTests/Verify.NewtonsoftJson/pull/1 is closed. i will close this one
