### ISSUE TITLE
VerifyDirectory show diff for text files on CI failure

### ISSUE THREAD

**Issue by yufeih** [VerifyTests/Verify#750]
#### Is the feature request related to a problem

When `VerifyDirectory` failed in CI, it dumps the full content of expected file and actual file. When the file is large, it becomes difficult to see the difference. In the example failure [here](https://github.com/dotnet/docfx/actions/runs/3730510591/jobs/6327650430), I need to manually copy the raw log, extract expected text and actual text, then diff it locally, which is time-consuming.

#### Describe the solution

When `VerifyDirectory` failed for text files in CI, show text diff. 

#### Additional context

Add any other context about the feature request here.

**Comment by SimonCropp** [comment]
would the compact option of Verify.DiffPlex work for you? https://github.com/VerifyTests/Verify.DiffPlex#output-types

**Comment by yufeih** [comment]
It works! Thanks for the help ❤️ 

Do you consider producing a condensed diff output by default for large text?
