### ISSUE TITLE
MSTest/NET48 hangs with custom file converter

### ISSUE THREAD

**Issue by TymurGubayev** [VerifyTests/Verify#751]
#### Description

Using MSTest 3.0.2, Verify commit cc00a5691799503520c1fd5933e6d8b6a6162d7a (02.01.2023) and custom file converter from [Verify.WinForms](https://github.com/VerifyTests/Verify.WinForms/blob/main/src/Verify.WinForms/VerifyWinForms.cs), the very basic test (`Verify(new Button())`) hangs.

#### Minimal Repro

Copy [VerifyWinForms.cs](https://github.com/VerifyTests/Verify.WinForms/blob/main/src/Verify.WinForms/VerifyWinForms.cs)
to `Verify.MSTest.Tests/WinForms/VerifyWinForms.cs`.

Create `Verify.MSTest.Tests/WinForms/UnitTest1.cs`:
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace UnitTestProject1;

[TestClass]
public class UnitTest1 : VerifyBase
{

    [ClassInitialize]
    public static void Init(TestContext context)
        => VerifyWinForms.Enable();

    [TestMethod]
    public Task TestMethod2()
    {
        var b = new Button();
        return Verify(b).AutoVerify();
    }
}
```

#### A solution or workaround

I tracked the problem down to [IoHelpers/WriteStream](https://github.com/VerifyTests/Verify/blob/main/src/Verify/IoHelpers.cs#L238), specifically this line:
```cs
await stream.CopyToAsync(targetStream)
```

Replacing it with
```cs
stream.CopyTo(targetStream);
```
fixes the issue.

**Comment by SimonCropp** [comment]
can you submit a pull request with a failing test

**Comment by SimonCropp** [comment]
I suspect the problem is vstests use of .GetAwaiter().GetResult() https://github.com/microsoft/testfx/issues/1284

Can you repro in xunit or nunit?

**Comment by TymurGubayev** [comment]
Added a PR with failing test.

Same test in NUnit works just fine.

There is some racing condition involved: when stepping through sometimes there is no deadlock.

**Comment by SimonCropp** [comment]
i dont think there is anything i can do in the Verify code. even changing `await stream.CopyToAsync(targetStream)` to be sync would only mitigate the problem. any async code could still deadlock. the only real fix is to make MStest properly respect async by removing the `.GetAwaiter().GetResult()`.

or alternatively you can move to xunit/nunit, or stop using Verify

**Comment by TymurGubayev** [comment]
It looks like it's a problem specifically with the combination of MSTest and WinForms, and this [StackOverflow answer](https://stackoverflow.com/a/20621341/5263865) (pointing to an implementation of [WindowsFormsContext](https://github.com/StephenCleary/AsyncCTPUtil/blob/master/AsyncTestUtilities/WindowsFormsContext.cs)) solves the issue.

**Comment by TymurGubayev** [comment]
Hi @Evangelink 

it fails consistently when I just run the test, just reproduced it on a different machine (source code from   https://github.com/TymurGubayev/Verify/commit/bb1c1119ef9cf161904cac0e95a8f7ab0f7b014c).
But when executing step by step while debugging the test it doesn't always deadlocks.
