### ISSUE TITLE
Global DisableDiff

### ISSUE THREAD

**Issue by marklagendijk** [VerifyTests/Verify#756]
#### Is the feature request related to a problem
I would like to be able to globally disable the diff tool from launching, this is currently not possible.
Reason being that I would rather launch it manually, when needed.
When there are many failures it can be annoying to close all the windows.

#### Describe the solution
Add a `DisableDiff` method to `VerifierSettings`.

#### Describe alternatives considered
I considered using `VerifierSettings.AutoVerify()`, but I would prefer that accepting would remain a manual action.

**Comment by SimonCropp** [comment]
https://github.com/VerifyTests/DiffEngine#disable-for-a-machineprocess

**Comment by SimonCropp** [comment]
> When there are many failures it can be annoying to close all the windows

DiffEngineTray makes that easier https://github.com/VerifyTests/DiffEngine/blob/main/docs/tray.md

**Comment by marklagendijk** [comment]
Awesome stuff!
I'm using the Rider plugin and prefer to accept the changes from the test result tree (it's really nice that accepting works on higher levels of the tree as well).

I must say that I'm quite impressed with all the features of this library. I have worked with snapshot testing within other contexts in the past, but the is definitely the most full-featured and easy-to-use solution I have seen so far.

For me the only thing that was tricky was finding the correct global configuration options, because they live on different classes. For example:
- `Verifier.DerivePathInfo`
- `DiffRunner.Disabled`
- `VerifierSettings.AutoVerify`

**Comment by SimonCropp** [comment]
Oh, and DiffEngineTray plays nicely with the Rider/R# plugin
