### ISSUE TITLE
QueueForVerification feature suggestion

### ISSUE THREAD

**Issue by benmccallum** [VerifyTests/Verify#762]
#### Is the feature request related to a problem

When doing more complicated multi-stage assertions, like a functional test, I typically do something like this:

```c#
var resultA = ActA();
var resultB = ActB();
var resultC = ActC();
Verify(new { resultA, resultB, resultC });
```

Or perhaps I'll collect action results up in a list, then verify the list.

Often if I've got a list, I'll have each member of that list not just be the result, but potentially be something like:
`new Result(resultA, "Vehicle was active, file says it's now inactive, should become inactive and ... ------------------------------");` so I can really easily identify each step and sort of describe what should be in the result below.

Although this works well, I wonder if there's room in Verify for something more native that would:
1. allow you to co-locate the "assertion" after the action (nice for next viewer, nice for not forgetting when you add a step in the middle that you'd need to add down bottom)
2. avoid the need for new'ing up a list or an anon object
3. improve readability of output (i.e. avoid the need for the anon object to have descriptive property names or the list item to have a property like "Step" with value "After Foo --------------------------------").

#### Describe the solution

Spit-balling, but something like

```c#
var resultA = ActA();
QueueForVerification(resultA);

var resultB = ActB();
QueueForVerification(resultB, header: "An optional header/delimiter");

var resultC = ActC();
QueueForVerification(resultC);

VerifyQueue();
```

Ideally the output we be super nice like:
```
resultA -----------------------------------------
{ ... }

resultB - An optional header/delimiter -------
{ ... }

resultC -----------------------------------------
{ ... }
```

Where the first part of the delimiter/heading could come from `CallerArgumentExpression` to get the variable name passed, the second part is the optional string, the last part is dashes up to x line length. Or I'm even thinking we could split the optional string down under the ---- and then it can be quite long and descriptive for when you're describing ins/outs/expected/etc. 

But we could just do a sorted array of `record QueueItem<T>(string Name, T Data)` as well and that'd prob be ok, maybe auto-adding dashes up to x chars in length to make it really readable.

#### Describe alternatives considered

Sort of covered this mentioning what I do now.

#### Additional context

Add any other context about the feature request here.

**Comment by SimonCropp** [comment]
so you want something equivalent to the recording feature of Verify.Sql ? https://github.com/VerifyTests/Verify.SqlServer#recording

**Comment by benmccallum** [comment]
Yea I guess that'd be one way to approach it

**Comment by SimonCropp** [comment]
can u submit a pr that illustrates this feature

**Comment by SimonCropp** [comment]
https://github.com/VerifyTests/Verify/blob/main/docs/recording.md
