### ISSUE TITLE
[Xunit] Parameterized tests in multi-targeted assembly give wrong filenames

### ISSUE THREAD

**Issue by asherber** [VerifyTests/Verify#765]
#### Describe the bug

When running a parameterized test, I expect the received/verified files to be named with the parameters, as described in [https://github.com/VerifyTests/Verify/blob/main/docs/parameterised.md](https://github.com/VerifyTests/Verify/blob/main/docs/parameterised.md)

If my test assembly is multitargeted, then the file names only use the target framework and do not use the input parameters.

I'm using VS 2022 v17.4.1, latest Verify packages from NuGet, writing a test assembly in .NET 6 and 4.6.2.

#### Minimal Repro

https://github.com/asherber/verify-filenames

This gets me one file called `UnitTest1.Test1.Net4_6.received.txt` and one called `UnitTest1.Test1.DotNet6_0.received.txt`. The input parameter is not used as part of the filename.

I haven't had time yet to debug through Verify source, will try to do so this weekend.

**Comment by SimonCropp** [comment]
for xnuit you need UseParameters https://github.com/VerifyTests/Verify/blob/main/docs/parameterised.md#useparameters

**Comment by asherber** [comment]
Ah, that's too bad -- and I think it's not clear from the docs, which imply that xUnit does expose parameter info for "certain types" but needs `UseParameters()` for complex types. Can you provide more info about what types xUnit can handle without `UseParameters()`? Or does it really need that method for all parameters? 

I'm happy to suggest a PR to clarify the docs once I understand the details of the situation.

**Comment by SimonCropp** [comment]
> which imply that xUnit does expose parameter info for "certain types" but needs UseParameters() for complex types

i dont know where that is implied

> Or does it really need that method for all parameters?

yes
