### ISSUE TITLE
TreatAsString() doesn't handle nested types

### ISSUE THREAD

**Issue by abiratur** [VerifyTests/Verify#770]
#### Is the feature request related to a problem

We have root objects with nested value types, so we would like to used TreatAsString to describe how to serialize them.
but apparently, TreatAsString only works on the "root" object being verified.
here is a simple repro of the issue.

```csharp
[UsesVerify]
public class UnitTest1
{
    [Fact]
    public async Task Test1()
    {
        var root = new Root { MyType = new MyType("hi") };

        VerifierSettings.TreatAsString<MyType>((target, _) => target.ToString());

        await Verify(root);
    }
}

class Root
{
    public MyType? MyType { get; set; }
}

class MyType
{
    private readonly string _s;

    public MyType(string s)
    {
        _s = s;
    }

    public override string ToString()
    {
        return _s;
    }
}
```

received:
![image](https://user-images.githubusercontent.com/22197855/214004439-73d05a2b-2cf2-45c0-a13d-c7c2ff93dd0a.png)

#### Proposed solution

Use typeToString mapping when serializing complex objects

**Comment by SimonCropp** [comment]
[TreatAsString](https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#treatasstring) bypasses serialization

> Certain types, when passed directly in to Verify, are written directly without going through json serialization

If u want to control type serialization in nested instances use a Json.NET Converter https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#jsonnet-converter

**Comment by FrancisGauthier** [comment]
i managed to make it work using the serializer extra settings with 

```
    [ModuleInitializer]
    public static void Init()
    {
        VerifierSettings.AddExtraSettings(settings =>
        {
            settings.Converters.Add(new ProvinceConverter ());
        });
    }

    private class ProvinceConverter : WriteOnlyJsonConverter<Province>
    {
        public override void Write(VerifyJsonWriter writer, Province province) => writer.WriteValue(province.Code);
    }

public sealed record Province 
{

    public string CodeIso => Code;

    public required string Code { get; init; }

    public required int Id { get; init; };

    public override string ToString() => Code;
}

```

from

`
    Province: {
      CodeIso: QC,
      Code: QC,
      Id: 1
    },
`

to 

`
  Province: QC,
`
