### ISSUE TITLE
[Argon] Cannot handle null value in a JSON string

### ISSUE THREAD

**Issue by deleteLater** [VerifyTests/Verify#773]
#### Preamble

I just can't create an issue in the [Argon](https://github.com/SimonCropp/Argon/issues/new/choose) repo, that's why I am here.

#### Minimal Repro
1. open this solution [Verify.SystemJson](https://github.com/VerifyTests/Verify.SystemJson/blob/main/src/Verify.SystemJson.sln)
2. find src/Tests/Tests.cs file and change line 10 from `"short": "foo"` to `"short": null`
3. run the tests and you can see the exception

#### Exception
Argon.JsonWriterException: Token PropertyName in state Property would result in an invalid JSON object. Path 'short'.

**Comment by SimonCropp** [comment]
can u try 1.0.1 of Verify.SystemJson
