### ISSUE TITLE
JaonIgnore attributes are not ignores

### ISSUE THREAD

**Issue by meirkr** [VerifyTests/Verify#798]
#### Describe the bug
Since upgrade to v18, properties in verified classes which are marked wit ]KspmIgnore] of NewtonSoft are not ignored anymore.

#### Minimal Repro
Have a property 

```
    /// <summary>
    /// logger
    /// </summary>
    [JsonIgnore]
    public ILogger<Client> ClientLogger { get; set; }
```

Then the verify started to output this property in received file, while in version prior to 18 it didn't.
```
    "Field: (6,6)": 182,
    "Field: (6,7)": 195
  },
  "ClientLogger": {}
}
```

Prior to 18:
```
    "Field: (6,6)": 182,
    "Field: (6,7)": 195
  }
}
```

**Comment by SimonCropp** [comment]
you need to move to `Argon.JsonIgnore`. or u can use https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#ignoring-a-type or https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#ignore-member-by-expressions
