### ISSUE TITLE
VerifyJson removes empty array ?

### ISSUE THREAD

**Issue by fforjan** [VerifyTests/Verify#802]
The issue is that the if a  JSON document as text given to parameter to VerifyJSON contains an empty array. The received document does NOT contains the empty array

See the sample here : https://github.com/fforjan/VerifyJsonIssue/tree/verifyjson ( you need the verifyjson branch)
it also contains the received and verified  you will get from a dotnet test:
![image](https://user-images.githubusercontent.com/601810/222988754-e3e8dac8-dcb9-4d00-af42-2b04ffb987f3.png)

![image](https://user-images.githubusercontent.com/601810/222988760-9ddc50e1-7c41-4a63-8aef-8b3ae0758f27.png)

**Comment by SimonCropp** [comment]
@fforjan https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#empty-collections-are-ignored

**Comment by fforjan** [comment]
@SimonCropp should this be set when using strict json ?

**Comment by SimonCropp** [comment]
@fforjan yes
