### ISSUE TITLE
Only show mismatched data between received & verified when failing on build server/terminal

### ISSUE THREAD

**Issue by jammehcow** [VerifyTests/Verify#803]
#### Is the feature request related to a problem

When verification of an object fails in a build server context, the entirety of both files (received & verified) are printed to the server's output. If the object being verified is a really large object (in my case, an entire `DbContext` instance using the `.AllData()` extension) the output window is flooded with two copies of the object which could be thousands of lines long - when only one line in the file could be different.

#### Describe the solution

Instead of dumping the full extent of both files, I would suggest a setting to "fold" or omit unchanged lines from the output should the verification fail. This keeps the overall output from the test small while still presenting the user/developer with the required information to fix the test.

I would also suggest that `x` amount of lines around the diffed line should be shown to provide context & line numbers should be preserved. This could also be a setting, but equally ~5 lines by default is probably fine.

#### Describe alternatives considered

 - Splitting the single "large" test into individual tests for each property (or entity set in my case)
   - This will blow out the size of my test fixtures and just provides more code for the same value
 - Only snapshotting/verifying the data that's expected to change
   - This makes sense in most cases, but the for tests I'm having this problem with I want to ensure that the entire object/DbContext hasn't changed

#### Additional context

Assuming you're happy with the design, I would be more than happy to implement this feature as it benefits both my work and personal projects using this library. Love the library, found it through Dan's Unhandled Exception podcast 🎉

**Comment by SimonCropp** [comment]
perhaps Diffplex with Compact output would work? https://github.com/VerifyTests/Verify.DiffPlex#output-types

**Comment by jammehcow** [comment]
I think that solves my problem. I'll double check later today and if that's the case, I'll close this issue off. Cheers Simon!

**Comment by SimonCropp** [comment]
did that work for you?

**Comment by jammehcow** [comment]
Sorry, yes it did! Cheers.

**Comment by SimonCropp** [comment]
@jammehcow glad it worked
