### ISSUE TITLE
Trailing comma for non-strict Json

### ISSUE THREAD

**Issue by Siphonophora** [VerifyTests/Verify#818]
#### Is the feature request related to a problem

I got the following diff after I removed a property from a model I was verifying. I got this for a bunch of tests and noticed the diff was harder to review than needed, because it looked like the date might have changed, but it was just the comma.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/32316111/225758705-11fcdc0d-c5ec-4e37-a3e3-1ca5526bcc2d.png">

#### Describe the solution

Change the non-strict json output to have trailing commas, to remove the extraneous diff results.

```
  Output: {
    IsOpen: false,
    LastTransitionTime: 2023-02-16 22:00 +0,
    NextTransitionTime: 2023-02-17 13:00 +0,
    IsGracePeriod: false
  },
... more content.
```

Becomes

```
  Output: {
    IsOpen: false,
    LastTransitionTime: 2023-02-16 22:00 +0,
    NextTransitionTime: 2023-02-17 13:00 +0,
    IsGracePeriod: false,
  },
... more content.
```

#### Additional context

I'm happy to take a stab at a PR if this looks like a good addition to you.

**Comment by SimonCropp** [comment]
yeah thats a good idea. happy to consider a PR. and will make a new major release that enables them

**Comment by Siphonophora** [comment]
Hi @SimonCropp  Just wondering if this would be in v21? I don't see it in 20 and wanted to ask. 

Thanks!

**Comment by SimonCropp** [comment]
@Siphonophora no one submitted a PR. so assuming it is no done

**Comment by Siphonophora** [comment]
@SimonCropp Ok, I had started working on a PR but stopped when you marked this completed. So, want to re-open it?
