### ISSUE TITLE
Consider removing implicit using of Xunit

### ISSUE THREAD

**Issue by glen-84** [VerifyTests/Verify#819]
#### Is the feature request related to a problem

We have two projects, `Api.IntegrationTests` and `Api.UnitTests`. We added a `Usings.cs` file to both with `global using Xunit;`, but the former showed:

> Using directive is unnecessary.

This was quite confusing, and it turns out that it's caused by `Verify.Xunit` adding an implicit using in `Verify.Xunit.props`.

I feel like this should be controlled by the developer, and not be imposed on them.

#### Describe the solution

I suggest removing `<Using Include="Xunit" />` from `Verify.Xunit.props`.

#### Describe alternatives considered

n/a

#### Additional context

This would likely be a breaking change, so it would need to happen in the next major.

**Comment by SimonCropp** [comment]
wouldn’t it be easier so suppress “ Using directive is unnecessary”

**Comment by glen-84** [comment]
No. I can remove the one Usings file, but that's beside the point.

It may seem trivial, but this forces us to have differing project structures – one with its own global usings, and one without. I like things to be consistent, and I'd prefer to have control of implicit usings.

It's one thing to add your own library's namespaces as implicit usings, but I don't think that it makes sense to add external namespaces on behalf of the developer.

**Comment by SimonCropp** [comment]
> It may seem trivial, but this forces us to have differing project structures – one with its own global usings, and one without. I like things to be consistent,

can you share a solution that illustrates this problem?

**Comment by glen-84** [comment]
Do you need an actual solution, or just an example of the structure?:

```
src
    Api
        Api.csproj
tests
    Api.IntegrationTests
        Api.IntegrationTests.csproj (uses Verify.Xunit)
        Usings.cs (global using Xunit;) ❌ Using directive is unnecessary.
    Api.UnitTests
        Api.UnitTests.csproj
        Usings.cs (global using Xunit;) ✅
```

We'd like to be able to control implicit usings, and have symmetry between test projects.

**Comment by SimonCropp** [comment]
the thing is, the using might be unenecessary, but i dont understand what the negative impact of that using is

**Comment by glen-84** [comment]
The negative impact is a warning. A warning that can be quite confusing for new developers.

![image](https://user-images.githubusercontent.com/261509/227772599-96454bdd-188f-45c5-8da4-c03ef9497bb5.png)

This code is added as part of the Xunit project template, as far as I know. Installing Verify.Xunit therefore "breaks" this by introducing an unnecessary import. The fact that you can remove this code or suppress the warning completely misses the point.

Why? What is the benefit of Verify adding this? The vast majority of Xunit projects will already have the global import.

**Comment by SimonCropp** [comment]
what cs compiler code is that warning?

**Comment by glen-84** [comment]
[IDE0005](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/style-rules/ide0005)

**Comment by SimonCropp** [comment]
i will accept a PR that allows consumers to opt out of this behaviour

**Comment by glen-84** [comment]
How would that be implemented, if this is in configuration?

I'm [not the only one](https://stackoverflow.com/a/75513764/221528) who thinks that this practice should be avoided.

**Comment by SimonCropp** [comment]
> How would that be implemented, if this is in configuration?

i dont know. what have you tried?

Side note you can disable this behavior by disabling `ImplicitUsings`

> I'm [not the only one](https://stackoverflow.com/a/75513764/221528) who thinks that this practice should be avoided.

Sorry. i will not be changing the current default behaviour

**Comment by glen-84** [comment]
> i dont know. what have you tried?

Nothing yet. I don't want to come up with some weird MS Build and/or environment variable hack. I shouldn't need to either.

> Side note you can disable this behavior by disabling ImplicitUsings

That would likely wipe out core namespaces like `System`, etc.

> Sorry. i will not be changing the current default behaviour

This is my last comment on the issue. Just some more [food for thought](https://github.com/spectreconsole/spectre.console/issues/515#issuecomment-902987551) (and this is the package itself, not a dependency of the package).

Anyway, thanks for maintaining Verify.

**Comment by adamralph** [comment]
I just hit this. I added a package reference to Verify.Xunit and suddenly every file in the project has a using statement for xunit. This doesn't seem like desirable behaviour.

**Comment by adamralph** [comment]
@SimonCropp BTW, the implicit using for `VerifyTests` is also problematic. In my case, I have a type name clash with `VerifyTests.Target`, which causes lots of errors in all the files which now have an implicit using for `VerifyTests`. I'm not convinced that a package should be adding implicit usings.

**Comment by SimonCropp** [comment]
u can manually remove it ` <Using Remove="thenamespace" />`

or i am happy to accept a PR that suppresses this behavior using a `<VerifyDisableImplicitUsings>true</VerifyDisableImplicitUsings>`

**Comment by adamralph** [comment]
> u can manually remove it ` <Using Remove="thenamespace" />`

👍 that's what I'm doing for now as a workaround.

> or i am happy to accept a PR that suppresses this behavior using a `<VerifyDisableImplicitUsings>true</VerifyDisableImplicitUsings>`

I'm not sure that adds much for me. It still means an extra step is required after installing the package to opt-out of behaviour which, IMO, shouldn't exist. My preference would be to remove the addition of implicit usings entirely, so I'd be willing to invest in that, but otherwise I guess I'll just live with the workaround.
