### ISSUE TITLE
Get rid of the empty.tar  (Verify.Xunit)

### ISSUE THREAD

**Issue by 304NotModified** [VerifyTests/Verify#822]
#### Is the feature request related to a problem
The empty.tar, from the https://www.nuget.org/packages/EmptyFiles/ gives policy errors in our binaries scan.

![image](https://user-images.githubusercontent.com/5808377/228243752-1a37bce8-28c6-4686-835a-417c9cb46b59.png)

#### Describe the solution
Is there a way to rid of the empty.tar? Could I remove it with a script without issues? 

#### Describe alternatives considered
It would be great if we don't have the EmptyFiles dependency, but I guess it's needed? For what feature is this needed?

**Comment by SimonCropp** [comment]
empty files is used for the diff tool launching https://github.com/VerifyTests/DiffEngine/blob/main/docs/diff-tool.md#initial-difference-behavior

not sure what the effects of deleting it would be. nuget might complain 

but imo u should fix the scanner. an empty compressed file should not be flagged

**Comment by 304NotModified** [comment]
To double check, the EmptyFiles packages isn't needed for the CI/CD? As we don't launch a diff tool over there. 

> but imo u should fix the scanner. an empty compressed file should not be flagged

It's not really empty? It's 2KB. 

![image](https://user-images.githubusercontent.com/5808377/228528907-411fdb76-5a0a-4d7f-a349-0fc6934eeca8.png)


Also the goal of this scanner is that there aren't unidentified binaries/code files in the build that could influence the result.
