### ISSUE TITLE
CustomContractResolver property name extensibility

### ISSUE THREAD

**Issue by MrJerB** [VerifyTests/Verify#849]
Thanks for providing such a lovely library ❤️

#### Problem Summary
A nuget package providing classes for serialization that we are passing to Verify has opted to add DataMemberAttribute with MemberName which we want to bypass to use the underlying property names. This is do-able by using our own ContractResolver, overriding CreateProperties/CreateProperty and voila! 

```
prop.Name = prop.UnderylingName;
```

However, to be able to solve one problem, we lose some of the lovely functionality built into the library (such as scrubbing), which we would like to avoid. We would also like to avoid creating copies of the POCOs without the attributes, although this could be our temporary solution.

#### Describe the solution

A way to "hook" into the virtual methods to enable modification of property name resolution in some way to keep using the `CustomContractResolver` provided by the library but still be able to use the underlying type name.

**Comment by SimonCropp** [comment]
can u share a failing test as a pull request
