### ISSUE TITLE
Make  `TargetAssembly` public

### ISSUE THREAD

**Issue by Gesma94** [VerifyTests/Verify#873]
#### Is the feature request related to a problem

I would like to implement a simpler version of Verify.MSTest by creating my own `VerifyBase`. I think it would be doable, but I would need `TargetAssembly` to be made `public` so that its state is set just like in your `VerifyBase`.

#### Describe the solution

I think it would be just enough to set `TargetAssembly` to `public` instead of the default `internal`.

#### Describe alternatives considered

An alternative would be to create special API that allows to create our own `Verify.XYZ`, where `XYZ` is any test tool.

#### Additional context

The reason for this is that I'd like to have the same usage of `Verify` across all the corporation.
I can indeed create a `MyVerifyBase` which extends `VerifyBase`, and that has a method `MyVerify`; but at that point, `MyverifyBase` would have all the methods from `VerifyBase` as well. Meaning, developers might choose to use different verify methods, like all the ones defined inside `verifyBase`.

**Comment by SimonCropp** [comment]
> I would like to implement a simpler version of Verify.MSTest 

in what way would it be simpler

> developers might choose to use different verify methods, like all the ones defined inside verifyBase.

why is this a problem?

**Comment by Gesma94** [comment]
> in what way would it be simpler
I'm sorry, let me try to explain better, which would also answer to why it could be a problem.

Basically, we want to force a set of rules in order to have same results in all our projects, which are maintained by different developers. For instance, we want all `verified` test files to be placed into a specific folder in the root of the project. To do so, we would use `useDirectory`, but all developers should remember to do so, and use the same exact option.

Instead, by creating `MyVerifyBase`, I can write my own `MyVerify` which uses by default a strict `useDirectory`.

Right now, though, developers could use both `MyVerifyBase.MyVerify` and `VerifyBase.Verify`, disrupting our rules.

> why is this a problem?
It may not be an actual problem, more a "nice-to-have", I guess.

**Comment by SimonCropp** [comment]
> For instance, we want all verified test files to be placed into a specific folder in the root of the project. To do so, we would use useDirectory, but all developers should remember to do so, and use the same exact option.

you can do that globally using https://github.com/VerifyTests/Verify/blob/main/docs/naming.md#derivepathinfo

are there any other conventions you would like you devs to follow?

**Comment by Gesma94** [comment]
I'm sorry, I was trying to wrap up our internal use.
No, right now I don't see any other conventions we want to follow, that cannot be made with the current Verify :)
