### ISSUE TITLE
Test result should not depend on Windows regional settings

### ISSUE THREAD

**Issue by Tolyandre** [VerifyTests/Verify#874]
#### Preamble

 * Rider 2023.1.1
 * net7.0
 * Windows 11 22H2
 * Verify.Xunit 19.14.1

#### Describe the bug

Method `VerifyJson()` looks for dates and replaces them with strings like `Date_1`.  It seems that the date pattern depends on OS regional settings. That means I end up with a different `*.received.txt` file on my Windows machine and in CI.

There are two runs below with different short-date formats in Windows (marked with a red arrow).

```cs
  const string json = """
      {
          "date1": "2023-05-05",
          "date2": "05/05/2023",
          "date3": "23/05/05"
      }
      """;

  await VerifyJson(json);
```

Given these Windows regional settings:
![image](https://user-images.githubusercontent.com/2414704/236495160-b0531592-bf74-4e2d-a53b-9d1af1066ec4.png)
![image](https://user-images.githubusercontent.com/2414704/236495872-24628822-a1e9-45b7-822b-3a3a6cf31f22.png)

Actual result (UnitTest1.Test1.received.txt):
```
{
  date1: Date_1,
  date2: 05/05/2023,
  date3: 23/05/05
}
```

```
{
  date1: 2023-05-05,
  date2: Date_1,
  date3: 23/05/05
}
```

Expected result:

The output of these two runs should be the same. It should not depend on regional settings.

I think it should use invariant culture until another is specified.

#### Minimal Repro

TestProject.cspoj
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
        <PackageReference Include="Verify.Xunit" Version="19.14.1" />
        <PackageReference Include="xunit" Version="2.4.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="3.1.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
</Project>
```

UnitTest1.cs
```cs
namespace TestProject;

[UsesVerify]
public class UnitTest1
{
    [Fact]
    public async Task Test1()
    {
        const string json = """
            {
                "date1": "2023-05-05",
                "date2": "05/05/2023",
                "date3": "23/05/05"
            }
            """;
        await VerifyJson(json);
    }
}
```

**Comment by SimonCropp** [comment]
yeah thats a bug. happy to accept a Pull request that fixes it

**Comment by JochemPalmsens** [comment]
@SimonCropp 
> I think it should use invariant culture until another is specified.
☝️ do you agree with this proposal?

**Comment by SimonCropp** [comment]
i think that will be problematic. people will have code that produces strings in their current local. and they will expect those values to be scrubbed

**Comment by JochemPalmsens** [comment]
@SimonCropp could you then maybe provide some requirements for any "Pull request that fixes it"? Would safe the person that implement it a lot of time and effort...

**Comment by JochemPalmsens** [comment]
🤷
