### ISSUE TITLE
Extend information of a SettingsTask to expose information about whether or not diff tool is being opened or not

### ISSUE THREAD

**Issue by taori** [VerifyTests/Verify#876]
#### Is the feature request related to a problem

I am dumping the contents of an openxml sdk file into several xml structures. If any of those parts have a difference i want to open that sdk file and analyze it in excel for example

#### Describe the solution

If settingstask contained the necessary paths for both the verified and received path of a comparison i would be able to compare the two files and spawn a process that opens excel on the sdk file. Currently however i only get the verified path, which by itself does not provide me with the means to know if there is a difference

#### Alternative solutions

Extending the SettingsTask returned from VerifyXXX and adding the information whether the diff tool was invoked or not would also provide me with the information necessary to open the excel file if there was a difference.

**Comment by taori** [comment]
VerifySettings.OnVerifyMismatch sort of is related to this issue. If the settings instance allowed to inject a delegate i could go this path too. But OnVerifyMismatch only exists as a static configuration.

**Comment by SimonCropp** [comment]
happy to consider a Pull Request for this
