### ISSUE TITLE
JsonIgnoreAttribute from Newtonsoft.Json doesn't work anymore

### ISSUE THREAD

**Issue by batzen** [VerifyTests/Verify#878]
#### Describe the bug

I am currently trying to upgrade to the latest Verify version.
Because Verify switched from Newtonsoft.Json to Argon the JsonIgnoreAttribute from Newtonsoft.Json stopped working.

As the data I want to verify is from classes that are used in production code and a switch from Newtonsoft.Json to Argon for the whole application is not desired, I can't verify the data properly anymore.

Possible solutions to this issue would be:
- modify `CustomContractResolver` from Verify to also check for the attribute from Newtonsoft.Json
- make `CustomContractResolver` public so consumers of Verify can override the behavior

Would a PR with one of the suggested solutions be accepted?

Is there any other way to configure this globally?
So far I haven't found a way to override this globally for all classes, just based on the `MemberInfo`.

**Comment by batzen** [comment]
While trying to make the required changes to Argon I noticed that there is also `IgnoreDataMemberAttribute` which might already solve the issue for me.
Will check that at work next week.

**Comment by SimonCropp** [comment]
did it work?

**Comment by batzen** [comment]
Sorry. Forgot to respond.

Yes it worked like a charm.
I just replaced all our usages of `JsonIgnoreAttribute` with `IgnoreDataMemberAttribute`.

I consider this solved.

**Comment by SimonCropp** [comment]
good to hear
