### ISSUE TITLE
Provide a "Next Steps" pathway after setting up Verify

### ISSUE THREAD

**Issue by aaronpowell** [VerifyTests/Verify#879]
I found the wizard a really helpful way to get Verify integrated into a project and write the first test, but after that I wasn't sure how to find the next thing to do with it, without going through all the different pages within the docs that are available.

#### Describe the solution

Having a "Next steps" section at the bottom of the last stage of the wizard ([using this as an example](https://github.com/VerifyTests/Verify/blob/main/docs/wiz/Windows_VisualStudio_Gui_MSTest_AzureDevOps.md) would help knowing what next to do, and also provide an entry point resource for onboarding other team members.

Here's an idea of the kinds of things that would be useful:

```
Next Steps

- Customise the naming conventions
- Working with data driven tests
- Ignoring connection strings, API keys and other secrets
``` 

These are the sorts of problems that I was looking to solve once I had Verify setup in the project.

**Comment by SimonCropp** [comment]
can you submit a pr for tuis
