### ISSUE TITLE
Generate a hash of parameters for the file name

### ISSUE THREAD

**Issue by aaronpowell** [VerifyTests/Verify#884]
Recently when using Verify for a set of data-driven tests I hit a problem when providing the `UseParameters` with the parameters of the test would cause the file name and path to be excessively long and cause problems on Windows.

#### Describe the solution

To work around this, I created a method that will take the parameters and generate a hash from them instead, since that will reduce the length of the file name, but also create something that is going to be consistent across test runs.

#### Additional context

The extension can be found here: https://github.com/Azure/data-api-builder/pull/1402/files#diff-0e9ff620b043280230cfc29acae2321e450546a8b2c86b3e8e3fa289a9b36a0f

**Comment by SimonCropp** [comment]
@aaronpowell i went with a slightly different approach https://github.com/VerifyTests/Verify/blob/main/docs/parameterised.md#hashing-parameters
