### ISSUE TITLE
Add "DontScrubDirectories" Method for Verify Settings

### ISSUE THREAD

**Issue by sirkiza** [VerifyTests/Verify#890]
Description:
Currently, the Verify framework automatically scrubs the temporary location with the `{TempPath}` parameter, and there is no way to disable or modify this behavior. We kindly request the addition of a new method called "DontScrubDirectories" that allows users to control the scrubbing process.

This feature is crucial for our testing purposes, as the current behavior breaks the expected behavior of our tests, making them dependent on the operating system where the tests are run. Our tests rely on retrieving expected files from a REST API, and the automatic scrubbing interferes with this process.

By introducing the "DontScrubDirectories" method, we would have the flexibility to disable the scrubbing of directories when necessary, ensuring consistent and reliable test results across different environments.

We appreciate your attention to this matter and kindly request your prompt action to address this issue. If you require any further information or clarification, please let us know. Thank you for your support.

**Comment by SimonCropp** [comment]
happy to consider a Pull Request for this change

**Comment by faze79** [comment]
I have this issue too during test execution that differ only for {TempPath} replacement.
Please add a boolean to skip this replacement...

**Comment by SimonCropp** [comment]
@faze79 happy to accept a PR for this

**Comment by SimonCropp** [comment]
@SteveLillis can u share a failing unit test as a pull request
