### ISSUE TITLE
Custom Diffing

### ISSUE THREAD

**Issue by LorneCash** [VerifyTests/Verify#918]
#### Is the feature request related to a problem

I've created a Custom Comparer to compare my log files because several operations are running async and therefore don't always finish (and get logged) in the same order.  The logic of my custom comparer specifies a block of lines that may happen in any order and then sorts those lines in both the received and verified strings before doing the comparison.  The comparison itself is working perfectly as far as I am aware and it seems like a good way to handle this type of case.  Here's the comparer code for reference:

``` C#
public static Task<CompareResult> LineComparerSortSubset(string received, string verified, IReadOnlyDictionary<string, object> context, int lineStart, int count)
{
	var receivedLines = received.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None).ToList();
	var verifiedLines = verified.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None).ToList();

	// Get and sort subsets
	var receivedSubset = receivedLines.Skip(lineStart - 1).Take(count).OrderBy(s => s).ToList();
	var verifiedSubset = verifiedLines.Skip(lineStart - 1).Take(count).OrderBy(s => s).ToList();

	// Replace original lines with sorted subsets
	for (var i = 0; i < receivedSubset.Count; i++)
	{
		receivedLines[lineStart - 1 + i] = receivedSubset[i];
		verifiedLines[lineStart - 1 + i] = verifiedSubset[i];
	}

	var isEqual = string.Join(Environment.NewLine, receivedLines) == string.Join(Environment.NewLine, verifiedLines);

	return Task.FromResult(new CompareResult(isEqual));
}
```

When the Custom Comparer finds a match everything is perfect but if it's not a match that's where I have a problem.  Specifically the problem is with the diffing tool and although some are better than others what I really want:

#### Describe the solution

Abstract solution:
I need a way send the modified received file's text (sorted in my specific case) to take the diff tool rather than the actual received file because otherwise it highlights lines as added/removed/modified if they're not in order and that's not useful to me I only want to see the lines that are missing/added highlighted.  It makes understanding the actual problem much harder.

Solution implementation:
There's so many different ways this could be implemented and I'm not familiar enough with source of this project to think that I could suggest the easiest/best way, but here are a few options to think about.

The Custom Comparer could have an option to modify/replace the actual received.txt file.
The Custom Comparer could have an option to create a modified received.txt file, ie. received.modified.txt.

#### Describe alternatives considered

I don't believe I could manually modify the received.txt because I believe it's created as part of the verify process and I am not aware of a way to interrupt it to do that.

I also can't easily modify the object being compared because I would need to run the scrubbers before I do that.  I could technically do this but it's not worth my time due to how much work the scrubbers doing for me.

#### Additional context

If I compare these two files:

Received:
1
2
4

Verified:
1
2
3

4 is added and 3 is missing very easy to understand but if instead the received file looks like this:

Received:
2
1
4

Then the comparison shows something like:
line 1: 2 != '' (line added)
line 2: 1  = 1  (line matches)
line 3: 2 != 3  (line missing/modified)
line 4: 4 != '' (line added)

I almost always look at diffs in side-by-side view so it's easy to compare but here its hard for me to articulate even this simple example but basically because this is relatively easy to understand that the line 1 "added" cancels out the line 3 "missing" and that really, it's line 3 "4" added and line 4 "3" missing.

**Comment by SimonCropp** [comment]
might help if u can share a failing test as a PR

**Comment by LorneCash** [comment]
@SimonCropp I'm sorry if I wasn't clear (and for the late reply), but in answer to your question:
would an alternative be to verify the sorted list of log entries?

Unless I'm misunderstanding what you're suggesting, I believe that's what I'm already doing with my Custom Comparer and as I stated the problem isn't with the compare itself passing or failing.  The Custom Comparer does that part perfectly.  There is no problem when it passes, and there is no problem with not failing or false positives like I said the Custom Comparer is working correctly so the fail is working correctly also.  The problem is after a failure when doing the diffing of the received.txt vs verified.txt.

When looking at the diff, it is very difficult to tell what the problem was because although the Custom Comparer is sorting and determining the correct result, the received.txt and verified.txt are not sorted and therefore VERY difficult to tell where the actual problem is.

With regard to creating a failing test as a PR:
Because of the nature of this problem, I can't be sure that it will fail predictably without manually forcing it which if you're not understanding how I'm describing the problem I'm not sure that would help you understand either.  I think what might help more is if I take screenshots of several different diffs I'm getting and try to point out how they are confusing/misleading and what I would like to see instead that would help me more clearly determine where the problem is.  That's what I was trying to do with the "Additional context" section in my original post, but I can understand that the diff highlighting could help make it easier to follow.

Would it be a completely ridiculous idea for me to suggest we do a short web meeting?  I'll try contacting you at your gmail if you're open to that.

**Comment by SimonCropp** [comment]
i am open to having a call.  

but can u answer this one first https://github.com/VerifyTests/Verify/issues/918#issuecomment-1594336028

> would an alternative be to verify the sorted list of log entries?

**Comment by LorneCash** [comment]
You asked, "would an alternative be to verify the sorted list of log entries?" and that's where I think the misunderstanding is.  Unless I'm misunderstanding your question, I believe I'm already doing that with the custom comparer.  The verify process (pass/fail) is working perfectly with the custom comparer.  

My enhancement request would not change anything about how the compare works but rather what information is sent to the diff (written to the recieved.txt) which obviously only happens after a failure.

I've created a sample project:
[VerifySortedLog.zip](https://github.com/VerifyTests/Verify/files/12032884/VerifySortedLog.zip)

It has two examples of different failures, one where the line ("Test Item 103") is missing and the other where it's added.  Each Failure has two variants one where the order is random and another where the order is sorted.
The tests are:
- Pass
- TestMethod1_Fail_Missing103OrderSorted
- TestMethod1_Fail_Missing103OrderRandom
- TestMethod1_Fail_Added103OrderSorted
- TestMethod1_Fail_Added103OrderRandom

If you look at the diff of:
    "UnitTest1.TestMethod1_Fail_Missing103OrderSorted.received.txt" to 
    "UnitTest1.TestMethod1_Fail_Missing103OrderSorted.verified.txt"
it's easy to see that one line is missing.

If you look at the diff of:
    "UnitTest1.TestMethod1_Fail_Missing103OrderRandom.received.txt" to
    "UnitTest1.TestMethod1_Fail_Missing103OrderRandom.verified.txt"
it's really hard to tell what the actual problem is.

...but in both cases the problem is the same they're both missing the line "Test Item 103".

<img width="822" alt="image" src="https://github.com/VerifyTests/Verify/assets/17584221/8660a238-2464-4021-9014-73a44ddcc8eb">

If you look at the diff of:
    "UnitTest1.TestMethod1_Fail_Added103OrderSorted.received.txt" to 
    "UnitTest1.TestMethod1_Fail_Added103OrderSorted.verified.txt"
it's easy to see that one line is added.

If you look at the diff of:
    "UnitTest1.TestMethod1_Fail_Added103OrderRandom.received.txt" to
    "UnitTest1.TestMethod1_Fail_Added103OrderRandom.verified.txt"
again, it's really hard to tell what the actual problem is.

...but in both cases the problem is the same they both have the added line "Test Item 103".

<img width="824" alt="image" src="https://github.com/VerifyTests/Verify/assets/17584221/bae3559b-f22f-4fdb-98cf-4e85b8dde206">

I'm hoping this will clear up any confusion, but I'd still love to talk for a min just to be sure everything is clear and possibly discuss how you think the best way to handle this would be.  I emailed you my contact info a couple days ago.

**Comment by LorneCash** [comment]
@SimonCropp have you had a chance to review my last post?

**Comment by SimonCropp** [comment]
i am still failing to grasp what is the problem here. if i look at your repro, and accept all the changes, the tests pass moving forward

could you submit a minimal  failing test repro as a pull request?

**Comment by LorneCash** [comment]
@SimonCropp I sent you a message in google chat to arrange a call.

**Comment by LorneCash** [comment]
@SimonCropp Is there a better way that I should reach you outside of github?  I've tried emailing and using google chat and I haven't seen any response.  Did I miss something? Are you still willing to talk?
