### ISSUE TITLE
VerifyXml method does not work correctly with empty tags

### ISSUE THREAD

**Issue by callmekoo** [VerifyTests/Verify#935]
Method VerifyXml expects opening and closing tags instead of empty tag.

Test to reproduce:
```
[Fact]
public Task EmptyTag() => VerifyXml("<body><empty /><node>text</node></body>");
```
This test fails with error, received file contains this xml:
```
<body>
  <empty></empty>
  <node>text</node>
</body>
```
Obviously, this is not correct xml, the empty tag should be a single tag.

The bug has been reproduced since version 19.8.2, in older versions everything works correctly.

**Comment by SimonCropp** [comment]
do you want to have a go at fixing this?

**Comment by callmekoo** [comment]
I'll try it this weekend, but I'm not quite sure of my skills.
