### ISSUE TITLE
Verifier.Verify wrapper around Debug.Assert

### ISSUE THREAD

**Issue by jzabroski** [VerifyTests/Verify#951]
#### Is the feature request related to a problem

When in debug mode, I would like to be able to replace Debug.Assert with Verifier.Verify to compare two instances.

#### Describe the solution

1. New solution csproj, Verify.Diagnostics w/ corresponding nuget package
2. Implementation similar to Verify.Expecto except without the F# dependencies
3. Class Verify.Diagnostics.Debug w/ method Assert that has two overloads:
     1. Assert<TLeft, TRight>(string snapshotName, TLeft left, TRight right);
     2. Assert<TLatest>(string snapshotName, TLatest latest);

First Assert would take a snapshot of the left, save it, then snapshot the right.

#### Describe alternatives considered

Use https://github.com/replaysMike/AnyDiff instead of Verify

#### Additional context

I tried AnyDiff already, and the performance to compare even tiny object graphs (~100 lines of JSON serialized into an object tree) was absolutely terrible. :(

**Comment by SimonCropp** [comment]
wont this be problematic since in release mode u would have a ref Verify.Diagnostics, Verify, DiffEngine, EmptyFiles, and Argon?

**Comment by SimonCropp** [comment]
so your intent is that neither of the snapshots file would be written to disk? (or at least not written to the source controlled directory)

**Comment by jzabroski** [comment]
Writing it to disk would be very useful, actually, but what I really want written to disk is the patch file if there are differences.

Basically, one use case I have for this is to test whether the API I am using has certain isomorphic properties.

For example, I learned yesterday that on Save, they capitalize the Name property of an object, but then return back the saved object with the original, un-capitalized Name, I sent in, and only enrich the saved object with its newly minted Id, CreatedDate, UpdatedDate fields.

Having things with persistent snapshots and diffs would allow me to continuously keep this vendor on a short leash.  They're an industry leader but they lack a lot of formal development practices (like continuous delivery - they deploy everything manually in the year 2023).

**Comment by SimonCropp** [comment]
> Writing it to disk would be very useful, actually, but what I really want written to disk is the patch file if there are differences.

so doesnt that mean you really want Verify to work as it is now?

**Comment by jzabroski** [comment]
Are you asking, Why can't I just use the Verify package as standalone?

I would say, because Verify has a lot of internal helper assemblies.

I would actually like it yo work like Verify.Expecto (without the f# helpers) , since I think that's the right basic API to use Verify as a base library.

**Comment by SimonCropp** [comment]
happy to expose some internals of verify if they are useful. 

how about your submit a PR that does that, and shoes some use cases in tests
