### ISSUE TITLE
Verify and datatable. Localization problem.

### ISSUE THREAD

**Issue by sybaris** [VerifyTests/Verify#971]
#### Preamble
 * Visual Studio 2022 on a french PC

#### Bug description
My unit test do this :
`await Verify(dataTable);`
I saved my .verified.txt file, and add it to my git repo.
All is fine on my PC. The problem is when I use Azure DevOps CI, this tests fails.
Note that other tests that verify anything else are ok.
When I compare received.txt & verified.txt files, the only difference is this :
received.txt :
```
...
  HasErrors: false,
  Locale: fr-FR,
  Rows: [
...
```
verified.txt :
```
...
  HasErrors: false,
  Locale: en-US,
  Rows: [
...
```

#### Minimal Repro
To reproduce, run this test on a French PC : 
```
    [TestClass]
    public class UniTest : VerifyMSTest.VerifyBase
    {
        [TestMethod]
        public async Task TestDataTable()
        {
          await Verify(new DataTable());
        }
    }
```
Save verified.txt file. It will contains Locale: **fr-FR**.
Then run the same test on azure devops CI
Save received.txt file. It will contains Locale: **en-US**.

#### Workaround
Do you have any workaround for this problem ?

**Comment by SimonCropp** [comment]
```
public static class ModuleInit
{
    [ModuleInitializer]
    public static void Init() =>
        VerifierSettings.IgnoreMember<DataTable>(_ => _.Locale);
}
```

**Comment by sybaris** [comment]
Hi 

Thanks for your answer, but when I include this piece of code, I have the following error : 
Error	CS0122	**'ModuleInitializerAttribute' is inaccessible due to its protection level**

Metadata on ModuleInitializerAttribute indicate that the class is in    System.Runtime.CompilerServices namespace and DiffEngine.dll assembly

Regards
Sybaris

**Comment by SimonCropp** [comment]
u can polyfill ModuleInitializerAttribute with https://github.com/SimonCropp/Polyfill or any of the other polyfill libs
