### ISSUE TITLE
Is 21.0 available or is someone hacking the  nuget package ?

### ISSUE THREAD

**Issue by fforjan** [VerifyTests/Verify#986]
Verify 21.0.0 is available on nuget.org 
![image](https://github.com/VerifyTests/Verify/assets/601810/81cf2bfb-ce55-4c19-b7a0-f3b7a6cb7c61)

but I do not see any release on github

![image](https://github.com/VerifyTests/Verify/assets/601810/c061457b-17e3-4a17-bf55-206e7fa18ea1)

For me it means I cannot trust 21.0.0 and someone has hacked the nuget.org package.

What did I miss ?

**Comment by SimonCropp** [comment]
for some reason my release notes publishing script failed

https://github.com/VerifyTests/Verify/releases/tag/21.0.0
