### ISSUE TITLE
Verify.Specification

### ISSUE THREAD

**Issue by stefannikolei** [VerifyTests/Verify#987]
I would love to have an package to verify usage of https://github.com/ardalis/Specification.

I would contribute that feature. 

How can this be tackled? It is hard to throw up an PR because there is no Repo for this (Every package lives in its own Repo...)

**Comment by SimonCropp** [comment]
you can create your own Repo for Specification support

**Comment by SimonCropp** [comment]
@stefannikolei bump

**Comment by stefannikolei** [comment]
Yeah I am looking into it. But it also seems after looking closer into the standard behavior that it probably is sufficient.
